*** Settings ***
Documentation   Test Suite - Call Center QA Leader Portal - Archirved studies
Metadata    sid     BFCC-QALEAD-ARCHIVED-STUDY
Metadata    owner   Nhan Nguyen
Library     Collections
Library     corelib/AssertionExtension.py
Library     corelib/WebHandler.py   ${BROWSER}  ${HEADLESS}
Library     project_bioflux_callcenter_portal/lib/ConfigHandler.py    ${ENV}
Library       project_bioflux_callcenter_portal/lib/web/Common.py
Library       project_bioflux_callcenter_portal/lib/web/Events.py
Library       project_bioflux_callcenter_portal/lib/web/EventDetails.py
Library       project_bioflux_callcenter_portal/lib/web/Reports.py
Library       project_bioflux_callcenter_portal/lib/web/StudyManagement.py
Library       project_bioflux_callcenter_portal/lib/web/Studies.py

Suite Setup     Suite Setup
Suite Teardown      Suite Teardown
Force Tags      BFCC-QALEAD-ARCHIVED-STUDY   web
Test Timeout    1h

*** Test Cases ***
BFCC-QALEAD-ARCHIVED-STUDY-01: Study management page-Display banner "This study has been archived."
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-01      auto   CP-2.16.7
    Navigate To Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    Manage Complete Study On        row=1
    ${msg}          Get Message Banner
    Run Keyword And Continue On Failure    Should Be Equal    ${msg}        This study has been archived.

BFCC-QALEAD-ARCHIVED-STUDY-02: Study mangement page >> Reports tab-Display AI status is "NA" for EOU report
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-02      auto   CP-2.16.7
    Navigate To Tab Menu      Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    Manage Complete Study On        row=1
    Navigate To Study Management Type    Reports
    ${reports}          Get Study Reports
    ${new_report_status}        Evaluate    [item for item in ${reports} if item.get('Type') == 'End Of Use']
    Run Keyword And Continue On Failure    Should Be Equal    ${new_report_status}[0][New Report Status]      N/A

BFCC-QALEAD-ARCHIVED-STUDY-02-1-CP2.16.9: Study mangement page >> Events tab-Display Invalid events BUT not display strip
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-02-1-CP2.16.9      manual   CP-2.16.9
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-03: Reports page >> Pending tab-All reports shall be removed from the list when study is aborted
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-03      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-04: Study management page >> Reports tab-Cannot Create Interim report manually (button disabled)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-04      auto   CP-2.16.7
    Navigate To Tab Menu      Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    Manage Complete Study On        row=1
    Navigate To Study Management Type    Reports
    ${interim_report}       Check Active Create Interim Available
    Run Keyword And Continue On Failure    Should Not Be True    ${interim_report}

BFCC-QALEAD-ARCHIVED-STUDY-05: Study management page >> Reports tab-Only view Interim report (instead of Edit button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-05      auto   CP-2.16.7
    Navigate To Tab Menu      Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    Manage Complete Study On        row=1
    Navigate To Study Management Type    Reports
    ${report}       Get Study Reports
    ${report_id}    Evaluate    [item for item in ${report} if item.get('Type') == 'Interim']
    ${report_id}    Set Variable    ${report_id}[0][Report ID]
    ${text_view}    View Reports On     report_id=${report_id}
    Run Keyword And Continue On Failure    Should Be Equal    ${text_view}   View
    ${header}       Get Current Page Header
    Run Keyword And Continue On Failure    Should Be Equal    ${header}         INTERIM REPORT
    ${active_button}    Check Active Event Report Available
    ${active_button_interim}        Check Active Event Interim Report Available
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Generate Report]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Upload Report]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Assigned]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Priority]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Dismiss]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Recall]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Mark Or Unmark]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Save Report]
    Run Keyword And Continue On Failure    Should Be True    ${active_button}[Status Report]
    Run Keyword And Continue On Failure    Should Be True    ${active_button}[Download Report]
    Run Keyword And Continue On Failure    Should Be True    ${active_button_interim}[Email]

BFCC-QALEAD-ARCHIVED-STUDY-06: Study management page >> Reports tab-Only view EOU report (instead of Edit button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-06      auto   CP-2.16.7
    Navigate To Tab Menu      Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    Manage Complete Study On        row=1
    Navigate To Study Management Type    Reports
    ${report}       Get Study Reports
    ${report_id}    Evaluate    [item for item in ${report} if item.get('Type') == 'End Of Use']
    ${report_id}    Set Variable    ${report_id}[0][Report ID]
    ${text_view}    View Reports On     report_id=${report_id}
    Run Keyword And Continue On Failure    Should Be Equal    ${text_view}   View
    ${header}       Get Current Page Header
    Run Keyword And Continue On Failure    Should Be Equal    ${header}         END OF USE REPORT
    ${active_button}    Check Active Event Report Available
#    ${active_button_interim}        Check Active Event Interim Report Available
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Generate Report]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Upload Report]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Assigned]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Priority]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Dismiss]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Recall]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Mark Or Unmark]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Save Report]
    Run Keyword And Continue On Failure    Should Be True    ${active_button}[Status Report]
    Run Keyword And Continue On Failure    Should Be True    ${active_button}[Download Report]
#    Run Keyword And Continue On Failure    Should Be True    ${active_button_interim}[Email]

BFCC-QALEAD-ARCHIVED-STUDY-06-1: Study management page >> Reports tab-Only view Notification/Event report (instead of Edit button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-06-1      auto   CP-2.16.7
    Navigate To Tab Menu      Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    Manage Complete Study On        row=1
    Navigate To Study Management Type    Reports
    Filter Study Reports    by_report=Notification reports
    ${report}       Get Study Reports
    ${text_view}    View Reports On     row=1
    Run Keyword And Continue On Failure    Should Be Equal    ${text_view}   Edit report
    ${header}       Get Current Page Header
    Run Keyword And Continue On Failure    Should Be Equal    ${header}         EVENT
    ${active_button}    Check Active Event Report Available
#    ${active_button_interim}        Check Active Event Interim Report Available
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Generate Report]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Upload Report]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Assigned]
    Run Keyword And Continue On Failure    Should Not Be True    ${active_button}[Priority]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Dismiss]
#    Run Keyword And Continue On Failure    Should Not Be True    ${active_button_interim}[Recall]
    Run Keyword And Continue On Failure    Should Be True    ${active_button}[Status Report Technician]
    Run Keyword And Continue On Failure    Should Be True    ${active_button}[Download Report]
#    Run Keyword And Continue On Failure    Should Be True    ${active_button_interim}[Email]

BFCC-QALEAD-ARCHIVED-STUDY-07: Event report details page >> Cannot select a priority (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-07      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-08: Event report details page >> Cannot dismiss a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-08      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-09: Event report details page >> Cannot Ready a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-09      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-10: Event report details page >> Can download a report
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-10      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-11: Event report details page >> Cannot upload a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-11      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-12: Event report details page >> Can Fax a report manually once the report is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-12      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-13: Event report details page >> Can email a report once the report is Sent
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-13      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-13-1: Event report details page >> Cannot re-enable a report (disabled button) once the report is dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-13-1      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-14: Event report details page >> Cannot generate a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-14      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-15: Event report details page >> Cannot re-generate a report (disabled button) once report status is not Sent/Dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-15      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-16: Event report details page >> Cannot Send a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-16      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-17: Event report details page >> Cannot recall a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-17      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-18: Event report details page >> Cannot assign a report (disabled button) once report status is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-18      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-19: Notification report details page >> Cannot select a priority (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-19      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-20: Notification report details page >> Cannot dismiss a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-20      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-21: Notification report details page >> Cannot Ready a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-21      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-22: Notification report details page >> Can download a report
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-22      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-23: Notification report details page >> Cannot upload a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-23      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-24: Notification report details page >> Can Fax a report manually once the report is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-24      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-25: Notification report details page >> Can email a report once the report is Sent
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-25      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-26: Notification report details page >> Cannot re-enable a report (disabled button) once the report is dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-26      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-27: Notification report details page >> Cannot generate a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-27      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-28: Notification report details page >> Cannot re-generate a report (disabled button) once report status is not Sent/Dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-28      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-29: Notification report details page >> Cannot Send a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-29      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-30: Notification report details page >> Cannot recall a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-30      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-31: Notification report details page >> Cannot assign a report (disabled button) once report status is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-31      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-31-1: Notification report details page >> Cannot change call status (Call requires, Call Completed, No call) (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-31-1      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-32: Interim report details page >> Cannot select a priority (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-32      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-33: Interim report details page >> Cannot dismiss a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-33      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-34: Interim report details page >> Cannot Ready a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-34      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-35: Interim report details page >> Can download a report
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-35      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-36: Interim report details page >> Cannot upload a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-36      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-37: Interim report details page >> Can Fax a report manually once the report is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-37      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-38: Interim report details page >> Can email a report once the report is Sent
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-38      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-39: Interim report details page >> Cannot re-enable a report (disabled button) once the report is dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-39      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-40: Interim report details page >> Cannot generate a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-40      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-41: Interim report details page >> Cannot re-generate a report (disabled button) once report status is not Sent/Dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-41      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-42: Interim report details page >> Cannot Send a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-42      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-43: Interim report details page >> Cannot recall a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-43      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-44: Interim report details page >> Cannot assign a report (disabled button) once report status is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-44      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-45: Interim report details page >> Cannot mark/unmark a report as artifact (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-45      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-45-1: EOU report details page >> Cannot select a priority (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-45-1      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-46: EOU report details page >> Cannot dismiss a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-46      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-47: EOU report details page >> Cannot Ready a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-47      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-48: EOU report details page >> Can download a report
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-48      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-49: EOU report details page >> Cannot upload a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-49      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-50: EOU report details page >> Can Fax a report manually once the report is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-50      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-51: EOU report details page >> Can email a report once the report is Sent
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-51      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-52: EOU report details page >> Cannot re-enable a report (disabled button) once the report is dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-52      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-53: EOU report details page >> Cannot generate a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-53      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-54: EOU report details page >> Cannot re-generate a report (disabled button) once report status is not Sent/Dismissed
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-54      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-55: EOU report details page >> Cannot Send a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-55      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-56: EOU report details page >> Cannot recall a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-56      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-57: EOU report details page >> Cannot assign a report (disabled button) once report status is Ready
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-57      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-58: EOU report details page >> Cannot mark/unmark a report as artifact (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-58      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-58-1: Holter/Ext.Holter/MCT Peek EOU report details page >> Cannot re-generate report in Afib Avg HR section (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-58-1      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-59: Event details page >> Cannot save a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-59      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-59-1: Notification report details page >> Cannot save a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-59-1      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-59-2: Interim report details page >> Cannot save a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-59-2      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-59-3: EOU report details page >> Cannot save a report (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-59-3      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-60: Studies page >> Cannot download zipfile (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-60      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-61: Study details page >> Study info-Cannot download zipfile (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-61      auto
    Navigate To Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    Manage Complete Study On        row=1
    ${zip_file}         Check Active Study Details Available
    Run Keyword And Continue On Failure    Should Not Be True     ${zip_file}[Zip File]

BFCC-QALEAD-ARCHIVED-STUDY-62: Quick access study info >> Cannot download zipfile (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-62      auto
    Navigate To Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    View Completed Studies Study Information On    row=1
    ${zip_file}         Check Active Study Details Available
    Run Keyword And Continue On Failure    Should Not Be True     ${zip_file}[Zip File]

BFCC-QALEAD-ARCHIVED-STUDY-63: Check UI when having more than one user is on the same report
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-63      manual   CP-2.16.7
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-QALEAD-ARCHIVED-STUDY-64: Quick access study info >> Display msg "This study has been archived."
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-64     auto
    Navigate To Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    View Completed Studies Study Information On    row=1
    ${msg}          Get Message Banner
    Run Keyword And Continue On Failure    Should Be Equal    ${msg}        This study has been archived.

BFCC-QALEAD-ARCHIVED-STUDY-65: Quick access event info >> Cannot edit technician comment (disabled button)
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-65       auto
    Navigate To Studies
    Navigate To Studies Type        Completed
    Filter Studies          search_by=Study ID      text_search=${STUDY_ID_ASSIGN}[study_id_archived]
    View Completed Studies Event Details On    row=1
    View Study Event Information On     row=1
    ${edit_technician_comment}      Check Active Edit Event Technician
    Run Keyword And Continue On Failure    Should Not Be True    ${edit_technician_comment}

BFCC-QALEAD-ARCHIVED-STUDY-66-CP-2.23.0: Quick access to device info
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1. General info: Model - it can be
    ...     - Bioflux
    ...     - Biocore: if the Auto-events detection for the device, there shall be a message displayed next to the device model – (Auto-events detection enabled).
    ...     - Biocore Pro
    ...     - Time zone
    ...     - Firmware version
    ...     - Operator
    ...     - Network mode
    ...     - Device lifetime - the total time of the device in use since the first study and it is counted by day and month
    ...     if its lifetime is less than 1 year- ex: 1 month 3 days or month and year if its lifetime is equal to or greater
    ...     than 1 year - ex: 1 year 3 months
    ...     2. Last Synced Status
    ...     - RSSI
    ...     - Lead on
    ...     - Battery level
    ...     - SD card free space
    ...     - Charging state
    ...     - Last connect
    ...
    ...     **Others
    ...     Update date: 5/28/2024 - Trinh Nguyen

    [Tags]      BFCC-QALEAD-ARCHIVED-STUDY-66-CP-2.23.0        manual    CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

*** Keywords ***
SUITE SETUP
    ${BROWSER_NODE}      Start Browser
    Import Library          project_bioflux_callcenter_portal/lib/web/Common.py             ${BROWSER_NODE}     ${ENV}
    Import Library          project_bioflux_callcenter_portal/lib/web/Events.py             ${BROWSER_NODE}     ${ENV}
    Import Library          project_bioflux_callcenter_portal/lib/web/EventDetails.py       ${BROWSER_NODE}     ${ENV}
    Import Library          project_bioflux_callcenter_portal/lib/web/Reports.py            ${BROWSER_NODE}     ${ENV}
    Import Library          project_bioflux_callcenter_portal/lib/web/StudyManagement.py    ${BROWSER_NODE}     ${ENV}
    Import Library          project_bioflux_callcenter_portal/lib/web/Studies.py            ${BROWSER_NODE}     ${ENV}
    ${USERS}                Get Config Param    NEW_USERS
    ${STUDY_ID}             Get Config Param    STUDY_ID
    ${CURRENT_USER}         Set Variable        ${USERS}[callcenter_qaleader]
    ${STUDY_ID_ASSIGN}      Set Variable        ${STUDY_ID}[study_id_completed]
    ${RELEASE_VERSION}      Navigate To Callcenter Sign In Page
    ${TOKEN}                Sign In Callcenter  ${CURRENT_USER}[username]      ${CURRENT_USER}[password]
    Set Suite Variable      ${TOKEN}
    Set Global Variable     ${STUDY_ID_ASSIGN}
    Set Suite Metadata   version   ${RELEASE_VERSION}
    Set Suite Metadata   browser   ${BROWSER.capitalize()}

SUITE TEARDOWN
    Quit Browser
