*** Settings ***
Documentation   Test Suite - Call Center AI - Process Reports
Metadata    sid     BFCC-AIRP-ACCESS-LIMITATION
Metadata    owner   Hoang Nguyen
Library     corelib/AssertionExtension.py
Library     Collections
Library     corelib/WebHandler.py   ${BROWSER}  ${HEADLESS}
Library     project_bioflux_ai_report_portal/lib/ConfigHandler.py    ${ENV}
Library     project_bioflux_ai_report_portal/lib/web/Reports.py
Library     project_bioflux_ai_report_portal/lib/web/Common.py
Library     project_bioflux_ai_report_portal/lib/web/Studies.py
Library     project_bioflux_ai_report_portal/lib/web/EcgEvent.py
Library     project_bioflux_ai_report_portal/lib/web/StudyManagement.py
Library     project_bioflux_ai_report_portal/lib/web/EventDetails.py
Library     project_bioflux_ai_report_portal/lib/web/StripsManagement.py

Suite Setup     Suite Setup
Suite Teardown      Suite Teardown
Force Tags      BFCC-AIRP-ACCESS-LIMITATION  web
Test Timeout    30m
*** Test Cases ***
BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-01:Verify the number of studies opened at the same time on the same account
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-01      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-02:Verify pop-up warning and provide a list of the studies displayed when opening studies exceeding the allowed number
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-02      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-03:Verify pop-up limit warning and provide a list of the studies displayed when opening the Beats&HR page
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-03      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-04:Verify pop-up limit warning and provide a list of the studies displayed when opening the ECG Event page
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-04      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-05:Verify pop-up limit warning and provide a list of the studies displayed when update Findings
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-05      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-06:Verify pop-up limit warning and provide a list of the studies displayed when generate report ( if there was a beats update before )
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-06      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-07:Verify the permitted number is only calculated when opening the Beats&HR page
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-07      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-08:Verify the permitted number is only calculated when opening the ECG Event page
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-08      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-09:Verify the permitted number is only calculated when update Findings
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-09      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-10:Verify the permitted number is only calculated when generate report ( if there was a beats update before )
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-10      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-11:Verify new study will not be limited after stop old study
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-11      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-12:Verify popup "Study processing limit reached" displays correct study is open
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-CALLCENTER-12      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-01:Verify the newly created admin account the "new reporting engine's access limitation" is set to 3 by default.
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-01      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-02:Verify Admin account logged in with newly created SSO, "New reporting engine's access limitation" is set to default
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-02      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-03:Verify enter value from 1 to 10 in New reporting engine access limitation
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-03      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-04:Verify enter Invalid value in New reporting engine access limitation
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-04      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-05:Verify no value entered in New Reporting Tool Access Limits
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-05      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-06:Verify the number of opened studies matches the number entered in "New reporting engine's access limitation"
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-06      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-07:Verify the newly created admin account the "new reporting engine's access limitation" is set to 3 by default.
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-07      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-08:Verify enter value from 1 to 10 in New reporting engine access limitation
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-08      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-09:Verify enter Invalid value  in New reporting engine access limitation
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-09      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-10:Verify no value entered in New Reporting Tool Access Limits
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-10      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCC-AIRP-ACCESS-LIMITATION-ADMIN-11:Verify the number of opened studies matches the number entered in "New reporting engine's access limitation"
    [Documentation]     Author: Hoang Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...
    ...     **Others**
    ...     Create date: 09/26/2024 - Hoang Nguyen
    ...
    [Tags]  BFCC-AIRP-ACCESS-LIMITATION-ADMIN-11      AIRP-1.11.0       manual      R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}