
FROM jenkins/jenkins:lts

USER root

# Install the Docker client inside the Jenkins container so Jenkins can interact with the Docker host
RUN apt-get update && apt-get install -y \
    docker.io \
    lsb-release \
    curl \
    gnupg2 \
    unzip \
    && apt-get clean

# "Optional: Install Git if Jenkins uses Git pipelines
RUN apt-get install -y git

# Create a directory to mount the source code if needed
RUN mkdir -p /jenkins_docker_cicd && chmod -R 777 /jenkins_docker_cicd

USER jenkins
