# Image Selenium Chrome chính chủ
FROM selenium/standalone-chrome:latest

USER root

# Cài các dependency cần thiết
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-setuptools \
    libpq-dev \
    python3-psycopg2 \
    make \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy project code vào container
COPY . /jenkins_docker_cicd

RUN ls -la /jenkins_docker_cicd/tmp

# Đúng tên file:
RUN chmod +x /jenkins_docker_cicd/tmp/chromedriver.exe

# Thêm vào PATH nếu bạn dùng .exe:
ENV PATH="/jenkins_docker_cicd/tmp:${PATH}"

# Cấp quyền
RUN chmod -R 777 /jenkins_docker_cicd

WORKDIR /jenkins_docker_cicd

# Cài thư viện Python
RUN pip3 install --no-cache-dir -r requirements_raw.txt

# Healthcheck đơn giản
HEALTHCHECK --interval=15s --timeout=5s --start-period=5s --retries=3 CMD ["echo", "healthy"]
