FROM selenium/standalone-chrome:latest

USER root

# Install necessary dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-setuptools \
    libpq-dev \
    python3-psycopg2 \
    make \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install the latest version of Google Chrome
RUN wget -qO - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && apt-get install -y google-chrome-stable

# Copy project code into the container
COPY . /jenkins_docker_cicd

# Grant permissions
RUN chmod -R 777 /jenkins_docker_cicd

#Set working directory for the project
WORKDIR /jenkins_docker_cicd

# Install Python libraries
RUN pip3 install --no-cache-dir -r requirements_raw.txt

# Healthcheck
HEALTHCHECK --interval=15s --timeout=5s --start-period=5s --retries=3 CMD ["echo", "healthy"]
