version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    ports:
      - "8080:8080"
#      - "8081:8080"  (port binding)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
#      - ./:/jenkins_docker_cicd  (optional)
    # Use only if Jenkins needs direct access to host code (no Git checkout).
    # Not needed if pipeline pulls code from Git and builds image with source.
    user: root

volumes:
  jenkins_home:
