WEB_BASE_URL: https://delta.cardiac.bioflux.io
API_BASE_URL: https://gateway.delta.cardiac.bioflux.io
USER:
  physician:
    - name: Physician Qa Team 01
      username: physician_qa_team_01
      password: Welcomeqa1#
    - name: Physician Qa Team 02
      username: physician_qa_team_02
      password: Welcomeqa1#
  nurse:
    - name: Technician Qa Team 01
      username: nurse_qa_team_01
      password: Welcomeqa1#
    - name: Technician Qa Team 02
      username: nurse_qa_team_02
      password: Welcomeqa1#
    - name: Technician Qa Team 03
      username: nurse_qa_team_03
      password: Welcomeqa1#
  facilities:
    - Facility_QA_01
    - Facility_QA_02
  patient:
    - Patient Qa 01 # new registered patient
    - Patient Qa 02 # active patient
    - Patient Qa 03 # active patient
    - Patient Qa 04 # new registered patient
    - Patient Qa 05 # new registered patient
    - Patient Qa 06 # new registered patient
    - Patient Qa 07 # new registered patient
    - Patient Qa 08 # new registered patient
    - Patient Qa 09 # new registered patient
    - Patient Qa 10 # new registered patient
    - Patient Qa 11 # new registered patient
    - Patient Qa 12 # new registered patient
    - Patient Qa 13 # new registered patient
    - Patient Qa 14 # new registered patient
    - Patient Qa 15 # new deleted patient
    - Patient Qa 16 # new registered patient
    - Patient Qa 17 # new registered patient
    - Patient Qa 18 # active patient (active HM study (Not start))
    - Patient Qa 19 # active patient
    - Patient Qa 20 # active patient
