# Appointment summary
APPTSUM_TABS = 'xpath://div[@class="appointment-info-drawer-header"]//span[@class="tab-header"]'
APPTSUM_TAB1_TOPINFO = 'class:patient-info-title'
APPTSUM_TAB1_BOTTOMINFO_HEADER = 'xpath://div[contains(@class, "left-item") or @class="registered-clinic" or @class="display-caregiver-wrapper-title"]'
APPTSUM_TAB1_BOTTOMINFO_CONTENT = 'xpath://div[contains(@class, "right-item") or contains(@class, "mt8") or contains(@class, "ant-space-vertical")]'
APPTSUM_TAB2_HEADER = 'class:appointment-info-show-title'
APPTSUM_TAB2_CONTENT1 = 'xpath:(//div[@class="appointment-info-show-title"])[1]/../div[2]'
APPTSUM_TAB2_CONTENT2 = 'xpath://div[contains(@class, "past-appointment-card-show")]'
APPTSUM_CLOSE_INFO = 'class:appointment-info-drawer-header-close-btn'
APPTSUM_GOTOPATIENTDETAIL = 'xpath://div[contains(@class, "appointment-info") and contains(@class, "right")]//div[@class="patient-info-drawer-footer"]/button/..'
# New appointment
NEWAPPTS_NEXTSTEP = 'xpath://button[@type="submit"]'
NEWAPPTS_BACK = 'class:ant-page-header-back-button'
NEWAPPTS_BACK_YES = 'xpath://div[@class="ant-modal modal-send-report"]//button[contains(@class, "custom-button") and not(contains(@class, "primary"))]'
NEWAPPTS_P1_CLINIC = 'xpath:(//*[@class="create-appointment-step-1"]//input[@type="search"])[1]'
NEWAPPTS_P1_CLINIC_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="facility"]'
NEWAPPTS_P1_PATIENT = 'class:ant-radio-wrapper'
NEWAPPTS_P1_PATIENTNAME = 'xpath:(//*[@class="create-appointment-step-1"]//input[@type="search"])[2]'
NEWAPPTS_P1_PATIENTNAME_OPTIONS = 'class:main-name'
NEWAPPTS_P2_TYPES = 'class:ant-radio-wrapper'
NEWAPPTS_P2_DATE = 'name:date'
NEWAPPTS_P2_DATE_TODAY = 'xpath://*[@class="create-appointment-step-1"]//a[@class="ant-picker-today-btn"]'
NEWAPPTS_P2_TIME = 'xpath://input[@placeholder="Select time"]'
NEWAPPTS_P2_DURATION = 'xpath:(//*[@class="create-appointment-step-1"]//div[contains(@class, "select-wrapper") and not(contains(@class, "attendee"))]//input[@role="combobox"])[1]'
NEWAPPTS_P2_DURATION_OPTIONS = 'xpath://div[@option="[object Object]" and @title]'
NEWAPPTS_P2_REASON = 'xpath:(//*[@class="create-appointment-step-1"]//div[contains(@class, "select-wrapper") and not(contains(@class, "attendee"))]//input[@role="combobox"])[2]'
NEWAPPTS_P2_REASON_OPTIONS = 'xpath://*[@class="rc-virtual-list"]//div[@option="[object Object]" and @label and @title]'
NEWAPPTS_P2_NURSE = 'xpath:(//*[@class="create-appointment-step-1"]//div[contains(@class, "select-wrapper attendee")])[1]//input'
NEWAPPTS_P2_NURSE_OPTIONS = 'class:attendee-info-name'
NEWAPPTS_P2_PHYSICIAN = 'xpath:(//*[@class="create-appointment-step-1"]//div[contains(@class, "select-wrapper attendee")])[2]//input'
NEWAPPTS_P2_PHYSICIAN_OPTIONS = 'xpath:(//*[@class="rc-virtual-list"])[last()]//div[@option="[object Object]" and @label]'
NEWAPPTS_P2_NOTICE = 'xpath://div[@class="new-patient-notice"]'
NEWAPPTS_P3_ADDMED = 'xpath://button[contains(@class, "add-medication-btn")]'
NEWAPPTS_P3_ADDMED_MEDICATION = 'xpath:(//div[@class="add-medication-modal-body"]//input)[1]'
NEWAPPTS_P3_ADDMED_MEDICATION_OPTIONS = 'xpath://div[contains(@id, "react-select")]'
NEWAPPTS_P3_ADDMED_QTY = 'xpath://input[@placeholder="Enter quantity"]'
NEWAPPTS_P3_ADDMED_UNIT = 'xpath:(//div[@class="add-medication-modal-body"]//input)[3]'
NEWAPPTS_P3_ADDMED_UNIT_OPTIONS = 'xpath://div[contains(@class, "ant-select-item-option") and @title]'
NEWAPPTS_P3_ADDMED_FREQ = 'xpath:(//div[@class="add-medication-modal-body"]//input)[4]'
NEWAPPTS_P3_ADDMED_FREQ_OPTIONS = 'xpath://div[contains(@class, "ant-select-item-option") and @title]'
NEWAPPTS_P3_ADDMED_TIMETOTAKES = 'xpath://input[@placeholder="Select date"]'
NEWAPPTS_P3_ADDMED_NOTES = 'xpath://textarea[@placeholder="Notes..."]'
NEWAPPTS_P3_ADDMED_SAVE = 'xpath://span[text()="Save"]'
NEWAPPTS_P3_ANSWERS = 'xpath://input[@placeholder="Your anwer ..."]'
NEWAPPTS_P4_ADDMED_NOTE = 'name:notes'
NEWAPPTS_P4_ADDMED_CREATE = 'class:next-btn'
# Appointment details
APPTDET_CANCELAPPT = 'xpath://span[text()="Cancel appointment"]'
APPTDET_DONEAPPT = 'xpath://span[text()="Mark as done"]'
APPTDET_OVERDUEAPPT = 'xpath://span[text()="Mark as overdue"]'
APPTDET_CANCELAPPT_YES = 'xpath://div[@class="ant-modal-content"]//span[text()="Yes"]/..'
APPTDET_LEFT_HEADER = 'xpath://div[@class="appointment-detail-left"]//div[contains(@class, "data-item left-item") or @class="display-caregiver-wrapper-title"]'
APPTDET_LEFT_CONTENT_BASIC = 'xpath://div[@class="appointment-detail-left"]//div[contains(@class, "data-item right-item")]'
APPTDET_LEFT_CONTENT_ATTENDEES = 'xpath://div[@class="appointment-detail-left"]//span[contains(@class, "ant-typography")]'
APPTDET_LEFT_CONTENT_ACTIONS = 'xpath://div[@class="appointment-detail-left"]//button[not(contains(@class, "link") or contains(@class, "edit"))]'
APPTDET_LEFT_CONTENT_FINALSTATUS = 'class:done-status'
APPTDET_RIGHTTABS = 'class:tab-header'
APPTDET_CONDINFO_HEADER = 'class:condition-infor-title'
APPTDET_CONDINFO_CONTENT = 'xpath://*[contains(@class, "condition-infor-title")]/../*[2]'
APPTDET_VITALS_HEADER = 'xpath://div[@class="appointment-detail-right"]//*[contains(@class, "left-item")]'
APPTDET_VITALS_CONTENT = 'xpath://div[@class="appointment-detail-right"]//div[@class="vital-form"]'
APPTDET_FINISHACTIONS = 'xpath://div[@class="appointment-detail-left"]/button[contains(@class, "ant-btn")]'
APPTDET_CONFIRM = 'xpath://div[@class="confirmation-layout-footer"]//button'
APPTDET_BACK = 'class:ant-page-header-back-button'
APPTDET_EDIT = 'xpath://div[@class="appointment-detail-wrapper"]//span[@aria-label="edit"]/..'
#Edit appointment
EDITAPPT_TYPE = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//label[contains(@class, "ant-radio-wrapper")]'
EDITAPPT_DATE = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//input[@placeholder="Select date"]'
EDITAPPT_DATE_CLEAR = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//input[@placeholder="Select date"]/..//span[@class="ant-picker-clear"]'
EDITAPPT_DATE_TODAY = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//a[@class="ant-picker-today-btn"]'
EDITAPPT_TIME = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//input[@placeholder="Select time"]'
EDITAPPT_TIME_CLEAR = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//input[@placeholder="Select time"]/..//span[@class="ant-picker-clear"]'
EDITAPPT_DURATION = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="ant-select-selector"])[1]'
EDITAPPT_DURATION_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@option and @aria-selected]'
EDITAPPT_NURSE = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="ant-select-selector"])[2]//input'
EDITAPPT_NURSE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "item-option")]'
EDITAPPT_NURSE_CLEAR = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="ant-select-selector"])[2]/..//span[@class="ant-select-clear"]'
EDITAPPT_PHYSICIAN = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="ant-select-selector"])[3]//input'
EDITAPPT_PHYSICIAN_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "item-option")]'
EDITAPPT_PHYSICIAN_CLEAR = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="ant-select-selector"])[3]/..//span[@class="ant-select-clear"]'
EDITAPPT_SAVE = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="footer-btns"]//button[contains(@class, "ant-btn-primary")]'