TABS = 'class:tab-header'
# In-progress
INP_FILTER = 'xpath://div[contains(@id, "panel-In progress")]//button[contains(@class, "filter-button")]'
INP_FILTER_STARTDATE = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//div[contains(@class, "start-date")]//input'
INP_FILTER_ENDDATE = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//div[contains(@class, "end-date")]//input'
INP_STATUSES = 'xpath:(//div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//div[contains(@class, "checkbox-group")])[1]//input[@type="checkbox"]'
INP_DURATIONS = 'xpath:(//div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//div[contains(@class, "checkbox-group")])[2]//input[@type="checkbox"]'
INP_APPLY = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//button[contains(@class, "btn-primary")]'
INP_CLEAR = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//button[not(contains(@class, "btn-primary"))]'
INP_BYPATIENT = 'xpath://div[contains(@id, "panel-In progress")]//div[@class="ant-select-selector"]'
INP_BYPATIENT_OPTIONS = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//div[@class="ant-select-item-option-content"]'
INP_SEARCHBY = 'xpath://div[contains(@id, "panel-In progress")]//div[@class="search-bar-wrapper"]//span[@aria-label="control"]'
INP_SEARCHBY_OPTIONS = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//span[@class="ant-dropdown-menu-title-content"]'
INP_TEXTSEARCH = 'xpath://div[contains(@id, "panel-In progress")]//div[@class="search-bar-wrapper"]//input'
INP_DATA_HEADER = 'xpath://div[contains(@id, "panel-In progress")]//table//th[contains(@class, "ant-table-cell")]'
INP_DATA_CONTENT = 'xpath://div[contains(@id, "panel-In progress")]//table//tr[@data-row-key]/td'
INP_DATA_CONTENT_ROW = 'xpath://div[contains(@id, "panel-In progress")]//table//tr[@data-row-key]'
INP_DATA_CONTENT_PATIENTNAME = 'xpath://div[contains(@id, "panel-In progress")]//table//tr[@data-row-key]//button[contains(@class, "text-color-blue")]'
# Ready for biller
BILLER_FILTER = 'xpath://div[contains(@id, "panel-Ready for biller")]//button[contains(@class, "filter-button")]'
BILLER_STARTDATE = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//div[contains(@class, "start-date")]//input'
BILLER_ENDDATE = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//div[contains(@class, "end-date")]//input'
BILLER_STATUSES = 'xpath:(//div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//div[contains(@class, "checkbox-group")])[1]//input[@type="checkbox"]'
BILLER_APPLY = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//button[contains(@class, "btn-primary")]'
BILLER_CLEAR = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]/ul//button[not(contains(@class, "btn-primary"))]'
BILLER_BYPATIENT = 'xpath://div[contains(@id, "panel-Ready for biller")]//button[contains(@class, "filter-button")]/following-sibling::div'
BILLER_BYPATIENT_OPTIONS = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//div[@class="ant-select-item-option-content"]'
BILLER_SEARCHBY = 'xpath://div[contains(@id, "panel-Ready for biller")]//div[@class="search-bar-wrapper"]//span[@aria-label="control"]'
BILLER_SEARCHBY_OPTIONS = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//span[@class="ant-dropdown-menu-title-content"]'
BILLER_TEXTSEARCH = 'xpath://div[contains(@id, "panel-Ready for biller")]//div[@class="search-bar-wrapper"]//input'
BILLER_DATA_HEADER = 'xpath://div[contains(@id, "panel-Ready for biller")]//table//th'
BILLER_DATA_CONTENT = 'xpath://div[contains(@id, "panel-Ready for biller")]//table//tr[@data-row-key]//td'
BILLER_DATA_CONTENT_CHECKBOXES = 'xpath://div[contains(@id, "panel-Ready for biller")]//table//tr[@data-row-key]//td//input[@type="checkbox"]'
BILLER_DATA_CONTENT_PATIENTNAME = 'xpath://div[contains(@id, "panel-Ready for biller")]//table//tr[@data-row-key]//button[contains(@class, "text-color-blue")]'
BILLER_DATA_CONTENT_ROW = 'xpath://div[contains(@id, "panel-Ready for biller")]//table//tr[@data-row-key]'
BILLER_DATA_CONTENT_STATUS = 'xpath://div[contains(@id, "panel-Ready for biller")]//table//tr[@data-row-key]//button[contains(@class, "hide-button-prevent")]'
BILLER_DATA_CONTENT_STATUS_OPTIONS = 'xpath://div[contains(@class, "dropdown") and not(contains(@class, "-hidden"))]//div[@class="ant-select-item-option-content"]'
BILLER_CREATEMASTERBILL = 'xpath://div[contains(@id, "panel-Ready for biller")]//button[contains(@class, "create-bill-btn")]'
BILLER_CREATEMASTERBILL_GENERATE = 'xpath://div[@class="create-bill-btn-container"]//button[contains(@class, "btn-primary")]'
#  Summary masterbill
SUMBILL_DATA_HEADER = 'xpath://div[@class="master-bill"]//div[contains(@class, "summary-item-bold")]'
SUMBILL_DATA_CONTENT = 'xpath://div[@class="master-bill"]//div[@class="summary-item"]'
SUMBILL_CLOSE = 'xpath://span[text()="Close"]/..'
