STATUS = 'xpath:(//div[@class="monthly-reports-wrapper"]//div[contains(@class, "select-ct-wrapper")])[1]'
STATUS_OPTIONS = 'xpath:(//div[@class="monthly-reports-wrapper"]//div[contains(@class, "select-ct-wrapper")])[1]//div[@class="ant-select-item-option-content"]'
PATIENT = 'xpath:(//div[@class="monthly-reports-wrapper"]//div[contains(@class, "select-ct-wrapper")])[2]'
PATIENT_OPTIONS = 'xpath:(//div[@class="monthly-reports-wrapper"]//div[contains(@class, "select-ct-wrapper")])[2]//div[@class="ant-select-item-option-content"]'
SEARCHBY = 'xpath://div[@class="monthly-reports-wrapper"]//span[contains(@class, "search-filter-btn")]'
SEARCHBY_OPTIONS = 'xpath://ul[contains(@class, "search-menu-wrapper")]//span[@class="ant-dropdown-menu-title-content"]'
SEARCH_TEXTBOX = 'xpath://div[@class="monthly-reports-wrapper"]//input[contains(@placeholder, "Search by")]'
HEADER = 'xpath://div[@class="monthly-reports-wrapper"]//thead[@class="ant-table-thead"]//th'
CONTENT = 'xpath://div[@class="monthly-reports-wrapper"]//tbody//tr[@data-row-key]/td'
CONTENT_ROW = 'xpath://div[@class="monthly-reports-wrapper"]//tbody/tr[@data-row-key]'
CONTENT_PATIENTNAME = 'xpath://div[@class="monthly-reports-wrapper"]//tbody[@class="ant-table-tbody"]//td[3]//button'
