SEARCHBY = 'xpath://div[@class = "patients-body-main"]//span[contains(@class, "search-filter-btn")]'
SEARCHBY_OPTIONS = 'xpath://div[@class="search-menu-title"]/parent::ul//li[@data-menu-id]'
SEARCH_TEXTBOX = 'xpath://div[@class = "patients-body-main"]//input[contains(@placeholder, "Search by")]'
HEADER = 'xpath://div[@class="notification-reports-wrapper"]//th'
CONTENT = 'xpath://div[@class="notification-reports-wrapper"]//div[@class = "patients-body-main"]//tr[@data-row-key]/td'
CONTENT_PATIENTNAME = 'xpath://div[@class="notification-reports-wrapper"]//tbody//td[2]//button'
CONTENT_ROW = 'xpath://div[@class="notification-reports-wrapper"]//tbody//tr[@data-row-key]'
PRIORITY = 'xpath:(//div[@class="patients-body-main"]//div[@class="ant-select-selector"])[2]'
PRIORITY_OPTIONS = 'xpath://div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
STATUS = 'xpath:(//div[@class="patients-body-main"]//div[@class="ant-select-selector"])[1]'
STATUS_OPTIONS = 'xpath://div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
PATIENT = 'xpath:(//div[@class="patients-body-main"]//div[@class="ant-select-selector"])[3]'
PATIENT_OPTIONS = 'xpath://div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
