BYPATIENT = 'xpath://div[@class="patients-active-wrapper"]//div[@class="select-ct-wrapper"]//div[@class="ant-select-selector"]'
BYPATIENT_OPTIONS = 'xpath://div[@class="patients-active-wrapper"]//div[@class="ant-select-item-option-content"]'
SEARCHBY = 'xpath://div[@class="patients-active-wrapper"]//*[contains(@class, "search-filter-btn")]'
SEARCHBY_OPTIONS = 'xpath://div[@class="search-menu-title"]/..//li[@data-menu-id]'
TEXTSEARCH = 'xpath://div[@class="patients-active-wrapper"]//input[contains(@placeholder, "Search by")]'
DATA_HEADER = 'xpath://div[@class="patients-active-wrapper"]//th[contains(@class, "ant-table-cell") and not(contains(@class, "px"))]'
DATA_HEADER_STARTDATE = 'xpath://div[@class="patients-active-wrapper"]//th[contains(@class, "ant-table-column-has-sorters")][1]'
DATA_HEADER_NEXTFUDATE = 'xpath://div[@class="patients-active-wrapper"]//th[contains(@class, "ant-table-column-has-sorters")][2]'
DATA_CONTENT = 'xpath://div[@class="patients-active-wrapper"]//tr[@data-row-key]//td[@class="ant-table-cell"]'
DATA_CONTENT_ROOT = 'xpath://div[@class="patients-active-wrapper"]//tbody/tr[@data-row-key]'
DATA_CONTENT_PATIENTNAME = 'xpath://div[@class="patients-active-wrapper"]//tbody/tr[@data-row-key]//button[contains(@class, "text-color-blue")]'
DATA_CONTENT_CALENDARICON = 'xpath://div[@class="patients-active-wrapper"]//td[contains(@class, "ant-table-cell")][last()]'
