TABS = 'xpath://*[@class="tab-header"]'
MANAGETEMPLATES = 'xpath://div[@class="div-add-new-patient"]//button[1]'
ADDNEWPATIENT = 'xpath://div[@class="div-add-new-patient"]//button[2]'
# Registered
REG_STATUS = 'xpath://div[contains(@id, "panel-Registered")]//div[@class="ant-select-selector"]'
REG_STATUS_OPTIONS = 'xpath://div[contains(@id, "panel-Registered")]//div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "item-option")]'
REG_SEARCHBY = 'xpath://div[contains(@id, "panel-Registered")]//*[contains(@class, "search-filter-btn")]'
REG_SEARCHBY_OPTIONS = 'xpath:(//*[contains(@class, "search-menu-wrapper")])[1]//li[@data-menu-id]'
REG_TEXTSEARCH = 'xpath://div[contains(@id, "panel-Registered")]//input[contains(@placeholder, "Search by")]'
REG_DATA_HEADER = 'xpath://div[contains(@id, "panel-Registered")]//th[@class="ant-table-cell"]'
REG_DATA_CONTENT = 'xpath://div[contains(@id, "panel-Registered")]//tr[@data-row-key]//td[@class="ant-table-cell"]'
REG_DATA_CONTENT_ROOT = 'xpath://div[contains(@id, "panel-Registered")]//tbody/tr'
REG_DATA_CONTENT_PATIENTNAME = 'xpath://div[contains(@id, "panel-Registered")]//td[@class="ant-table-cell"]//button[contains(@class, "text-color-blue")]'
REG_CALENDARICON = 'xpath://div[contains(@id, "panel-Registered")]//td[contains(@class, "ant-table-cell")][last()]'
# Assigned
ASN_BYPATIENT = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//div[@class="ant-select-selector"]'
ASN_BYPATIENT_OPTIONS = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//div[@class="ant-select-item-option-content"]'
ASN_SEARCHBY = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//span[contains(@class, "search-filter-btn")]'
ASN_SEARCHBY_OPTIONS = 'xpath:(//*[contains(@class, "search-menu-wrapper")])[last()]//li[@data-menu-id]'
ASN_TEXTSEARCH = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//input[contains(@placeholder, "Search by")]'
ASN_DATA_HEADER = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//thead//th[@class="ant-table-cell"]'
ASN_DATA_CONTENT = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//tr[@data-row-key]//td[@class="ant-table-cell"]'
ASN_DATA_CONTENT_PATIENTNAME = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//tbody/tr[@data-row-key]//button[contains(@class, "text-color-blue")]'
ASN_DATA_CONTENT_ROW = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//tbody/tr[@data-row-key]'
ASN_CALENDARICON = 'xpath://div[contains(@id, "panel-Healthcare Team Assigned")]//tbody/tr[@data-row-key]/td[last()]'
# Deleted
DEL_BYPATIENT = 'xpath://div[contains(@id, "panel-Deleted")]//div[@class="ant-select-selector"]'
DEL_BYPATIENT_OPTIONS = 'xpath://div[contains(@id, "panel-Deleted")]//div[contains(@class, "select-dropdown")]//div[@class="ant-select-item-option-content"]'
DEL_SEARCHBY = 'xpath://div[contains(@class, "tabpane-active") and contains(@id, "panel-Deleted")]//div[@class="search-bar-wrapper"]//span[@aria-label="control"]'
DEL_SEARCHBY_OPTIONS = 'xpath://div[contains(@class, "placement-bottomRight") and not(contains(@class, "hidden"))]//ul[contains(@class, "ant-dropdown-menu")]//li[@role="menuitem"]'
DEL_SEARCHBOX = 'xpath://div[contains(@id, "panel-Deleted")]//div[@class="search-bar-wrapper"]//input[@class="ant-input"]'
DEL_DATA_HEADER = 'xpath://div[contains(@id, "panel-Deleted")]//thead//th[not(contains(@class, "px"))]'
DEL_DATA_CONTENT = 'xpath://div[contains(@id, "panel-Deleted")]//tr[@data-row-key]//td[@class="ant-table-cell"]'
DEL_DATA_CONTENT_ROW = 'xpath://div[contains(@id, "panel-Deleted")]//tbody/tr[@data-row-key]'
DEL_DATA_CONTENT_PATIENTNAME = 'xpath://div[contains(@id, "panel-Deleted")]//tbody/tr[@data-row-key]/td//button[contains(@class, "text-color-blue")]'
DEL_DATA_RESTORE = 'xpath://div[contains(@id, "panel-Deleted")]//tbody/tr[@data-row-key]/td[contains(@class, "px")]//button'
DEL_DATA_RESTORE_YES = 'xpath://div[@class="ant-modal-content"]//button[contains(@class, "ant-btn-primary")]'
# New
NEW_STATUS = 'xpath:(//div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//div[@class="ant-select-selector"])[1]'
NEW_STATUS_OPTIONS = 'xpath://div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
NEW_BYPATIENT = 'xpath:(//div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//div[@class="ant-select-selector"])[2]'
NEW_BYPATIENT_OPTIONS = 'xpath://div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
NEW_SEARCHBY = 'xpath://div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//span[contains(@class, "search-filter-btn")]'
NEW_SEARCHBY_OPTIONS = 'xpath://div[contains(@class, "placement-bottomRight") and not(contains(@class, "hidden"))]//ul[contains(@class, "ant-dropdown-menu")]//li[@role="menuitem"]'
NEW_SEACHBOX = 'xpath://div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//div[@class="search-bar-wrapper"]//input[@class="ant-input"]'
NEW_DATA_HEADER = 'xpath://div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//thead//th[not(contains(@class, "px"))]'
NEW_DATA_CONTENT = 'xpath://div[contains(@id, "panel-New")]//tr[@data-row-key]//td[@class="ant-table-cell"]'
NEW_DATA_CONTENT_ROW = 'xpath://div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//tbody//tr[@data-row-key]'
NEW_CALENDARICON = 'xpath://div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//tbody//tr[@data-row-key]//td[contains(@class, "px")]'
NEW_DATA_CONTENT_PATIENTNAME = 'xpath://div[contains(@class, "tabpane-active") and contains(@id, "panel-New")]//tbody//td//button[contains(@class, "text-color-blue")]'
# Add new patient
ANP_CLINICINFO = 'xpath:(//div[@class="add-new-patients-wrapper"]//div[@class="ant-select-selector"])[1]'
ANP_CLINICINFO_OPTIONS = 'xpath:(//div[@class="add-new-patients-wrapper"]//div[@class="rc-virtual-list-holder"])[1]//div[@class="ant-select-item-option-content"]'
ANP_INPUTTYPES = 'xpath://div[@class="add-new-patients-information"]//div[contains(@class, "ant-radio-group-solid")]/label'
ANP_TEMPLATE = 'xpath:(//div[@class="add-new-patient-information"]//div[contains(@class, "ant-select ant-select-single")])[1]'
ANP_TEMPLATE_OPTIONS = 'xpath://div[@class="add-new-patient-information"]//div[contains(@class, "ant-select-dropdown") and not(contains(@class, "ant-select-dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
ANP_EMAIL = 'xpath://div[@class="add-new-patient-information"]//input[@placeholder="Enter patient\'s email"]'
ANP_FNAME = 'xpath://div[@class="add-new-patient-information"]//input[@placeholder="Enter patient\'s first name"]'
ANP_LNAME = 'xpath://div[@class="add-new-patient-information"]//input[@placeholder="Enter patient\'s last name"]'
ANP_DOB = 'xpath://div[@class="add-new-patient-information"]//input[@placeholder="Select patient\'s date of birth"]'
ANP_DOB_TODAY = 'xpath://div[@class="add-new-patient-information"]//div[contains(@class, "ant-picker-dropdown") and not(contains(@class, "hidden"))]//a[@class="ant-picker-today-btn"]'
ANP_GENDER = 'xpath:(//div[@class="add-new-patient-information"]//div[@class="ant-select-selector"])[2]'
ANP_GENDER_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
ANP_PHONENUMBER = 'xpath://div[@class="add-new-patient-information"]//input[@name="phoneNumber"]'
ANP_COUNTRY = 'xpath:(//div[@class="add-new-patient-information"]//div[@class="ant-select-selector"])[3]'
ANP_COUNTRY_OPTIONS = 'xpath://div[@class="add-new-patient-information"]//div[contains(@class, "ant-select-dropdown") and not(contains(@class, "ant-select-dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
ANP_ADDRESS = 'xpath://input[@name="address"]/..//div//input[contains(@id, "react-select")]'
ANP_ADDRESS_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
ANP_CITY = 'xpath://div[@class="add-new-patient-information"]//input[@placeholder="Enter patient\'s city"]'
ANP_STATEV1 = 'xpath://div[@class="add-new-patient-information"]//input[@placeholder="Enter patient\'s state"]'
ANP_STATEV2 = 'xpath:(//div[@class="add-new-patient-information"]//div[@class="ant-select-selector"])[4]'
ANP_STATEV2_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@option and @aria-selected]/div'
ANP_ZIPCODE = 'xpath://div[@class="add-new-patient-information"]//input[@placeholder="Enter zip code"]'
ANP_HEIGHT_AF = 'xpath://span[text()="ft"]/../../input'
ANP_HEIGHT_XF = 'xpath://span[text()="in"]/../../input'
ANP_WEIGHT = 'xpath://span[text()="lb"]/../../input'
ANP_PAYMENTTYPE = 'xpath://div[@class="add-new-patient-information"]//div[contains(@class, "ant-radio-group")]//label//input[@type="radio"]'
ANP_ADDBUTTON = 'xpath://div[@class="add-new-patient-information"]//div[@class="add-area"]//button[not(contains(@class, "ant-btn-background-ghost"))]'
ANP_INSURANCENAMEV1 = 'xpath://input[@placeholder="Enter patient\'s insurance name"]'
ANP_INSURANCENAMEV2 = 'xpath:(//div[@class="add-new-patient-information"]//div[contains(@class, "ant-select-selector")])[5]'
ANP_INSURANCENAMEV2_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[@option and @aria-selected]/div'
ANP_INSURANCEPROVINCIAL = 'xpath://input[@placeholder="Enter patient\'s provincial billing"]'
ANP_INSURANCEEXPIRIREDATE = 'xpath://input[@placeholder="Select patient\'s insurance expire date"]'
ANP_INSURANCEEXPIRIREDATE_TODAY = 'xpath://div[@class="add-new-patient-information"]//div[contains(@class, "ant-picker-dropdown") and not(contains(@class, "hidden"))]//a[@class="ant-picker-today-btn"]'
ANP_IMPORTPLIST = 'xpath://div[@class="add-new-patients-wrapper"]//span[@aria-label="file-excel"]/..'
# Import patient list dialog
APL_TEMPLATE = 'xpath://div[contains(@class, "import-patients-modal")]//div[@class="ant-select-selector"]//input'
APL_TEMPLATE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "item-option")]'
APL_IMPORTAREA = 'xpath://div[contains(@class, "import-patients-modal")]//div[@class="upload-file-new"]/..//input[@type="file"]'
APL_CONFIRMIMPORT = 'xpath://div[contains(@class, "import-patients-modal")]//button[contains(@class, "ant-btn-primary")]'
APL_ADDPATIENTS = 'xpath://div[@class="add-new-patient-body"]//button[contains(@class, "add-patients-btn")]'
APL_DATA_HEADER = 'xpath://div[@class="add-new-patients-wrapper"]//thead//th[@class="ant-table-cell" and string-length(text()) > 0]'
APL_DATA_CONTENT = 'xpath://div[@class="add-new-patients-wrapper"]//tbody//div[contains(@class, "normal-cell-wrapper") and not(contains(@class, "flex-end"))]/..'
