SEARCHBY = 'xpath://div[@class="patients-inactive-wrapper"]//*[contains(@class, "search-filter-btn")]'
SEARCHBY_OPTIONS = 'xpath://div[@class="search-menu-title"]/..//li[@data-menu-id]'
TEXTSEARCH = 'xpath://div[@class="patients-inactive-wrapper"]//input[contains(@placeholder, "Search by")]'
BYPATIENT = 'xpath://div[@class="patients-inactive-wrapper"]//div[@class="select-ct-wrapper"]'
BYPATIENT_OPTIONS = 'xpath://div[@class="patients-inactive-wrapper"]//div[@class="ant-select-item-option-content"]'
DATA_HEADER = 'xpath://div[@class="patients-inactive-wrapper"]//th[@class="ant-table-cell"]'
DATA_CONTENT = 'xpath://div[@class="patients-inactive-wrapper"]//tr[@data-row-key]//td[@class="ant-table-cell"]'
DATA_CONTENT_ROW = 'xpath://div[@class="patients-inactive-wrapper"]//tbody/tr[@data-row-key]'
DATA_CONTENT_PATIENTNAME = 'xpath://div[@class="patients-inactive-wrapper"]//tbody/tr[@data-row-key]//button[contains(@class, "text-color-blue")]'
