# Manage template
MT_CREATENEWTEMPLATE1 = 'xpath://div[@class="create-new-template-wapper"]//button[contains(@class, "create-btn")]'
MT_CREATENEWTEMPLATE2 = 'xpath://div[@class="empty-space"]//button[contains(@class, "ant-btn-primary")]'  # displayed if there is no existing template
MT_TEMPLATE_MENUS = 'xpath://div[@class="create-new-template-body"]//div[contains(@class, "body-left")]//button[contains(@class, "facility-btn")]'
MT_TEMPLATE_SUBMENUS = 'xpath:.//div[@class="template-facility-btn-list"]/button'
MT_DATA_TEMPLATEHEADER = 'xpath://div[@class="create-new-template-body-right"]//div[contains(@class, "left-item")]'
MT_DATA_TEMPLATECONTENT = 'xpath://div[@class="create-new-template-body-right"]//div[contains(@class, "right-item")]'
MT_EDIT = 'xpath://div[@class="create-new-template-body-right"]//span[@aria-label="edit"]/..'
MT_DUPLICATE = 'xpath://div[@class="create-new-template-body-right"]//span[@aria-label="copy"]/..'
MT_DELETE = 'xpath://div[@class="create-new-template-body-right"]//span[@aria-label="delete"]/..'
# Create new template
NT_FACILITY_OPTIONS = 'xpath://div[@class="ant-modal-wrap" and @role="dialog" and not(contains(@style, "display"))]//div[@class="multiple-checkbox-value"]/label'
NT_FACILITY_CHECKBOXOPTIONS = 'xpath://div[@class="ant-modal-wrap" and @role="dialog" and not(contains(@style, "display"))]//input[@class="ant-checkbox-input"]'
NT_CREATETEMPLATE = 'xpath://div[@class="ant-modal-wrap" and @role="dialog" and not(contains(@style, "display"))]//button[contains(@class, "ant-btn-primary")]'
NT_TEMPLATETITLE = 'xpath://div[@class="create-new-patient-body"]//input[@placeholder="Enter template title"]'
NT_CURRENTSYMPTOMS = 'xpath:(//div[@class="create-new-patient-body"]//div[@class="ant-select-selector"])[1]//div[@class="ant-select-selection-search"]'
NT_CURRENTSYMPTOMS_OPTIONS = 'xpath://div[@class="create-new-patient-body"]//div[contains(@class, "ant-select-item-option") and @aria-selected]'
NT_PASTMEDICAL = 'xpath:(//div[@class="create-new-patient-body"]//div[contains(@class, "custom-select-input")])[1]/div[contains(@class, "container")]//input'
NT_PASTMEDICAL_OPTIONS = 'xpath:(//div[@class="medical-history-select"])[2]//div[contains(@class, "menu")]//div[@id]'
NT_ADDMEDI_NAME = 'xpath://div[@class="add-medication-wrapper"]//div[@class="custom-select-input"]//input'
NT_ADDMEDI_NAME_OPTIONS = 'xpath://div[@class="add-medication-wrapper"]//div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
NT_ADDMEDI_QUANTITY = 'name:quantity'
NT_ADDMEDI_UNIT = 'xpath:(//div[@class="add-medication-wrapper"]//span[@class="ant-select-selection-search"])[1]//input'
NT_ADDMEDI_UNIT_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[contains(@class, "ant-select-item-option")]'
NT_ADDMEDI_FREQUENCY = 'xpath:(//div[@class="add-medication-wrapper"]//span[@class="ant-select-selection-search"])[2]//input'
NT_ADDMEDI_FREQUENCY_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[contains(@class, "ant-select-item-option") and @aria-selected]'
NT_ADDMEDI_TIMETOTAKE = 'xpath://div[@class="add-medication-wrapper"]//div[@class="time-to-take-main"]//input'
NT_ADDMEDI_NOTE = 'xpath://div[@class="add-medication-wrapper"]//textarea[@placeholder="Enter note"]'
NT_ADDMEDI_PRESCRIBEDATE = 'xpath://div[@class="add-medication-wrapper"]//input[@placeholder="Enter prescribed date"]'
NT_ADDMEDI_PRESCRIBEDATE_TODAY = 'xpath://div[contains(@class, "ant-picker-dropdown") and not(contains(@class, "hidden"))]//a[@class="ant-picker-today-btn"]'
NT_ADDMEDI_ADDBUTTON = 'xpath://div[@class="add-medication-wrapper"]//button[contains(@class, "add-button")]'
NT_CREATE = 'xpath://div[@class="create-new-patient-body"]//div[@class="footer-button-div"]//button[contains(@class, "ant-btn ant-btn-primary")]'
# Edit template
ET_TITLE = 'xpath://div[@class="create-new-template-wapper"]//input[@placeholder="Enter template title"]'
ET_CURRENTSYMPTOMS = 'xpath:(//div[@class="create-new-patient-body"]//div[@class="ant-select-selector"])[1]//div[@class="ant-select-selection-search"]'
ET_CURRENTSYMPTOMS_OPTIONS = 'xpath://div[@class="create-new-patient-body"]//div[contains(@class, "ant-select-item-option") and @aria-selected]'
ET_EXISTINGCURRENTSYMPTOMS = 'xpath:(//div[@class="create-new-patient-body"]//div[@class="ant-select-selector"])[1]//span[@class="ant-select-selection-item"]'
ET_PASTMEDICAL = 'xpath:(//div[@class="create-new-patient-body"]//div[contains(@class, "custom-select-input")])[1]/div[contains(@class, "container")]//input'
ET_PASTMEDICAL_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
ET_EXISTINGPASTMEDICALS = 'xpath://div[@class="create-new-patient-body"]//div[@class="medical-history-select"]//div[contains(@class, "select-ct-outside")]//div[contains(@class, "row-wrapper")]'
ET_EXISTINGMEDICATIONS = 'xpath://div[@class="medication-card-container"]//div[@class="medication-card-top"]'
ET_SAVE = 'xpath://div[@class="create-new-patient-body"]//div[@class="footer-button-div"]//button[contains(@class, "ant-btn ant-btn-primary")]'
# Duplicate dialog
DUP_DUPLECATETEMPLATE = 'xpath://div[@class="ant-modal-wrap" and @role="dialog" and not(contains(@style, "display"))]//button[contains(@class, "ant-btn-primary")]'
# Delete dialog
DEL_YES = 'xpath://div[@class="confirmation-layout-wrapper"]//button[contains(@class, "ant-btn-primary")]'
