WEB_BASE_URL: https://identity.athenahealth.com/oauth2/auset0ja9xZ2Hniep296/v1/authorize?BANNERTIME=1726867979&SHOWBANNER=TIMEDOUT&client%5Fid=0oaet0rfjNzyKCiQQ296&idp=&login%5Fhint=sladow1&nonce=c0fb83075a2850513eeffa8e298f642eae3b58c642bfaf92ea43b49792dff4c0&prompt=login&redirect%5Furi=https%3A%2F%2Fathenanet%2Eathenahealth%2Ecom%2F1%2F1%2Flogin%2Foidc%2Eesp&response%5Fmode=form%5Fpost&response%5Ftype=code&scope=openid%20profile%20offline%5Faccess%20&sessionToken=&state=eyJGTEFHUyI6eyJDT0RFUEFTU1RIUk9VR0giOm51bGwsIkFORVRNRkFTSElNV0lER0VUIjoiIiwiTk9GUkFNRVNFVCI6bnVsbCwiREVQQVJUTUVOVElEIjpudWxsLCJERUVQTElOSyI6bnVsbH0sIkxPR0lOTUVUQURBVEEiOnsiVVNFUkFVVEhOVFlQRSI6Ik5PTlNTTyIsIkJBTk5FUlRZUEUiOiJUSU1FRE9VVCJ9LCJDU1JGIjoiNDFlMjNhYmMwNmU5YzNiYzU5N2E3NjZmNzA5MmIzNmQiLCJUQVJHRVRVUkwiOm51bGx9
NEW_USERS:
    crawl_data:
        username: sladow1
        password: B!0tr1c1ty4

STUDY_ID:
    patient_id:
        patient_id_1: 7362
