WEB_BASE_URL: https://callcenter.staging.biotricity.com
USERS:
    callcenter_technician:
        username: technician01
        password: 2@2@biotricityca
    callcenter_qa:
        username: qa1
        password: 2@2@biotricityca
    callcenter_qalead:
        username: leader1
        password: 3#Monitoring3#
    callcenter_supervisor:
        username: super1
        password: 3#Monitoring3#

NEW_USERS:
    callcenter_technician:
        username: cct_qa_01
        password: 3#Monitoring3#
    callcenter_qa:
        username: ccqa_qa_01
        password: 3#Monitoring3#
    callcenter_qaleader:
        username: ccqal_qa_01
        password: 3#Monitoring3#
    callcenter_supervisor:
        username: super3
        password: 3#Monitoring3#
    callcenter_airp:
          username: super2
          password: 3#Monitoring3#
    callcenter_airp_pdf:
      username: ccqa_qa_02
      password: 3#Monitoring3#
#    callcenter_airp:
#        username: qafetest
#        password: 3#Monitoring3#

STUDY_ID:
    study_id_completed:
        study_id_airp: '13605'
        study_id_strips_ventricular: '17874'
        study_id_strips_management: '17415'
        study_id_strips_management_2: '17416'
        study_id_strips_supraventricular: '17873'
        study_id_pdf_report: '17956'

#clinic
WEB_BASE_URL_CLINIC: https://diagnostics.staging.biotricity.com
NEW_USER_CLINIC:
    clinic_physician:
        - name: Physician Qa Team 01
          username: physician_qa_team_01
          password: Welcomeqa1#
        - name: Physician Qa Team 02
          username: physician_qa_team_02
          password: Welcomeqa1#
          userID: 635a0afc14ba33394f6504e1
    clinic_technician:
        - name: Technician Qa Team 01
          username: nurse_qa_team_01
          password: Welcomeqa1#
        - name: Technician Qa Team 02
          username: nurse_qa_team_02
          password: Welcomeqa1#
