*** Settings ***
Documentation   Test Suite - Billing Portal - Authentication
Metadata    sid     BLP-BIOCARE-AUTH
Metadata    owner   Trinh Nguyen
Library     corelib/AssertionExtension.py
Library     corelib/WebHandler.py   ${BROWSER}   ${HEADLESS}
Library     project_billing_portal/lib/ConfigHandler.py     ${ENV}
#Library     project_billing_portal/lib/web/Common.py

Suite Setup     SUITE SETUP
Suite Teardown  SUITE TEARDOWN
Force Tags      BLP-BIOCARE-AUTH    web
Test Timeout    1h

*** Test Cases ***
BLP-BIOCARE-AUTH-SIGNIN-01: Cannot Sign in to Biocare portal if the username or password or both are invalid
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. The following error message will be displayed: “Invalid username or password"
    ...     2. The user will still stay on the Login screen

    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-01     manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-02: Cannot Sign in to Biocare portal if the account was deactivated and the assigned facility is active
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. The following error message will be displayed: “Invalid username or password"
    ...     2. The user will still stay on the Login screen

    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-02      manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-03: Cannot Sign in to Biocare portal if the account was deactivated and the assigned facility is closed
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. The following error message will be displayed: “Invalid username or password"
    ...     2. The user will still stay on the Login screen

    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-03      manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-04: Can Sign in to Biocare portal with new the password has just been reset by Admin
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. A page requesting a password change will be displayed
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-04     manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-05: Can Sign in to Biocare portal with the old account without setting new password
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. A page requesting a password change will be displayed

    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-05      manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-06: Can Sign in to Biocare portal with the old account has been set new password
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. A page requesting a password change will be displayed
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-06     manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-07: Can Sign in to Biocare portal with the new account has just been created by Admin user
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. A page requesting a password change will be displayed
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-07     manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-08: Can Sign in to Biocare portal with an account has activate status (haven't set a new password) and facility status is closed
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     1. There is an account that having active status and facility is closed
    ...     2. This account haven't set a new password yet
    ...
    ...
    ...     Test Steps:
    ...     1. Enter username and password
    ...     2. Click Sign in button
    ...     3. Click Set up new password screen, then fill all required fields
    ...
    ...     Expected Results:
    ...     1. Rediect user to Set up new pass word screen
    ...     2. After Setting up new password button success, user shall redirect to "Your clinic was closed!" page
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-08     manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNIN-09: Can Sign in to Biocare portal with an account has activate status (has been set up new password) and facility status is closed
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     1. There is an account that having activate status and facility is closed
    ...     2. This account has been set a new password yet
    ...
    ...
    ...     Test Steps:
    ...     1. Enter username and password
    ...     2. Click Sign in button
    ...
    ...     Expected Results:
    ...     1. After clicking the Set up new password button, user shall redirect to "Your clinic was closed!" page
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNIN-09     manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-01: Verify email for new account created from Admin
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     New account is created
    ...
    ...     Test Steps:
    ...     1. Login to the Biocare portal
    ...     2. Click "Verify Email" button
    ...     3. Enter a valid and unique email (not yet verified on another users) and click "Next" button
    ...     4. Enter the received verfication code and complete proceed
    ...
    ...     Expected Results:
    ...     1. Display modal to verify email, the user can verify email or skip this feature until 30days from the account creation date
    ...     2. Display "Verify your email" screen
    ...     3. A verification code shall be sent to mailbox (will expire after 24 hours)
    ...     4. After successful email verification, the new email will be updated in the user's info
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-01     manual    CP-2.23.0   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-02: Verify email for old account after 30 days not yet verified since the release of this feature
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     There is an old account that not yet verified since the release of this feature (Release date: Delta 01/23, Staging 01/26, Prod 02/05)
    ...
    ...     Test Steps:
    ...     1. Login to the Biocare portal
    ...     2. Click "Verify Email" button
    ...     3. Enter a valid and unique email (not yet verified on another users) and click "Next" button
    ...     4. Enter the received verfication code and complete proceed
    ...
    ...     Expected Results:
    ...     1. Display modal to verify email with no option to skip the pop-up
    ...     2. Display "Verify your email" screen
    ...     3. A verification code shall be sent to mailbox (will expire after 24 hours)
    ...     4. After successful email verification, the new email will be updated in the user's info
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-02     manual     CP-2.23.0   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-03: Enter invalid verification code
    [Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     The user is on "Verify your email" screen and has a verification code sent to user
    ...
    ...     Test Steps:
    ...     1. Enter invalid verification code, then click "Verify" button
    ...
    ...     Expected Results:
    ...     1. Display an error message "Invalid or expired verification code"
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-03     manual     CP-2.23.0   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-04: Enter the expired verification code
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     The user is on "Verify your email" screen and has a verification code sent to user exceed 24 hours
    ...
    ...     Test Steps:
    ...     1. Enter verification code mentioned in Precondition, then click "Verify" button
    ...
    ...     Expected Results:
    ...     1. Display an error message "Invalid or expired verification code"
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-04     manual     CP-2.23.0   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-05: Resend verification code
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     The user is on step "Enter verification code" of "Verify your email" screen
    ...
    ...     Test Steps:
    ...     1. Enter a valid email  >> Click "Verify"
    ...     2. Click "Didn’t get an verification code?" button
    ...     3. Wait for more than 2 minutes >> Click "Resend code"
    ...     4. Click "Resend code" continously
    ...
    ...     Expected Results:
    ...     1. Step 3 - The code is resent to user
    ...     2. Step 4 - Display an error message "Please wait for 2 minutes to perform the resend code"
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-05     manual     CP-2.23.0   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-06: Change email while Verify email proceed
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     The user is on step "Enter verification code" of "Verify your email" screen
    ...
    ...     Test Steps:
    ...     1. Enter a valid email  >> Click "Verify"
    ...     2. Click "Didn’t get an verification code?" button
    ...     3. Wait for more than 2 minutes >> Click "Change email" >> Enter valid email and go through a similar process BLP-BIOCARE-AUTH-VERIFY-EMAIL-01
    ...
    ...     Expected Results:
    ...     1. After successful email verification, the new email will be updated in the user's info
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-06     manual     CP-2.23.0   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-07: Cannot verify email if the email used on another user
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     There is an email adrress that has been verified and used on another user
    ...     The user is on step "Enter email" of "Verify your email" screen
    ...
    ...     Test Steps:
    ...     1. Enter the email mentioned in Precondition  >> Click "Next"
    ...
    ...     Expected Results:
    ...     1. Display an error message "Email is already in use"
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-07     manual     CP-2.23.0   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-08: Cannot verify email if invalid email
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     The user is on step "Enter email" of "Verify your email" screen
    ...
    ...     Test Steps:
    ...     1. Enter invalid email format  >> Click "Next "
    ...
    ...     Expected Results:
    ...     1. Display an error message "Invalid email"
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-08     manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-09: Cannot verify email without entering email address on Email field
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...     The user is on step "Enter email" of "Verify your email" screen
    ...
    ...     Test Steps:
    ...     1. Let empty the email address  >> Click "Next "
    ...
    ...     Expected Results:
    ...     1. Display an error message "Invalid email"
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-09     manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-10: Can skip the verify email process by clicking the Later button
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1. Let empty the email address  >> Click "Next "
    ...
    ...     Expected Results:
    ...     1. Display an error message "Invalid email"
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-10     manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-11: Verify the Verify email modal is displayed after reloading the portal
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-11     manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-VERIFY-EMAIL-12: Verify the verification code in the email will expired after 24 hours
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]      BLP-BIOCARE-AUTH-VERIFY-EMAIL-12     manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNOUT-01: Sign out from the Biocare portal
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1. The user shall be signed out of the Biocare Portal and redirected to the Login screen
    ...     2. Users will be logged out from all portals on the browser after logging out successfully!
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNOUT-01     manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNOUT-02: Automatically Sign out from the Biocare portal after Admin reset password
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1. If the password has just been reset by Admin, user accounts will be logged out and redirected to the login screen
    ...     2. Users will be logged out from all portals on the browser after logging out successfully!
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNOUT-02     manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-SIGNOUT-03: Sign out from the Billing portal
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1. The user shall be signed out of the Billing Portal and redirected to the Login screen
    ...     2. Users will be logged out from all portals on the browser after logging out successfully!
    ...
    [Tags]      BLP-BIOCARE-AUTH-SIGNOUT-03     manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-01: Verify user can go to the Reset your password page by clicking Forgot your password button
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-01    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-02: Can reset password if username is valid and the associated account has a verified email
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-02    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-03: Can back to Sign In page by clicking the Back to Sign in button on Reset your password screen
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-03    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-04: Check case the link in the email will expire after 1 hour
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-04    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-05: Check case except for the user who takes action to change their password, there shall be a alert displayed
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-05    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-06: Check case the user does not reset their password on this page within 15 minutes
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-06    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-07: Check case the password entered has less than 8 characters
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-07    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-08: Check case the password entered includes a blank space
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-08    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-09: Check case the confirmation of the new password does not match with the new password entered
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-09    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-10: Check case the user enters incomplete information
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-10    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-11: Check case the user enters the password contain the username
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-11    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-12: Cannot reset password without entering username
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-12    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-13: Cannot reset password if username is valid but the associated account has not verified the email
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-13    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-14: Cannot reset password if username is valid but the associated account has no the email
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-14    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-FORGOT-PW-15: Cannot reset password if username is invalid
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    ...
    [Tags]      BLP-BIOCARE-AUTH-FORGOT-PW-15    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-01: Information on the Set up new password screen
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. New password
    ...     2. Confirm new password
    ...     3. There shall also be Password rules letting the user know what is required to create a valid password:
    ...     "A password must be at least 8 characters, must not contain the username and should be a mixture of uppercase and lowercase letters, numbers, and symbols."
    ...     5. There is a "eye" icon on each password field
    ...     6. A warning message: “You will be logged out from all sessions after changing password successfully!”
    ...     7. There are 2 butons: Set Up New Password, Back to Sign In
    ...

    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-01   manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-02: Change password unsuccessfully if the new password entered has less than 8 characters
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display an error message: “Password must have at least 8 characters.”
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-02   manual   CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-03: Change password unsuccessfully if the password entered includes a blank space
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display an error message: “Password cannot include blank spaces.”
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-03    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-04: Change password unsuccessfully if the confirmation of the new password does not match with the new password entered
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display an error message: “The confirm password does not match.”
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-04    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-05: Change password unsuccessfully if the user enters incomplete information
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display an error message: “Please complete all information”
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-05    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-06: Change password unsuccessfully if the user does not reset their password on this page within 15 minutes
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display a toast message: “Password reset time has expired. Please log in again.” if the user does not
    ...     reset their password on this page within 15 minutes. After 3 seconds , user accounts will be logged out
    ...     and redirected to the login screen
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-06    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-07: Change password unsuccessfully if the password contain the username
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display an error message: “The password must not contain the username.”
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-07    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-08: Change password successfully if the confirmation of the new password match with the new password entered
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display a toast message: “Your password has been updated successfully.”.
    ...     2. Except for the user who takes action to change their password, there shall be a alert displayed:
    ...     Content: You have changed your password before.
    ...     3. The clinic user will be redirected to the Biocare Portal home page if the new password setup is successful
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-08    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-09: Change password successfully if the new password match the password rules
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1. Display a toast message: “Your password has been updated successfully.”.
    ...     2. Except for the user who takes action to change their password, there shall be a alert displayed:
    ...     Content: You have changed your password before.
    ...     3. The clinic user will be redirected to the Biocare Portal home page if the new password setup is successful
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-09    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-10: Check except for the user who takes action to change their password, there shall be a alert displayed
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...     Test Steps:
    ...
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-10    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-RESET-PW-11: Cancel setting new password
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1. Click the Back To Sign In button
    ...
    ...     Expected Results:
    ...     1. When users click Back To Sign In button, password will not change and the screen will return to the Biocare portal login page
    ...
    [Tags]      BLP-BIOCARE-AUTH-RESET-PW-11    manual  CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-LINKS-01: Privacy Policy content is displayed when clicking "Privacy Policy" button at the bottom page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description: Privacy Policy content is displayed when clicking "Privacy Policy" button at the bottom page
    ...
    ...     Precondition: The user is on the Biocare portal login page
    ...
    ...     Test Steps:
    ...     1. Click "Privacy Policy" button located at the bottom page
    ...
    ...     Expected Results:
    ...     1. Modal will be displayed with the content of the Privacy Policy
    ...     2. The content must match the content in https://itrvn.sharepoint.com/:w:/s/BiofluxPortal/EcOnc_fzevJClFWo2m_Iem0BRX_Z-Ef8oyinftqPTqJSTw?e=GL5XOB&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA2MDQwMTE2MSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D
    ...     3. The modal has [Close] button

    [Tags]      BLP-BIOCARE-AUTH-LINKS-01    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-LINKS-02: Terms of Use content is displayed when clicking "Terms of Use" button at the bottom page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description: Terms of Use content is displayed when clicking "Terms of Use" button at the bottom page
    ...
    ...     Precondition: The user is on the Biocare portal login page
    ...
    ...     Test Steps:
    ...     1. Click "Terms of Use" button located at the bottom page
    ...
    ...     Expected Results:
    ...     1. Modal will be displayed with the content of the Terms of Use
    ...     2. The content must match the content in https://itrvn.sharepoint.com/:w:/s/BiofluxPortal/EWhgPBjsH1BPlOW5_fNZFrEBvih0jh_xhNji_8ZsyOT2cw?e=6ZSChM&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA2MDQwMTE2MSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D
    ...     3. The modal has [Close] button

    [Tags]      BLP-BIOCARE-AUTH-LINKS-02    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BLP-BIOCARE-AUTH-LINKS-03: Contact Support content is displayed when clicking "Contact Support" button at the bottom page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description: Contact Support content is displayed when clicking "Contact Support" button at the bottom page
    ...
    ...     Precondition: The user is on the Biocare portal login page
    ...
    ...     Test Steps:
    ...     1. Click "Contact Support" button located at the bottom page
    ...
    ...     Expected Results:
    ...     1. Modal will be displayed with the contact support information
    ...     2. The content must match the content in
    ...     3. The modal has [Got It] button, when clicking this button the modal will be exited

    [Tags]      BLP-BIOCARE-AUTH-LINKS-03    manual     CP-2.23.0
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

*** Keywords ***
SUITE SETUP
    ${BROWSER_NODE}      Start Browser
    Import Library       project_billing_portal/lib/web/Common.py      ${BROWSER_NODE}      ${ENV}
    ${VERSION}           Navigate To Sign In Page
    Set Suite Metadata    browser       ${BROWSER.capitalize()}
    Set Suite Metadata    version       ${VERSION}

SUITE TEARDOWN
    Quit Browser
