# Create facility page 1 | Facility info
CFI_NAME = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="facilityName"]'
CFI_SHORTNAME = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="shortName"]'
CFI_COUNTRY = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[1]'
CFI_COUNTRY_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CFI_ADDRESS = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "auto-complete__control")])[1]//input'
CFI_ADDRESS_OPTIONS = 'xpath://div[contains(@class, "auto-complete__menu-list")]//div[contains(@class, "auto-complete__option") and @id]'
CFI_STATE = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[2]'
CFI_STATE_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CFI_CITY = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "auto-complete__control")])[2]//input'
CFI_CITY_OPTIONS = 'xpath://div[contains(@class, "auto-complete__menu-list")]//div[contains(@class, "auto-complete__option") and @id]'
CFI_ZIPCODE = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="zipCode"]'
CFI_PHONENUMBER = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="phoneNumber"]'
CFI_FAX = 'xpath://div[contains(@class, "new-facility-form")]//div[contains(@class, "custom-multi-email")]'
CFI_ADDCLINICCONTACT = 'xpath://div[contains(@class, "new-facility-form")]//button[contains(@class, "add-clinician-contact-button")]'
CFI_FACILITYNOTE = 'xpath://div[contains(@class, "new-facility-form")]//textarea[@name="facilityNote"]'
CFI_NEXT = 'xpath://div[contains(@class, "new-facility-form")]//button[contains(@class, "normal-btn")]'
CFI_NEXTLOADING = 'xpath://div[contains(@class, "new-facility-form")]//button[contains(@class, "normal-btn") and (@disabled)]'
# > Clinic support contact
ACS_NAME = 'xpath://div[contains(@class, "add-edit-clinician-modal")]//input[@name="name"]'
ACS_PHONENUMBER = 'xpath://div[contains(@class, "add-edit-clinician-modal")]//input[@name="phone"]'
ACS_EMAIL = 'xpath://div[contains(@class, "add-edit-clinician-modal")]//input[@name="email"]'
ACS_DESCRIPTION = 'xpath://div[contains(@class, "add-edit-clinician-modal")]//textarea[@name="description"]'
ACS_ADDCONTACT = 'xpath://div[contains(@class, "add-edit-clinician-modal")]//button[contains(@class, "save-btn")]'
# Create facility page 2 | Facility setting
CFS_SERVICETYPE = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[1]'
CFS_SERVICETYPE_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CFS_FACILITYSTATUS = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[2]'
CFS_FACILITYSTATUS_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CFS_NOTIFICATIONEMAIL = 'xpath://div[contains(@class, "new-facility-form")]//div[contains(@class, "custom-multi-email")]//input'
CFS_FACILITYGROUP = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "custom-select-input")])[3]/div'
CFS_FACILITYGROUP_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
CFS_REPORTFAXING = 'xpath://div[contains(@class, "new-facility-form")]//label[contains(@for, "custom-checkbox-input")]'
CFS_EVALSTARTDAY = 'xpath://div[contains(@class, "new-facility-form")]//input[@placeholder="Start date"]'
CFS_EVALENDDAY = 'xpath://div[contains(@class, "new-facility-form")]//input[@placeholder="End date"]'
CFS_OTHERCONFIGS = 'xpath://div[contains(@class, "new-facility-form")]//label[contains(@for, "custom-toggle-input")]'
CFS_NEXT = 'xpath://div[contains(@class, "new-facility-form")]//button[contains(@class, "normal-btn")]'
# Create facility page 3 | Account payable
CAP_NAME = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="name"]'
CAP_EMAIL = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="email"]'
CAP_COUNTRY = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[1]'
CAP_COUNTRY_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CAP_ADDRESS = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "async-select-custom")])[1]//input'
CAP_ADDRESS_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
CAP_STATE = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[2]'
CAP_STATE_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CAP_CITY = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "async-select-custom")])[1]//input'
CAP_CITY_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
CAP_ZIPCODE = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="zipCode"]'
CAP_PHONENUMBER = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="phoneNumber"]'
CAP_FINANCIALHOLD = 'xpath://div[contains(@class, "new-facility-form")]//div[contains(@class, "custom-radio-input")]//label'
CAP_FAX = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="faxNumber"]'
CAP_NEXT = 'xpath://div[contains(@class, "new-facility-form")]//button[contains(@class, "normal-btn")]'
# Create facility page 4 | Notification protocol
CNP_CREATE = 'xpath://div[contains(@class, "new-facility-form")]//button[contains(@class, "normal-btn")]'
# Create facility page 5 | Device Settings
CDS_STUDYDURATION = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="studyDuration"]'
CDS_PREEVENTTIME = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[1]'
CDS_PREEVENTTIME_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CDS_POSTEVENTTIME = 'xpath:(//div[contains(@class, "new-facility-form")]//div[contains(@class, "select-input__control")])[2]'
CDS_POSTEVENTTIME_OPTIONS = 'xpath://div[contains(@class, "select-input__menu-list")]//div[contains(@class, "select-input__option") and @id]'
CDS_BRADYTHRS = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="bradyThrs"]'
CDS_TACHYTHRS = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="tachyThrs"]'
CDS_PAUSELVDURATION = 'xpath://div[contains(@class, "new-facility-form")]//input[@name="pauseLvDuration"]'
CDS_AFIBDETECTION = 'xpath://div[contains(@class, "new-facility-form")]//label[contains(@for, "afibDetection")]'
CDS_PAUSEDETECTION = 'xpath://div[contains(@class, "new-facility-form")]//label[contains(@for, "pauseDetection")]'
CDS_DIAGNOSTICLEAD = 'xpath://div[contains(@class, "new-facility-form")]//label[contains(@for, "diagnosticLead")]'
CDS_CREATE = 'xpath://div[contains(@class, "new-facility-form")]//button[contains(@class, "normal-btn")]'
# incase switch page
NEXTLOADING = 'xpath://button[@disabled and contains(@class, "normal-btn")]'