US_TABS_HEADER = 'xpath://div[contains(@class, "top-container")]//li[contains(@class, "tab-nav")]'
US_CREATENEWUSER = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//a[contains(@class, "new-normal-btn")]'
US_DATA_HEADER = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//thead//th'
US_DATA_CONTENT = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//tbody//tr[@class]/td'
US_DATA_CONTENT_ROOT = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//tbody//tr[@class]'
US_DATA_EDITICONS = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//tbody//tr[@class]//a[contains(@class, "row-action-facility")]'
# Call center
UCT_SEARCHBY = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//div[contains(@class, "search-input-box")]/button'
UCT_SEARCHBY_OPTIONS = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//div[contains(@class, "search-by-options")]//button[contains(@class, "toggle-button")]'
UCT_SEARCHBOX = 'xpath://div[contains(@class, "tab-pane") and contains(@class, "active")]//div[contains(@class, "search-input-box")]//input'
UCT_EDIT = 'xpath://div[contains(@class, "active")]//a[@class="row-action-facility-button-v2"]'
