# Common
VERSION = "class:footer-reserved"
HOME = "xpath://div[@class='App']"
SIDEBAR_MODAL = "class:ant-drawer-body"
ANT_MODAL = "class:ant-modal-body"
SUCCESS_MESSAGE = 'xpath://div[@class="ant-message-notice-content"]'
ERROR_MESSAGE = "xpath://p[contains(@class,'errorMessage')]"
CLOSE_MODAL = "xpath://div[contains(@class,'modalHeader')]//button"
CLOSE_ANT_MODAL = "class:ant-modal-close"
# Login
AUTH_USERNAME = "id:username"
AUTH_PASSWORD = "id:password"
AUTH_SIGNIN = "class:submit-btn"
AUTH_FORGOT_PASSWORD = "xpath://div[@class='forgot-password-btn']/button"
AUTH_HEADER_RIGHT = "xpath://div[@class='header-right']/div"
AUTH_SIGNOUT = "xpath://div[@class='header-right']//ul"
AUTH_ERROR_MESSAGE = "class:error-message"
AUTH_MAIN_PAGE = "class:app-container"
AUTH_SIGNIN_PAGE = "class:sign-in__layout"
# Navigate to portal _ Shortcuts
SCUT_DIAGNOSTIC = "xpath://a[@class='shortcuts-widget-item'][1]"
SCUT_DISEASE = "xpath://a[@class='shortcuts-widget-item'][2]"
# Account Information
INFO_NAME = "xpath://div[@class='user-wiger-title']/h2"
INFO_USERNAME = "xpath://div[@class='user-wiger-title']/span"
INFO_EMAIL = "xpath://div[@class='user-widget-row'][1]/div[2]"
INFO_COUNTRY = "xpath://div[@class='user-widget-row'][2]/div[2]"
INFO_ADDRESS = "xpath://div[@class='user-widget-row'][3]/div[2]"
INFO_PHONE = "xpath://div[@class='user-widget-row'][4]/div[2]"
INFO_AFTER_HOUR_PHONE = "xpath://div[@class='user-widget-row'][5]/div[2]"
INFO_FAX = "xpath://div[@class='user-widget-row'][6]/div[2]"
INFO_FACILITIES = "xpath://div[@class='facilities-widget-body']"
# Account Details
ACCSETTING = "xpath://div[@class='user-widget-dropdown']/button"
ACCSETTING_OPTIONS = "xpath://div[@class='user-widget-dropdown']/div//li"
ACCSETTING_EDIT_PROFILE = "xpath://div[@class='user-widget-dropdown']/div//li[1]"
ACCSETTING_UPDATE_EMAIL = "xpath://div[@class='user-widget-dropdown']/div//li[2]"
ACCSETTING_CHANGE_PASSWORD = "xpath://div[@class='user-widget-dropdown']/div//li[3]"
# Edit profile
EDPROFILE_FIRST_NAME = "xpath://div[contains(@class, '_profileDrawerItem')][1]/div/div/div[contains(@class, '_profileDrawerRowItem')][1]//input"
EDPROFILE_LAST_NAME = "xpath://div[contains(@class, '_profileDrawerItem')][1]/div/div/div[contains(@class, '_profileDrawerRowItem')][2]//input"
EDPROFILE_TITLE = "xpath://div[contains(@class, '_profileDrawerItem')][1]/div/div[contains(@class, '_profileDrawerRowItem')]//input"
EDPROFILE_COUNTRY = "xpath://div[contains(@class, '_profileDrawerItem')][2]//div[contains(@class,'_profileDrawerItemContent')]/div[1]//input"
EDPROFILE_COUNTRY_OPTIONS = "xpath://div[@class='ant-select-item-option-content']"
EDPROFILE_ADDRESS = "xpath://div[contains(@class, '_profileDrawerItem')][2]//div[contains(@class,'_profileDrawerItemContent')]/div[2]//input"
EDPROFILE_ADDRESS_OPTIONS = "xpath://div[@class='ant-select-item-option-content']"
EDPROFILE_CITY = "xpath://div[contains(@class, '_profileDrawerItem')][2]//div[contains(@class,'_profileDrawerItemContent')]/div[3]//input"
EDPROFILE_CITY_OPTIONS = "xpath://div[@class='ant-select-item-option-content']"
EDPROFILE_STATE = "xpath://div[contains(@class,'_profileDrawerItemContent')]/div[4]/div[1]//input"
EDPROFILE_STATE_OPTIONS = "xpath://div[@class='ant-select-item-option-content']"
EDPROFILE_STATE_REMOVE = "xpath://div[contains(@class,'_profileDrawerItemContent')]/div[4]//span[contains(@class,'close-circle')]"
EDPROFILE_ZIPCODE = "xpath://div[contains(@class,'_profileDrawerItemContent')]/div[4]/div[2]//input"
EDPROFILE_PHONE = "xpath://div[contains(@class,'phoneInputWrapper')][1]//input"
EDPROFILE_AFTER_HOUR_PHONE = "xpath://div[contains(@class,'phoneInputWrapper')][2]//input"
EDPROFILE_FAX = "xpath://div[contains(@class,'phoneInputWrapper')][3]//input"
EDPROFILE_SAVE = "xpath://div[contains(@class,'_profileDrawerFooter')]//button[2]"
# Update email
UPDMAIL_MODAL = "class:ant-modal-content"
UPDMAIL_NEW_EMAIL = "id:proposedEmail"
UPDMAIL_SAVE = "xpath://button[@form='email-update-form']"
# Change password
CHANGEPASS_CURRENT_PASSWORD = "xpath://div[contains(@class,'custom-input-wrapper')][1]//input"
CHANGEPASS_NEW_PASSWORD = "xpath://div[contains(@class,'custom-input-wrapper')][2]//input"
CHANGEPASS_CONFIRM_PASSWORD = "xpath://div[contains(@class,'custom-input-wrapper')][3]//input"
CHANGEPASS_SAVE = "xpath://button[contains(@class,'change-password-modal-button')][2]"
# Edit avatar
EDAVATAR = "class:profile-item-edit-button"
EDAVATAR_OPTIONS = "xpath://div[@class='avatar']//li"
EDAVATAR_UPLOAD_IMG = "xpath://input[@type='file']"
EDAVATAR_SAVE = "xpath://div[contains(@class, '_avatarModalBody')]/button"
