*** Settings ***
Documentation   Clinic-Inbox Test Suite
Metadata    sid     BFCN-INBOX-INTERIM
Metadata    owner   Trinh Nguyen
Library     corelib/AssertionExtension.py

Force Tags      BFCN-INBOX-INTERIM   mapp
Test Timeout    30m

*** Test Cases ***
BFCN-INBOX-INTERIM-VIEW-01: View the INTERIM reports screen
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-INTERIM-VIEW-01      manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-INTERIM-FILTER-FACILITY-01: View the name of the facility in case the user only associates with one facility
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-INTERIM-FILTER-FACILITY-01       manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-INTERIM-FILTER-FACILITY-02: Select a specific facility in case the user associates with multiples facility
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-INTERIM-FILTER-FACILITY-02       manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-INTERIM-FILTER-PRIORITY-01: Filter the report lists by priority on the Inbox page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-INTERIM-FILTER-PRIORITY-01     manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-INTERIM-SEARCH-01: Search by Patient Name attributes on the Inbox page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-INTERIM-SEARCH-01    manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-INTERIM-SEARCH-02: Search by Study ID attributes on the Inbox page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-INTERIM-SEARCH-02    manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-INTERIM-VIEW-DETAILS-01: View information of each report in the list
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-INTERIM-VIEW-DETAILS-01   manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

