
*** Settings ***
Documentation   Notification Test Suite
Metadata    sid     BFCN-NOTI
Metadata    owner   Nhan Nguyen
Library     corelib/AssertionExtension.py

Force Tags      BFCN-NOTI       mapp
Test Timeout    1h


*** Test Cases ***

BFCN-NOTI-01: CT-View notification icon on Inbox screen
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-01      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-02: CP-Not show Notification icon on Inbox screen
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-02      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}
    
BFCN-NOTI-03: CT-Check unread status (red dot) for notification when Flagged study is turned on/off
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-03      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}
    
BFCN-NOTI-04: CT-Check unread status (red dot) for notification when having Flagged studies
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-04      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}
    
BFCN-NOTI-05: CT-Check read status for notification when tapping Notification icon
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-05      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}
    
BFCN-NOTI-06: CT-Flagged studies button shall be hidden if the user works for only 1 clinic or all user's facilities have this feature disabled.
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-06      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-07: CT-Receive push notification for flagged studies
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-07      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-08: CT/CP-Receive push notification for Urgent Event/Notification reports during working hours
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-08      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-09: CT/CP-Receive push notification for Emergent Event/Notification reports regardless of the time
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-09      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-10: CT/CP-Check Update required for new version app available when opening the app
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-10      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-11: CT/CP-Check Update required for new version app available when opening the app by accessing push notification
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-11      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-12: CT-View notification of flagged study is turned on in Notification center
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-12      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-13: CT-View notification of flagged study is turned off in Notification center
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-13      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-14: CT-View notification of flagged studies having issues in Notification center
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-14      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-15: CT-View notification of flagged studies having issues in Notification center
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-15      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-NOTI-16: CT-The user is navigated to Flagged studies screen when tapping [View flagged studies] button
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-NOTI-16      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}
