
*** Settings ***
Documentation   Studies Test Suite
Metadata    sid     BFCN-STUDIES
Metadata    owner   Nhan Nguyen
Library     corelib/AssertionExtension.py

Force Tags      BFCN-STUDIES       mapp
Test Timeout    1h


*** Test Cases ***

BFCN-STUDIES-CREATE-01: Test Facility-Cannot create new functional study test (app not support)
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-01      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-02: Test Facility (Biotres Fw <1.5.0)-Can create new study Holter/Ext.Holter
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-02      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-03: Test Facility (Biotres Fw <1.5.0)-Cannot create new study MCT/MCT Peek/Cardiac/HnFO
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-03      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-04: Test Facility (Biotres Fw >=1.5.0)-Can create all study types
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-04      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-05: Active Facility-Biotres (No Auto tag + FW <1.5.0)-Can create new study with Holter/Ext.Holter study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-05      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-06: Active Facility-Biotres (No Auto tag + FW <1.5.0)-Cannot create new study with MCT/MCT Peek/Cardiac Event/HnFO study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-06      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-07: Active Facility-Biotres (No Auto tag + FW >=1.5.0)-Can create new study with Holter/Ext.Holter study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-07      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-08: Active Facility-Biotres (No Auto tag + FW >=1.5.0)-Cannot create new study with MCT/MCT Peek/Cardiac Event/HnFO study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-08      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-09: Active Facility-Biotres (Auto tag + FW <1.5.0)-Can create new study with Holter/Ext.Holter study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-09      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-10: Active Facility-Biotres (Auto tag + FW <1.5.0)-Cannot create new study with MCT/MCT Peek/Cardiac Event/HnFO study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-10      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-11: Active Facility-Biotres (Auto tag + FW >=1.5.0)-Can create new study with any study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-11      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-12: Active Facility-Biotres (Auto tag + FW >=1.5.0)-Can create new study with any study type
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-12      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-13: Active Facility-Biotres-Cannot create new study using Biodirect service
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-13      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-14: Financial Hold 90d and user works for 1 facility: Display alert after tapping Create button
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-14      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-15: Financial Hold 90d and user works for multiple facilities: Tap Next on step 2, display alert and cannot move to step 4
	[Documentation]     Author: Nhan Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
	...		Test Steps:
	...
    ...
    ...     Expected Results:
    ...

    [Tags]    BFCN-STUDIES-CREATE-15      manual
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-16: Bioflux-Create new study with a single study type (MCT/MCT Peek/Cardiac event/Holter/Ext.Holter)
    [Documentation]     Author: Nhan Nguyen
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...

    [Tags]  BFCN-STUDIES-CREATE-16     manual   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-17: Bioflux-Create new study with a Holter and FO study
    [Documentation]     Author: Nhan Nguyen
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...

    [Tags]  BFCN-STUDIES-CREATE-17     manual   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-18: Bioflux-Create new study with a single study type (MCT/MCT Peek/Cardiac event/Holter/Ext.Holter) using Biodirect service
    [Documentation]     Author: Nhan Nguyen
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...

    [Tags]  BFCN-STUDIES-CREATE-18     manual   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-STUDIES-CREATE-19: Bioflux-Create new study with a Holter and FO study using Biodirect service
    [Documentation]     Author: Nhan Nguyen
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...
    ...     Expected Results:
    ...

    [Tags]  BFCN-STUDIES-CREATE-19     manual   R1
    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}
