*** Settings ***
Documentation   Clinic-Inbox Test Suite
Metadata    sid     BFCN-INBOX-RECENT
Metadata    owner   Trinh Nguyen
Library     corelib/AssertionExtension.py

Force Tags      BFCN-INBOX-RECENT   mapp
Test Timeout    30m

*** Test Cases ***
BFCN-INBOX-RECENT-VIEW-01: View the list of new report sent by the call center in Recent screen
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-RECENT-VIEW-01      manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

#BFCN-INBOX-RECENT-FILTER-FACILITY-01: View the name of the facility in case the user only associates with one facility
#    [Documentation]     Author: Trinh Nguyen
#    ...
#    ...     Description:
#    ...
#    ...     Precondition:
#    ...
#    ...
#    ...     Test Steps:
#    ...     1.
#    ...
#    ...     Expected Results:
#    ...     1.
#    ...
#    [Tags]  BFCN-INBOX-RECENT-FILTER-FACILITY-01       manual
#    Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-RECENT-FILTER-FACILITY-02: Select a specific facility in case the user associates with multiples facility
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-RECENT-FILTER-FACILITY-02       manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

#BFCN-INBOX-RECENT-FILTER-PRIORITY-01: Filter the report lists by priority on the Inbox page
#    [Documentation]     Author: Trinh Nguyen
#    ...
#    ...     Description:
#    ...
#    ...     Precondition:
#    ...
#    ...
#    ...     Test Steps:
#    ...     1.
#    ...
#    ...     Expected Results:
#    ...     1.
#    ...
#    [Tags]  BFCN-INBOX-RECENT-FILTER-PRIORITY-01     manual
#     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-RECENT-SEARCH-01: Search by Patient Name attributes on the Inbox page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-RECENT-SEARCH-01    manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-RECENT-SEARCH-02: Search by Study ID attributes on the Inbox page
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-RECENT-SEARCH-02    manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

BFCN-INBOX-RECENT-VIEW-DETAILS-01: View information of each report in the list
    [Documentation]     Author: Trinh Nguyen
    ...
    ...     Description:
    ...
    ...     Precondition:
    ...
    ...
    ...     Test Steps:
    ...     1.
    ...
    ...     Expected Results:
    ...     1.
    ...
    [Tags]  BFCN-INBOX-RECENT-VIEW-DETAILS-01   manual
     Manual Should Be Passed     ${TEST_NAME}    ${TEST_DOCUMENTATION}

