from project_cardiac_portal.config.web_locators.common import CONFIRM_MSG

PAGEHEADER = 'xpath://span[@class="custom-title"]'
# Login page
USERNAME = 'name:username'
PASSWORD = 'name:password'
SIGNIN = 'xpath://button[contains(@class, "sign-in-btn")]'
SIGNIN_ERROR_MSG = 'xpath://div[contains(@class, "__error-message")]'
AVATAR = 'id:avatar'
SIGNOUT = 'xpath://div[contains(@class, "sign-out-container")]//button[.//div[text()="Sign out"]]'
CHANGEPW= 'xpath://div[contains(@class, "sign-out-container")]//button[.//div[text()="Change your password"]]'
OLDPASSWORD = 'name:oldPassword'
NEWPASSWORD = 'name:newPassword'
CONFIRMPASSWORD = 'name:confirmPassword'
CHANGEPWHEADER= 'xpath://span[text()="Change your password"]'
CHANGEPASSWORD= 'xpath://button[contains(@class, "filled-btn") and .//span[text()="Change password"]]'

OLDPASSWORD_ERROR_MSG='xpath://div[@id="text-input-wrapper-oldPassword"]//div[@class="custom-text-input__error-message"]'
NEWPASSWORD_ERROR_MSG='xpath://div[@id="text-input-wrapper-newPassword"]//div[@class="custom-text-input__error-message"]'
CONFIRMPASSWORD_ERROR_MSG='xpath://div[@id="text-input-wrapper-confirmPassword"]//div[@class="custom-text-input__error-message"]'
CLOSE_CHANGEPW='xpath://button[@class="icon-btn --filled"]'

FOOTER = 'class:login-container__footer'
ELEMENT_BACK = 'xpath://img[@alt="Back icon"]/..'
CLOSEBTN = 'xpath://img[@alt="Close icon"]'
# Menu
MENU = 'class:sidebar-tab-content'
# Left side : Study information
STUDYINFO_CONTENT_ROOT = 'xpath://div[contains(@class, "drawer-open")]//div[@class="drawer-body"]'
STUDYINFO_HEADER = 'xpath://div[contains(@class, "drawer-open")]//div[@class="drawer-header"]'
STUDYINFO_CONTENT_HEADER = 'xpath:.//div[@class="drawer-item"]/span[1]'
STUDYINFO_CONTENT_CONTENT = 'xpath:.//div[@class="drawer-item"]//div[contains(@class, "items-center")]'
STUDYINFO_CONTENT_CONTENT_RMATAG = 'xpath://div[starts-with(@class, "eol-label")]'
STUDYINFO_CONTENT_ARTIFACTTAG = 'xpath://div[contains(@class, "ant-drawer-open")]//div[contains(@class, "--need-attention")]'
STUDYINFO_CONTENT_CONTENT_FOLLOWONTAG = 'xpath://div[@class="follow-on-study-label"]'
STUDYINFO_CONTENT_POTENTIALLY = 'xpath://div[contains(@class,"total-artifact-percentage")]//div[@class="label"]'
STUDYINFO_CONTENT_ARTIFACTPERCEN = 'xpath://div[contains(@class, "total-artifact-percentage")]'
STUDYINFO_CONTENT_NOTES = 'xpath:.//div[@class="notes"]'
STUDYINFO_CLOSE = 'xpath://div[contains(@class, "drawer-open")]//img[@alt="Close icon"]/..'
STUDYINFO_ZIPFILE = 'xpath://div[contains(@class, "drawer-open")]//img[@alt="Download zip file icon"]/..'
STUDYINFO_GOTOSTUDYMANAGE = 'xpath://div[contains(@class, "drawer-open")]//button[contains(@class, "link-normal-button")]'
# Left side : Patient details
PTDET_CONTENT_ROOT = 'xpath://div[contains(@class, "drawer-open")]//div[@id="drawer-body-container"]//div[contains(@class, "drawer-body")]'
PTDET_CLOSEICON = 'xpath://div[contains(@class, "drawer-open")]//button[starts-with(@class, "icon-btn")]'
# Left side : device info
DEVICEINFO_CONTENT_ROOT = 'xpath://div[contains(@class, "drawer-open")]//div[@class="drawer-body"]'
DEVICEINFO_CLOSE = 'xpath://div[contains(@class, "drawer-open")]//img[@alt="Close icon"]/..'
# Device Infor
DEVICE_INFO_HEADER = 'selector:div.drawer-header'
DEVICE_INFO_SUBHEADER = 'xpath:..//div[@class="drawer-item"]//span[1]'
DEVICE_INFO_SUBCONTENT = 'xpath:..//div[@class="drawer-item"]//span[2]'
DEVICE_INFO_CLOSE = 'xpath://img[@alt="Close icon"]'
# Page Header
PAGE_FACILITY_ELEMENT = 'xpath://div[contains(@class, "select-facilities-select-input")]//input'
PAGE_FACILITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select")]'
PAGE_CURRENTMODEL = 'xpath://div[starts-with(@class, "search-input-row")]//button[contains(@class, "dropdown-toggle")]'
PAGE_BYMODELS_OPTIONS = 'xpath://div[contains(@class, "show")]//button[@role="menuitem"]'
PAGE_TEXTSEARCH = 'name:searchValue'
PAGE_FACILITY_HEADER = 'xpath://div[@class="drawer-title-container"]'
# Pagination
PGN_NEXT = 'xpath://div[contains(@class,"active")]//div[@class="flex justify-center"]//span[text()=">"]'
PGN_PREVIOUS_ALL = 'xpath://div[@class="flex justify-center"]//span[text()="<<"]'
PGN_PREVIOUS = 'xpath://div[contains(@class,"active")]//div[@class="flex justify-center"]//span[text()="<"]'
PGN_PAGENUM = 'xpath://div[contains(@class,"active")]//div[contains(@class,"react-bootstrap-table-pagination")]//button[contains(@id,"pagination") and contains(@class,"filled-btn")]'
BYROW = 'xpath:(//div[contains(@class,"custom-size-per-page-btn-dropdown")]//button)[1]'
BYROW_OPTIONS = 'xpath://div[contains(@class,"custom-size-per-page-btn-dropdown")]//button[contains(@class,"dropdown-item")]'
DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'

# log in clinic portal
RELEASE_VERSION = 'xpath://div[@class="footer-container"]'
SIGNIN_LOADING = 'selector:.ant-btn-loading-icon'
ICONSHORTCUT = 'xpath://a[@class="shortcuts-widget-item"][1]'
POPUP_VIDEO = 'xpath://div[@class="whats-new-modal"]'
POPUP_GOT_IT_VIDEO = 'xpath://button[@id="got-it-btn"]'
ERRORMESSAGE1ST = 'selector:div.error-message'
USERNAME_CLINIC = 'xpath://*[@id="username"]'
PASSWORD_CLINIC = 'xpath://*[@id="password"]'
SIGNIN_CLINIC = 'xpath://button[@type="submit"]'
#erp sso
ERP_LOGIN_PAGE = 'xpath://div[@class="login-page"]//button'
ERP_LOGIN_PAGE_NEXT = 'xpath://div[@id="lightbox"]//input[@type="submit"]'
ERP_USERNAME = 'xpath://div[@id="lightbox"]//input[@type="email"]'
ERP_PASSWORD = 'xpath://div[@id="lightbox"]//input[@type="password"]'
ERP_SKIP_SETUP = 'xpath://button[text()="Skip setup"]'
ERP_MENU_REPO = 'xpath://div[@class="all-portal-container"]//div[@class="portal-card"]'
