CUSTOMER_SUBTAB = 'xpath://li[contains(@class,"nav-item")]'
CUSTOMER_MENU_SUBTAB = 'xpath://div[contains(@class,"submenu ")]'
CUSTOMER_PAGEHEADER = 'xpath://span[@class="title"]'
CUSTOMER_PAGEHEADER_BILLING = 'xpath://div[@class="container-main"]//div[@class="row"]'
CUSTOMER_PAGEHEADER_BIOCARE = 'xpath://div[@class="ant-page-header-heading"]'
CUSTOMER_FACILITIES_DETAIL = 'xpath://ul[contains(@class,"ant-menu ant-menu-root")]'
CUSTOMER_FACILITY_ACCESS = 'xpath://div[contains(@class, "facility-row")]//div[contains(@class,"row-action-facility-button")]'
CUSTOMER_FACILITY_EDIT_ICON = 'xpath://div[contains(@class, "facility-row")]//a[contains(@class,"row-action-facility-button")]'
CUSTOMER_FACILITY_HEADER = 'xpath://div[contains(@class, "container-fluid")]//thead//th'
CUSTOMER_FACILITY_CONTENT = 'xpath://div[contains(@class, "container-fluid")]//tbody//td'
CUSTOMER_FACILITY_PORTAL = 'xpath://div[@class="modal-content"]//label[@class="options-checkbox"]'
CUSTOMER_FACILITY_PORTAL_SUBMIT = 'xpath:(//div[@class="footer"]//button)[2]'
CUSTOMER_CONTENT_HEADER = 'xpath://div[@class="content"]'
CUSTOMER_CONTENT_HEADER_BIOCARE = 'xpath://div[@class="admin-login-banner"]'
CUSTOMER_EDIT_USER_USERNAME = 'xpath://div[@class="left-col-container"]//span[contains(@class,"pre-title")]'
CUSTOMER_CONTENT_PAGE = 'xpath://div[@id="content-page-id"]//div[contains(@class,"tab-content")]'
CUSTOMER_SALES_DASHBOARD = 'xpath://div[@class="body-left"]//div[@class="bottom"]'
CUSTOMER_SALES_VIEW_ACCOUNT = 'xpath://div[@class="detail-row-button"]'
CUSTOMER_SALES_ACCOUNT_DETAILS = 'xpath://div[@class="sale-info-page"]//div[contains(@class,"chart-container-wrapper")]//div[@class="area-chart"]'
CUSTOMER_SALES_TEAM_SUBTAB = 'xpath://div[@class="ant-tabs-tab-btn"]'

CUSTOMER_BIODIRECT_CONTENT = 'xpath://table[contains(@class,"table")]//tbody//td'
CUSTOMER_BIODIRECT_HEADER = 'xpath://table[contains(@class,"table")]//thead//th'
CUSTOMER_BIODIRECT_EDIT = 'xpath://img[@alt="Edit biodirect"]/..'
CUSTOMER_BIODIRECT_CONTENT_HEADER = 'xpath://div[contains(@class,"container-header")]//div[@class="title"]'

CUSTOMER_SUPPORT_EDIT = 'xpath://img[@alt="Edit Ticket Icon"]/..'
CUSTOMER_SUPPORT_OPEN = 'xpath://img[@alt="Open Ticket Icon"]/..'
CUSTOMER_SUPPORT_EDIT_RMA = 'xpath://img[@alt="Edit RMA Icon"]/..'
CUSTOMER_SUPPORT_EDIT_OPERATION = 'xpath://img[@alt="Edit Icon"]/..'
