TABS = 'xpath://ul[starts-with(@class, "top-nav-tabs")]//li'
FACILITY_INPUT = 'xpath://div[contains(@class, "select-facilities-select-input")]//input'
FACILITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select")]'
CURRENTMODEL = 'xpath://div[starts-with(@class, "search-input-row")]//button[contains(@class, "dropdown-toggle")]'
BYMODELS_OPTIONS = 'xpath://div[contains(@class, "show")]//button[@role="menuitem"]'
TEXTSEARCH = 'name:searchValue'
TEXTSEARCH_CLEAR = 'xpath://button[starts-with(@class, "custom-search-input__clear-btn")]'
DEVICE_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
PGN_NEXT = 'xpath://div[contains(@class,"active")]//button[@id="next-page-btn"]'
PGN_PREVIOUS = 'xpath://div[contains(@class,"active")]//button[@id="previous-page-btn"]'
SORT_DEVICES_ID = 'xpath://div[contains(@class, "active")]//thead//th[1]'
PGN_MESSAGE = 'xpath://div[@class="toast-message"]'
# In study devices
INSTUDY_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
INSTUDY_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
INSTUDY_DATA_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
# End of life
EOL_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
EOL_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
EOL_DATA_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
# All device
ALL_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
ALL_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
ALL_DATA_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
ALL_SORT_DEVICES_ID = 'xpath://div[contains(@class, "active")]//thead//th[1]'
ALL_DEVICES_ID_DATA_CONTENT = 'xpath://button[@id="device-id-btn"]'
DEVICE_BYROW = 'xpath:(//div[@class="custom-body"]//div[@class="showing-number-ticket"]//button)[1]'
DEVICE_BYROW_OPTIONS = 'xpath://div[contains(@class,"active")]//div[@class="custom-body"]//div[@role="menu"]//button'
DEVICE_PGN_PAGENUM = 'xpath://div[contains(@class,"active")]//button[contains(@id,"pagination-drawn-pages")]'

# customer
DEVICE_LOADING = 'xpath:(//div[contains(@class,"active")]//div)[1]'
DEVICE_EDIT_ICON = 'xpath://img[@alt="EditTableIcon"]/..'
USER_EDIT_ICON = 'xpath://div[contains(@class,"active")]//div[@class="user-page"]//a[contains(@class,"row-action-facility")]'
GROUPS_EDIT_ICON = 'xpath://div[contains(@class,"active")]//img[@alt="Edit icon"]'
