TABS = 'xpath://div[@class="top-nav-tabs-container"]//li[@class="nav-item"]'
SUBTABS = 'xpath://div[contains(@class, "active")]//button[starts-with(@class, "toggle-button")]'
SEARCH_ICON = 'xpath://div[contains(@class, "active")]//img[@alt="Search icon"]/..'
SEARCH_CLOSE = 'xpath://div[contains(@class, "active")]//img[@alt="Search icon" and contains(@src, "yb3VuZCIvPgo8L3N2Zz4K")]/..'
SEARCH_INPUT = 'name:searchValue'
BYLAYOUT = 'xpath://div[contains(@class, "active")]//img[@alt="More menu layout icon"]/..'
BYLAYOUT_OPTIONS = 'xpath://div[contains(@class, "show")]//input[contains(@id, "layout-events")]/../label'
# Open events
OPENEVENTS_STARTPROCESS = 'xpath://button[@class="outline-btn"]'
OPENEVENTS_STOPPROCESS = 'xpath://button[contains(@class, "outline-btn") and contains(@class, "--red")]'
OPENEVENTS_SELECTEDOPTIONS = 'xpath://div[@class="selected-event-container"]/button'
OPENEVENTS_CLOSEALL = 'xpath://span[text()="Close all"]/../..'  # On Non-viable bucket
OPENEVENTS_LOADMORE = 'xpath://button[contains(@class, "load-more-btn")]'
OPENEVENTS_CONTENT_ROOT = 'xpath://div[contains(@class, "event-column-list-item") and @id]'
OPENEVENTS_HEADER1ST = 'xpath:.//span[@class="title"]'
OPENEVENTS_HEADER2ST = 'xpath:.//div[@class="ai-suggest-container"]/span'  # AI suggest
OPENEVENTS_CONTENT_STUDYID = 'xpath:.//button[contains(@class, "text-btn")]//span[@class="name"]'
OPENEVENTS_CONTENT_NODATA_TEXT = 'xpath://div[@class="no-data__text"]'
OPENEVENTS_CONTENT_EVENTID = 'xpath:.//span[@class="normal-content"]'
OPENEVENTS_CONTENT_EVENTTYPE = 'xpath:.//span[contains(@class, "normal-content") and contains(@class, "accent-green-label")]'
OPENEVENTS_CONTENT_STRIPIMAGE = 'xpath:.//div[contains(@class, "event-column-list-item__body")]//img[@alt="Final strip"]'
OPENEVENTS_CONTENT_AISG = 'xpath:.//div[@class="ai-suggest-container"]//div[@class="suggest-item"]'
OPENEVENTS_CONTENT_MOVE = 'xpath://div[@class="header-buttons"]//button[starts-with(@id, "header-button")]'
OPENEVENTS_CONTENT_CLOSE = 'xpath://div[starts-with(@id, "header-conflict-button")]/button'
OPENEVENTS_CONTENT_CLOSE_OPTIONS = 'xpath://div[contains(@class, "show")]/button[@class="dropdown-item"]'
OPENEVENTS_CONTENT_CHECKBOX = 'xpath:(//input[@name="closeEvents" and @type="checkbox"])'
OPENEVENTS_CONTENT_EDITBT = 'xpath://img[@alt="Edit icon"]'
OPENEVENTS_CONTENT_VIEWALLTRIPS = 'xpath://button[@class="view-all-strips"]/..'
OPENEVENTS_VIEWALLTRIPS_OPEN = 'xpath://img[@alt="New tab icon"]/..'
OPENEVENTS_EDIT_TECHNICIAN = 'xpath://button[@id="edit-btn-event-info-id"]'
OPENEVENTS_NO_OPEN = 'xpath://div[@class="no-data-container"]'
