TABS = 'xpath://li[@class="nav-item"]'
REPORTTYPES = 'xpath://div[@class="selected-report-type"]//button'
FACILITY_INPUT = 'xpath://div[contains(@class, "select-facilities-select-input")]//input'
FACILITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select")]'
ASSIGN_BUTTON = 'xpath://div[@id="action-button-row-undefined"]//button'
ASSSIGNTASKS_OPTIONS = 'xpath://div[@class="assign-tasks-container"]//div[contains(@class, "user-info")]'
SELECTEDTASKS = 'xpath://div[@class="button-container-left"]//span[@class="number"]'
TASK_REPORT_TYPE = 'xpath:(//div[@id="dropdow-input"]//button)[1]'
TASK_REPORT_TYPE_OPTION = 'xpath://div[@id="dropdow-input"]//div[@role="menu"]//button'
PGN_NEXT = 'xpath://div[contains(@class,"active")]//div[@class="flex justify-center"]//span[text()=">"]'

# qa team
QATEAM_EXPANDORCOLLAPSE = 'xpath://div[contains(@class, "team-sidebar-header")]//button'
QATEAM_CONTENT_ROOT = 'xpath://div[contains(@class, "work-load-card") and @aria-hidden]'
QATEAM_CONTENT_QANAME = 'xpath:.//div[contains(@class, "user-info")]//span[@class="name"]'
QATEAM_CONTENT_TIME = 'xpath:.//div[contains(@class, "user-info")]//div[@class="time"]'
QATEAM_CONTENT_SUMMARYRP = 'xpath:.//div[@class="left-content"]//div[@class="content"]'
QATEAM_CONTENT_NOTIFICATIONRP = 'xpath:.//div[@class="right-content"]//div[@class="content"]'
# unassigned
UNASSIGNED_ASSIGN = 'xpath://span[text()="Assign"]/../..'
UNASSIGNED_HEADER = 'xpath://div[@class="custom-table-container"]//th[not(@data-row-selection)]'
UNASSIGNED_HEADER_CHECKBOX = 'xpath://input[contains(@id, "custom-checkbox-input-select") and contains(@class, "--check-all")]'
UNASSIGNED_CONTENT = 'xpath://div[@class="custom-table-container"]//td[not(@class="selection-cell")]'
UNASSIGNED_CONTENT_ROW = 'xpath://div[@class="custom-table-container"]//tbody//tr'
UNASSIGNED_CONTENT_CHECKBOXES = 'xpath://input[contains(@id, "custom-checkbox-input-select") and not(contains(@class, "--check-all"))]'
UNASSIGNED_CONTENT_ASSIGNICONS = 'xpath://img[@alt="Assign Icon"]/..'
UNASSIGNED_ASSIGN_TASK_ROOT = 'xpath://div[@class="assign-tasks-container"]//div[contains(@class, "work-load-card") and @aria-hidden]'
UNASSIGNED_ASSIGN_TASK_NAME = 'xpath://div[@class="assign-tasks-container"]//div[contains(@class, "user-info")]//span[@class="name"]'
UNASSIGNED_ASSIGN_TASK_TIME = 'xpath://div[@class="assign-tasks-container"]//div[contains(@class, "user-info")]//div[@class="time"]'
UNASSIGNED_ASSIGN_TASK_SUMMARYRP = 'xpath://div[@class="assign-tasks-container"]//div[@class="left-content"]//div[@class="content"]'
UNASSIGNED_ASSIGN_TASK_NOTIFICATIONRP = 'xpath://div[@class="assign-tasks-container"]//div[@class="right-content"]//div[@class="content"]'
UNASSIGNED_STUDY_ID = 'xpath://button[@id="study-id-btn"]'
UNASSIGNED_PATIENT_NAME = 'xpath://button[@id="patient-name-formatter-btn"]'
# assigned
ASSIGNED_UNASSIGN = 'xpath://span[text()="Unassign"]/../..'
ASSIGNED_HEADER = 'xpath://div[@class="custom-table-container"]//th[not(@data-row-selection)]'
ASSIGNED_HEADER_CHECKBOX = 'xpath://input[contains(@id, "custom-checkbox-input-select") and contains(@class, "--check-all")]'
ASSIGNED_CONTENT = 'xpath://div[@class="custom-table-container"]//td[not(@class="selection-cell")]'
ASSIGNED_CONTENT_ROW = 'xpath://div[@class="custom-table-container"]//tbody//tr'
ASSIGNED_CONTENT_CHECKBOXES = 'xpath://input[contains(@id, "custom-checkbox-input-select")]'
ASSIGNED_CONTENT_ASSIGNEE = 'xpath://div[@role="menu" and contains(@class, "show")]//button[@role="menuitem"]/span'
ASSIGNED_CONTENT_UNASSIGN = 'xpath://img[@alt="Unassign Icon"]/..'
ASSIGNED_UNASSIGN_CONFIRM = 'xpath://button[contains(@class, "unassign-btn")]'
ASSIGNED_UNASSIGN_CANCEL = 'xpath://button[contains(@class, "cancel-btn")]'
ASSIGNED_STUDY_ID = 'xpath://button[@id="study-id-btn"]'
ASSIGNED_PATIENT_NAME = 'xpath://button[@id="patient-name-formatter-btn"]'
# overview
OVERVIEW_BODY = 'xpath://div[@class="overview-tab-body"]'
