STATUS = 'xpath:(//div[@class = "patients-body-main"]//div[contains(@class, "select-ct-wrapper")])[1]'
STATUS_OPTIONS = 'xpath://div[@class = "select-ct-wrapper"]//div[@class = "ant-select-item-option-content"]'
PATIENT = 'xpath:(//div[@class = "patients-body-main"]//div[contains(@class, "select-ct-wrapper")])[2]'
PATIENT_OPTIONS = 'xpath:(//div[@class = "patients-body-main"]//div[contains(@class, "select-ct-wrapper")])[2]//div[contains(@class, "ant-select-item-option-content")]'
SEARCHBY = 'xpath://div[@class = "patients-body-main"]//span[contains(@class, "search-filter-btn")]'
SEARCHBY_OPTIONS = 'xpath://div[@class="search-menu-title"]/parent::ul//li[@data-menu-id]'
SEARCH_TEXTBOX = 'xpath://div[@class = "patients-body-main"]//input[contains(@placeholder, "Search by")]'
HEADER = 'xpath://div[@class = "patients-body-main"]//th'
CONTENT = 'xpath://div[@class = "patients-body-main"]//tbody//tr[@data-row-key]/td'
CONTENT_PATIENTNAME = 'xpath://div[contains(@class, "bioheart-table-wrapper")]//tbody//td[3]//button'
CONTENT_ROW = 'xpath://div[contains(@class, "bioheart-table-wrapper")]//tbody//tr[@data-row-key]'
