TABS = 'xpath://div[contains(@class, "ant-tabs-top")]/div[1]//span[@class="tab-header"]'
BACK = 'xpath://div[@aria-label="Back"]'
BACK_CONFIRM = 'xpath://div[@class="confirmation-layout-footer"]//button[not(contains(@class, "-primary"))]'
# Common info
COMMON_TOPINFO = 'xpath://div[@class="details-page-content-left"]//div[@class="patient-info-title"]/*'
COMMON_MIDINFO_DATA = 'xpath://div[@class="details-page-content-left"]//div[contains(@class, "display-data") and contains(@class, "-wrapper")]'
COMMON_REGCLINIC_CAREGIVERS_DATA = 'xpath://div[@class="details-page-content-left"]//div[@class="registered-clinic" or @class="mt8" or @class="display-caregiver-wrapper-title" or contains(@class, "ant-space-vertical")]'
COMMON_EDIT = 'xpath://div[@class="patient-info-body"]//span[@aria-label="edit"]/..'
COMMON_CREATEAPPOINTMENT = 'xpath://div[@class="patient-info-body"]//button[contains(@class, "patient-info-create-apt-btn")]'
COMMON_DELETECAREPLAN = 'xpath://div[@class="patient-info-body"]/button[contains(@class, "ant-btn")]'
COMMON_DELETECAREPLAN_YES = 'xpath://div[@class="ant-modal-content"]//button[contains(@class, "ant-btn-primary")]'
COMMON_ASSIGNNURSE = 'xpath://div[@class="patient-info-body"]//span[@aria-label="user-add"]/../..'
COMMON_ASSIGNPHYSICIAN = 'xpath://div[@class="patient-info-body"]//span[@aria-label="user-add"]/../..'
COMMON_CAREGIVERS_EDIT = 'xpath://div[@class="patient-info-body"]//div[@class="display-caregiver-wrapper"]//span[@aria-label="edit"]'
COMMON_STARTHEALTHCARE = 'xpath://span[@aria-label="plus"]/../following-sibling::button'
COMMON_STOPHEALTHCARE = 'xpath://span[@aria-label="plus"]/../following-sibling::button'
COMMON_RESENDRFCODE = 'xpath://span[@aria-label="mail"]/..'
COMMON_REACTIVATECAREPLAN = 'xpath://div[@class="patient-info-body"]//button[contains(@class, "ant-btn-primary")]'
# Assign nurse
AN_NURSE = 'xpath://div[@class="assign-drawer-wrapper"]//div[@class="ant-select-selector"]//input'
AN_NURSE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[contains(@class, "ant-select-item-option")]//div[@class="ant-select-item-option-content"]/div[not(contains(@class, "avatar"))]'
AN_ASSIGNTOME = 'xpath://div[@class="assign-drawer-wrapper"]//button[contains(@class, "ant-btn-primary") and not(contains(@class, "btn-assign"))]'
AN_ASSIGN = 'xpath://div[@class="assign-drawer-wrapper"]//button[contains(@class, "ant-btn-primary") and contains(@class, "btn-assign")]'
# Assign physician
AP_PHYSICIAN = 'xpath://div[@class="assign-drawer-wrapper"]//div[@class="ant-select-selector"]//input'
AP_PHYSICAN_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[contains(@class, "ant-select-item-option")]//div[@class="ant-select-item-option-content"]/div[not(contains(@class, "avatar"))]'
AP_ASSIGN = 'xpath://div[@class="assign-drawer-wrapper"]//button[contains(@class, "btn-assign")]'
# Edit caregivers
ECAREGIVERS_NURSE = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "open")]//div[@class="ant-select-selector"])[1]//input'
ECAREGIVERS_NURSE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[contains(@class, "ant-select-item-option")]//div[@class="search-option-name"]'
ECAREGIVERS_PHYSICIAN = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "open")]//div[@class="ant-select-selector"])[2]//input'
ECAREGIVERS_PHYSICIAN_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[contains(@class, "ant-select-item-option")]//div[@class="search-option-name"]'
ECAREGIVERS_CHANGE = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "open")]//button[contains(@class, "ant-btn-primary")]'
# Stop health care program
STOPHC_REASON_OPTIONS = 'xpath://div[@class="ant-modal-content"]//div[@class="radio-item"]/label'
STOPHC_STOP = 'xpath://div[@class="ant-modal-content"]//button[contains(@class, "ant-btn-primary")]'
# Resend reference code
RESENDRF_RESEND = 'xpath://div[@class="ant-modal-content"]//button[contains(@class, "ant-btn-primary")]'
# Reactivate care plan
REACTCP_REACTIVATE = 'xpath://div[@class="ant-modal-content"]//button[contains(@class, "ant-btn-primary")]'
# Initial intake info
INITINTAKE_DATA = 'xpath://div[@class="initial-intake-info-view"]'
INITINTAKE_ALLERGIES_DATA_CONTENT = 'xpath://div[@class="initial-intake-info-view"]//div[contains(@class, "allergies-list")]'
INITINTAKE_CARDIACHISTORY_DATA_HEADER = 'xpath://div[contains(@class, "afib-history")]//div[contains(@class, "data-item") and contains(@class, "left-item")]'
INITINTAKE_CARDIACHISTORY_DATA_CONTENT = 'xpath://div[contains(@class, "afib-history")]//div[contains(@class, "data-item") and contains(@class, "right-item")]'
INITINTAKE_CARDIACHISTORY = 'xpath://div[@class="initial-intake-info-view"]//button[contains(@class, "history-add")]'
INITINTAKE_ALLERGIES = 'xpath://div[@class="initial-intake-info-view"]//button[contains(@class, "allergies-add")]'
INITINTAKE_QUALITYOFLIFE = 'xpath://div[@class="initial-intake-info-view"]//div[@class="quality-of-life"]//button'
# Initial intake info > add general cardiac history
INITINTAKE_CURRENTSYMPTOMS = 'xpath:(//div[@class="initial-intake-info-editing-main"]//div[@class="medical-history-select"])[1]//div[@class="ant-select-selection-overflow"]'
INITINTAKE_CURRENTSYMPTOMS_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
INITINTAKE_PASTMEDICAL = 'xpath:(//div[@class="initial-intake-info-editing-main"]//div[@class="medical-history-select"])[2]//div[@class="custom-select-input"]//input'
INITINTAKE_PASTMEDICAL_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
INITINTAKE_MEDICATIONPREVIOUSLY = 'xpath:(//div[@class="initial-intake-info-editing-main"]//div[contains(@class, "checkbox-ct-wrapper")])[1]//div[contains(@class, "custom-select-input")]'
INITINTAKE_MEDICATIONPREVIOUSLY_NO = 'xpath:(//div[@class="initial-intake-info-editing-main"]//div[contains(@class, "checkbox-ct-wrapper")])[1]//label[@class="ant-checkbox-wrapper"]'
INITINTAKE_MEDICATIONPREVIOUSLY_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
INITINTAKE_MEDICATIONCURRENTLY = 'xpath:(//div[@class="initial-intake-info-editing-main"]//div[contains(@class, "checkbox-ct-wrapper")])[2]//div[contains(@class, "custom-select-input")]'
INITINTAKE_MEDICATIONCURRENTLY_NO = 'xpath:(//div[@class="initial-intake-info-editing-main"]//div[contains(@class, "checkbox-ct-wrapper")])[2]//label[@class="ant-checkbox-wrapper"]'
INITINTAKE_MEDICATIONCURRENTLY_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
INITINTAKE_ADD = 'xpath://div[@class="initial-intake-info-editing-main"]//button[contains(@class, "ant-btn-primary")]'
# Initial intake info > allergies
ALLERGIES_ANSWER = 'xpath://div[contains(@class, "add-allergy-modal")]//textarea[@name="allergy"]'
ALLERGIES_SAVE = 'xpath://div[contains(@class, "add-allergy-modal")]//button[contains(@class, "ant-btn-primary")]'
# Baseline info
BASELINE_DATA = 'xpath://div[@class="baseline-info-main"]'
BASELINE_INPUTBASELINE = 'xpath://div[@class="baseline-info-main"]//button[contains(@class, "ant-btn-primary")]'
BASELINE_NEXT = 'xpath://div[contains(@class, "width-buttons")]//button[contains(@class, "ant-btn-primary")]'
# Baseline info > Step 1/7
# # Diagnosed conditions
BASELINE_DIAGNOSEDCONDITIONS = 'xpath://div[@class="input-baseline-info"]//div[@class="diagnosed-conditions-body"]//div[@class="custom-select-input"]'
BASELINE_DIAGNOSEDCONDITIONS_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
BASELINE_DIAGNOSEDONSETDATE = 'xpath://div[@class="input-baseline-info"]//div[@class="diagnosed-conditions-body"]//input[@placeholder="Select date"]'
BASELINE_DIAGNOSEDONSETDATE_TODAY = 'xpath://div[contains(@class, "ant-picker-dropdown") and not(contains(@class, "hidden"))]//a[@class="ant-picker-today-btn"]'
BASELINE_DIAGNOSEDCONFIRMEDVIA = 'xpath://div[@class="input-baseline-info"]//div[@class="diagnosed-conditions-body"]//div[@class="ant-select-selector"]'
BASELINE_DIAGNOSEDCONFIRMEDVIA_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
BASELINE_DIAGNOADDMORE = 'xpath://div[@class="input-baseline-info"]//span[@aria-label="plus"]/..'
# # At-risk conditions
BASELINE_RISKCONDITIONS = 'xpath://button[contains(@class, "ant-btn-link")]/following-sibling::div[@class="custom-select-input"]//input'
BASELINE_RISKCONDITIONS_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
BASELINE_RISKCONDITIONS_NOTES = 'xpath://button[contains(@class, "ant-btn-link")]/following-sibling::div[contains(@class, "input-ct-wrapper")]//textarea'
# Baseline info > Step 2/7
# # Complete blood count
BASELINE_CBC_DATE = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[1]//input[@placeholder="Select date"]'
BASELINE_CBC_DATE_TODAY = 'xpath://div[contains(@class, "picker-dropdown") and not(contains(@class, "dropdown-hidden"))]//a[@class="ant-picker-today-btn"]'
BASELINE_CBC_SUMMARY = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[1]//textarea[@placeholder="Enter your summary"]'
BASELINE_CBC_ATTACHMENT = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[1]//input[@type="file"]'
# # Liver function test
BASELINE_LFT_DATE = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[2]//input[@placeholder="Select date"]'
BASELINE_LFT_DATE_TODAY = 'xpath://div[contains(@class, "picker-dropdown") and not(contains(@class, "dropdown-hidden"))]//a[@class="ant-picker-today-btn"]'
BASELINE_LFT_SUMMARY = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[2]//textarea[@placeholder="Enter your summary"]'
BASELINE_LFT_ATTACHMENT = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[2]//input[@type="file"]'
# # 12 leads ECG
BASELINE_LEADS_DATE = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[3]//input[@placeholder="Select date"]'
BASELINE_LEADS_DATE_TODAY = 'xpath://div[contains(@class, "picker-dropdown") and not(contains(@class, "dropdown-hidden"))]//a[@class="ant-picker-today-btn"]'
BASELINE_LEADS_SUMMARY = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[3]//textarea[@placeholder="Enter your summary"]'
BASELINE_LEADS_ATTACHMENT = 'xpath:(//div[contains(@class, "input-baseline-info-step2")]//div[contains(@class, "date-summary")])[3]//input[@type="file"]'
# Baseline info > Step 3/7
# # Exercise stress testing
BASELINE_EST_DATE = 'xpath://div[contains(@class, "input-baseline-info-step3")]//div[contains(@class, "date-summary")]//input[@placeholder="Select date"]'
BASELINE_EST_DATE_TODAY = 'xpath://div[contains(@class, "picker-dropdown") and not(contains(@class, "dropdown-hidden"))]//a[@class="ant-picker-today-btn"]'
BASELINE_EST_SUMMARY = 'xpath://div[contains(@class, "input-baseline-info-step3")]//div[contains(@class, "date-summary")]//textarea[@placeholder="Enter your summary"]'
BASELINE_EST_ATTACHMENT = 'xpath://div[contains(@class, "input-baseline-info-step3")]//div[contains(@class, "date-summary")]//input[@type="file"]'
# # Echocardiogram
BASELINE_ECHO_DATE = 'xpath:(//div[contains(@class, "input-baseline-info-step3")]//div[contains(@class, "datepicker")])[2]'
BASELINE_ECHO_DATE_TODAY = 'xpath://div[contains(@class, "picker-dropdown") and not(contains(@class, "dropdown-hidden"))]//a[@class="ant-picker-today-btn"]'
BASELINE_ECHO_LVEF = 'xpath://div[contains(@class, "input-baseline-info-step3")]//input[@name="echocardiogramLVEF"]'
# Baseline info > Step 4/7
# # CHA2DS2-VASc score
BASELINE_VASC_SCORE = 'xpath://div[contains(@class, "input-baseline-info-step6")]//label[contains(@class, "ant-checkbox-wrapper")]'
# Baseline info > Step 5/7
# # HAS-BLED clinical characteristic
BASELINE_CLINICALCHAR = 'xpath://div[contains(@class, "input-baseline-info-step7")]//label[contains(@class, "ant-checkbox-wrapper")]'
# Baseline info > Step 6/7
# # EHRA score
BASELINE_EHRASCORE = 'xpath://div[contains(@class, "input-baseline-info-step8")]//label[contains(@class, "ant-radio-wrapper")]'
# Baseline info > Step 7/7
# # Framingham risk score (FRS)
BASELINE_FRS_CHECK = 'xpath://div[contains(@class, "input-baseline-info-step7")]//input[@name="isEnsurePatientAge"]'
BASELINE_FRS_GENDER = 'xpath://div[contains(@class, "input-baseline-info-step7")]//div[contains(@class, "ant-select-selector")]'
BASELINE_FRS_GENDER_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
BASELINE_FRS_AGE = 'name:frsAge'
BASELINE_FRS_SMOKER = 'xpath:(//div[contains(@class, "input-baseline-info-step7")]//div[contains(@class, "ant-radio-group")])[1]//label[contains(@class, "ant-radio-wrapper")]'
BASELINE_TOTALCHOLESTEROL = 'name:totalCholesterol'
BASELINE_HDLCHOLESTEROL = 'name:HDLCholesterol'
BASELINE_SYSTOLICBP = 'name:systolicBP'
BASELINE_BLOODPRESSURE = 'xpath:(//div[contains(@class, "input-baseline-info-step7")]//div[contains(@class, "ant-radio-group")])[2]//label[contains(@class, "ant-radio-wrapper")]'
BASELINE_FINISH = 'xpath://div[contains(@class, "width-buttons")]//button[contains(@class, "ant-btn-primary")]'
# Care plan
CAREPLAN_MENU = 'xpath://div[@class="care-plan-main f-row"]//span[@class="ant-menu-title-content"]'
CAREPLAN_MENU_OVERVIEW = 'xpath://div[@class="care-plan-overview-wrapper"]/div'
CAREPLAN_MENU_CONDINFO = 'xpath://div[@class="care-plan-diseases-info-wrapper"]/div'
CAREPLAN_MENU_MED_ACTIVE = 'xpath://div[contains(@id, "panel-Active")]//div[@class="care-plan-prescription-wrapper"]'
CAREPLAN_MENU_MED_INACTIVE = 'xpath://div[contains(@id, "panel-Inactive")]//div[@class="care-plan-prescription-wrapper"]/div'
CAREPLAN_MENU_QOL = 'xpath://div[contains(@class, "care-plan-quality-of-life")]'
CAREPLAN_MENU_RPSETTINGS = 'xpath://div[@class="care-plan-report-settings-wrapper"]'
# Care plan overview
CPO_ADDCAPLANOVERVIEW = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//span[@aria-label="plus"]/..'
CPO_PATIENTEDUCATION = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//div[@class="multiple-checkbox-wrapper"]//label[contains(@class, "ant-checkbox-wrapper")]'
CPO_EQUIPMENT = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//div[contains(@class, "opacity-text-disabled")]//label[contains(@class, "ant-checkbox-wrapper")]'
CPO_NOTES = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//textarea[@placeholder="Notes..."]'
CPO_ADD = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//button[contains(@class, "ant-btn-primary")]'
CPO_EDIT = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//span[@aria-label="edit"]/..'
# Blook work
CPO_BLOODWORK = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//button[contains(@class, "bloodwork-toggle")]'
CPO_BLOODWORK_FREQUENCY = 'xpath:(//button[contains(@class, "bloodwork-toggle")]/..//div[contains(@class, "input-ct-wrapper")])[1]//input[@placeholder="Enter frequency"]'
CPO_BLOODWORK_FREQUENCYUNIT = 'xpath:(//button[contains(@class, "bloodwork-toggle")]/..//div[contains(@class, "input-ct-wrapper")])[1]//div[@class="select-ct-wrapper"]//input'
CPO_BLOODWORK_FREQUENCYUNIT_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidde"))]//div[@aria-selected]'
CPO_BLOODWORK_DUENEXT = 'xpath:(//button[contains(@class, "bloodwork-toggle")]/..//div[contains(@class, "input-ct-wrapper")])[2]//input[@placeholder="Select date"]'
CPO_BLOODWORK_TESTTYPE = 'xpath:(//button[contains(@class, "bloodwork-toggle")]/..//div[contains(@class, "input-ct-wrapper")])[3]//div[@class="select-ct-wrapper"]'
CPO_BLOODWORK_TESTTYPE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidde"))]//div[@aria-selected and contains(@class, "select-item-option")]'
# Stress test
CPO_STRESSTEST = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//button[contains(@class, "stress-test-toggle")]'
CPO_STRESSTEST_FREQUENCY = 'xpath:(//button[contains(@class, "stress-test-toggle")]/..//div[contains(@class, "input-ct-wrapper")])[1]//input[@placeholder="Enter frequency"]'
CPO_STRESSTEST_FREQUENCYUNIT = 'xpath:(//button[contains(@class, "stress-test-toggle")]/..//div[contains(@class, "input-ct-wrapper")])[1]//div[@class="select-ct-wrapper"]//input'
CPO_STRESSTEST_DUENEXT = 'xpath:(//button[contains(@class, "stress-test-toggle")]/..//div[contains(@class, "input-ct-wrapper")])[2]//input[@placeholder="Select date"]'
CPO_FWUSCHEDULE = 'xpath://div[@role="tabpanel" and contains(@aria-labelledby, "tab-Overview")]//div[contains(@class, "ant-divider")][5]/following-sibling::div[contains(@class, "select-ct-wrapper")]//input'
# Careplan conditions information
CI_SELECTCONDITIONS = 'xpath://div[contains(@id, "panel-Conditions information")]//button[contains(@class, "ant-btn-primary")]'
# Care plan medication active
MEDICATIONACT_ROOT = 'xpath://div[@class="medication-card-item"]'
MEDICATIONACT_HEADER = 'xpath:.//div[contains(@class, "medication-title")]'
MEDICATIONACT_CONTENT = 'xpath:.//div[contains(@class, "medication-info")]'
MEDICATIONACT_MEDICATION_HEAD = 'xpath:.//div[contains(@class, "medication-card-item-header-name")]'
MEDICATIONACT_ADD = 'xpath://div[contains(@id, "panel-Active")]//button[contains(@class, "ant-btn-primary")]'
MEDICATIONACT_SAVECHANGES = 'xpath://span[text()="Save changes"]'
MEDICATIONACT_EDITMEDI = 'xpath://span[text()="Edit medications"]/..'
MEDICATIONACT_ARCHIVE = 'xpath://div[@class="medication-card-item"]//span[@aria-label="minus-circle"]/..'
MEDICATIONACT_ARCHIVE_ROOT = 'xpath://div[contains(@class, "inactive") and contains(@class, "medication-card-item")]'
MEDICATIONACT_ARCHIVE_HEADER = 'xpath:.//div[contains(@class, "medication-title")]'
MEDICATIONACT_ARCHIVE_MEDICATIONHEAD = 'xpath:.//div[contains(@class, "medication-card-item-header-name")]'
MEDICATIONACT_ARCHIVE_CONTENT = 'xpath:.//div[contains(@class, "medication-info")]'
MEDICATIONACT_PRESCRIBE = 'xpath://div[@class="medication-card"]//span[@aria-label="plus-circle"]/..'
MEDICATIONACT_EDIT = 'xpath://div[@class="medication-card-item"]//span[@aria-label="edit"]/..'
MEDICATIONACT_MEDI = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="custom-select-input"]//input'
MEDICATIONACT_MEDI_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
MEDICATIONACT_QUANTITY = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//input[@name="quantity"]'
MEDICATIONACT_QUANTITYUNIT = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="ant-select-selector"])[1]//input'
MEDICATIONACT_QUANTITYUNIT_OPTIONS = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[contains(@class, "ant-select-dropdown")]//div[@aria-selected and contains(@class, "select-item")]'
MEDICATIONACT_FREQUENCY = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="ant-select-selector"])[2]//input'
MEDICATIONACT_FREQUENCY_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
MEDICATIONACT_TIMETOTAKE = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//div[@class="time-to-take-main"]//input[@placeholder="Select date"]'
MEDICATIONACT_NOTES = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "ant-drawer-open")]//textarea[contains(@placeholder, "Notes")]'
MEDICATIONACT_SAVE_ACTIONS = 'xpath://div[@class="add-medication-drawer-footer"]//button[contains(@class, "ant-btn-primary")]'
MEDICATIONACT_CONFIRMPRESCRIBE = 'xpath://div[@class="add-medication-drawer-footer"]//button[contains(@class, "ant-btn-primary") and not(contains(@class, "background-ghost"))]'
# Care plan medication inactive
MEDICATIONINACT_ROOT = 'xpath://div[contains(@class, "medication-card-item") and contains(@class, "inactive")]'
MEDICATIONINACT_MEDICATION_HEAD = 'xpath:.//div[contains(@class, "medication-card-item-header-name")]'
MEDICATIONINACT_HEADER = 'xpath:.//div[contains(@class, "medication-title")]'
MEDICATIONINACT_CONTENT = 'xpath:.//div[contains(@class, "medication-info")]'
MEDICATIONINACT_DELETE = 'xpath://div[@class="care-plan-prescription-wrapper"]//span[@aria-label="delete"]/..'
MEDICATIONINACT_DELETE_CONFIRM = 'xpath://div[contains(@class, "modal-send-report")]//span[text()="Delete"]/..'
MEDICATIONINACT_PRESCRIBE = 'xpath://div[@class="care-plan-prescription-wrapper"]//span[@aria-label="plus-circle"]/..'
# Medical test results
MEDTESTRES_MENU = 'xpath://div[@class="medical-test-result-main"]// li[@data-menu-id]'
MEDTESTRES_MENU_SAMPLEINFO = 'xpath://div[@role="tabpanel"]//div[@class="content-wrapper"]'
# Medical - Stress test
MEDISTRESSTEST_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Stress test")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDISTRESSTEST_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Stress test")]//span[@aria-label="edit"]/..'
MEDISTRESSTEST_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Stress test")]//input[@placeholder="Select date"]'
MEDISTRESSTEST_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Stress test")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDISTRESSTEST_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Stress test")]//textarea[@placeholder="Enter your summary"]'
MEDISTRESSTEST_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Stress test")]//input[@type="file"]'
MEDISTRESSTEST_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Stress test")]//button[contains(@class, "ant-btn-primary")]'
# Medical - Complete blood count
MEDICOMPBLOOD_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Complete blood count")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDICOMPBLOOD_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Complete blood count")]//span[@aria-label="edit"]/..'
MEDICOMPBLOOD_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Complete blood count")]//input[@placeholder="Select date"]'
MEDICOMPBLOOD_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Complete blood count")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDICOMPBLOOD_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Complete blood count")]//textarea[@placeholder="Enter your summary"]'
MEDICOMPBLOOD_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Complete blood count")]//input[@type="file"]'
MEDICOMPBLOOD_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Complete blood count")]//button[contains(@class, "ant-btn-primary")]'
# Medical - Liver function testing
MEDILIVERFUNC_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Liver function testing")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDILIVERFUNC_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Liver function testing")]//span[@aria-label="edit"]/..'
MEDILIVERFUNC_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Liver function testing")]//input[@placeholder="Select date"]'
MEDILIVERFUNC_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Liver function testing")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDILIVERFUNC_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Liver function testing")]//textarea[@placeholder="Enter your summary"]'
MEDILIVERFUNC_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Liver function testing")]//input[@type="file"]'
MEDILIVERFUNC_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Liver function testing")]//button[contains(@class, "ant-btn-primary")]'
# Medical - Fasting blood sugar
MEDIFASTBLOOD_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Fasting blood sugar")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDIFASTBLOOD_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Fasting blood sugar")]//span[@aria-label="edit"]/..'
MEDIFASTBLOOD_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Fasting blood sugar")]//input[@placeholder="Select date"]'
MEDIFASTBLOOD_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Fasting blood sugar")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDIFASTBLOOD_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Fasting blood sugar")]//textarea[@placeholder="Enter your summary"]'
MEDIFASTBLOOD_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Fasting blood sugar")]//input[@type="file"]'
MEDIFASTBLOOD_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Fasting blood sugar")]//button[contains(@class, "ant-btn-primary")]'
# Medical - Lipid profile
MEDILIPIDPROFILE_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Lipid profile")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDILIPIDPROFILE_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Lipid profile")]//span[@aria-label="edit"]/..'
MEDILIPIDPROFILE_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Lipid profile")]//input[@placeholder="Select date"]'
MEDILIPIDPROFILE_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Lipid profile")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDILIPIDPROFILE_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Lipid profile")]//textarea[@placeholder="Enter your summary"]'
MEDILIPIDPROFILE_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Lipid profile")]//input[@type="file"]'
MEDILIPIDPROFILE_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Lipid profile")]//button[contains(@class, "ant-btn-primary")]'
# Medical - INR
MEDIINR_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDIINR_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//span[@aria-label="edit"]/..'
MEDIINR_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//input[@placeholder="Select date"]'
MEDIINR_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDIINR_RESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//input[@name="inrRes"]'
MEDIINR_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//textarea[@placeholder="Enter your summary"]'
MEDIINR_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//input[@type="file"]'
MEDIINR_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-INR")]//button[contains(@class, "ant-btn-primary")]'
# Medical - TSH
MEDITSH_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-TSH")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDITSH_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-TSH")]//span[@aria-label="edit"]/..'
MEDITSH_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-TSH")]//input[@placeholder="Select date"]'
MEDITSH_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-TSH")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDITSH_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-TSH")]//textarea[@placeholder="Enter your summary"]'
MEDITSH_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-TSH")]//input[@type="file"]'
MEDITSH_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-TSH")]//button[contains(@class, "ant-btn-primary")]'
# Medical - creatinine
MEDICATININE_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Creatinine")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDICATININE_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Creatinine")]//span[@aria-label="edit"]/..'
MEDICATININE_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Creatinine")]//input[@placeholder="Select date"]'
MEDICATININE_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Creatinine")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDICATININE_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Creatinine")]//textarea[@placeholder="Enter your summary"]'
MEDICATININE_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Creatinine")]//input[@type="file"]'
MEDICATININE_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Creatinine")]//button[contains(@class, "ant-btn-primary")]'
# Medical - HbA1c
MEDIHBA1C_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDIHBA1C_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//span[@aria-label="edit"]/..'
MEDIHBA1C_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//input[@placeholder="Select date"]'
MEDIHBA1C_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDIHBA1C_PERCENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//input[@name="hgbA1C"]'
MEDIHBA1C_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//textarea[@placeholder="Enter your summary"]'
MEDIHBA1C_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//input[@type="file"]'
MEDIHBA1C_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-HbA1c")]//button[contains(@class, "ant-btn-primary")]'
# Medical - Echocardiogram
MEDIECHO_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDIECHO_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//span[@aria-label="edit"]/..'
MEDIECHO_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//input[@placeholder="Select date"]'
MEDIECHO_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDIECHO_LVEF = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//input[@name="lvef"]'
MEDIECHO_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//textarea[@placeholder="Enter your summary"]'
MEDIECHO_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//input[@type="file"]'
MEDIECHO_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Echocardiogram")]//button[contains(@class, "ant-btn-primary")]'
# Medical - Other test
MEDIOTHER_ADDNEW = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//span[@aria-label="plus" and contains(@class, "anticon-plus")]/..'
MEDIOTHER_EDIT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//span[@aria-label="edit"]/..'
MEDIOTHER_TITLE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//input[@placeholder="Enter test title"]'
MEDIOTHER_DATE = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//input[@placeholder="Select date"]'
MEDIOTHER_DATE_TODAY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
MEDIOTHER_SUMMARY = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//textarea[@placeholder="Enter your summary"]'
MEDIOTHER_ATTACHMENT = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//input[@type="file"]'
MEDIOTHER_ADDRESULTS = 'xpath://div[@role="tabpanel" and contains(@id, "panel-Other tests")]//button[contains(@class, "ant-btn-primary")]'
# Heart monitor
HEARTMON_MENU = 'xpath://div[@class="heart-monitor-tab-main"]//div[@role="tab"]/..'
HEARTMON_MENU_SAMPLEINFO = 'xpath://div[@class="heart-monitor-tab-main"]//div[contains(@class, "ant-tabs-tabpane-active")]'
# Heart monitor > current study
CURSTUDY_PRESCRIBENEWSTUDY = 'xpath://div[@class="heart-monitor-tab-main"]//div[contains(@class, "ant-tabs-tabpane-active")]//button[contains(@class, "ant-btn-primary")]'
CURSTUDY_CREATESTUDY = 'xpath://div[@class="heart-monitor-tab-main"]//div[contains(@class, "ant-tabs-tabpane-active")]//button[contains(@class, "eart-mornitor-current-study-create-study-btn")]'
CURSTUDY_CANCELSTUDY = 'xpath://div[@class="heart-monitor-tab-main"]//div[contains(@class, "ant-tabs-tabpane-active")]//button[contains(@class, "heart-mornitor-current-study-cancel-btn")]'
CURSTUDY_CANCELSTUDY_YES = 'xpath://div[@class="ant-modal-content"]//div[contains(@class, "footer-buttons")]//button[contains(@class, "ant-btn-primary")]'
CURSTUDY_VIEWALL = 'xpath://div[@class="heart-mornitor-current-study"]//button[contains(@class, "ant-btn-link")]'
# HM > Prescribe new study
PRESCRIBE_BIODIRECT = 'xpath://input[@name="isUseBiodirect"]'
PRESCRIBE_DEVICE = 'xpath://div[contains(@class, "ant-drawer-right")]//label[contains(@class, "ant-radio-wrapper")]'
PRESCRIBE_STUDYTYPE = 'xpath:(//div[contains(@class, "ant-drawer-right")]//div[@class="ant-select-selector"])[1]'
PRESCRIBE_STUDYTYPE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "item-option")]'
PRESCRIBE_STUDYDURATION = 'name:studyDuration'
PRESCRIBE_PRIMARYDIAGNOCODE = 'xpath:(//div[contains(@class, "ant-drawer-right")]//div[@class="ant-select-selector"])[2]//input'
PRESCRIBE_PRIMARYDIAGNOCODE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "item-option")]'
PRESCRIBE_SECONDARYDIAGNOCODE = 'xpath:(//div[contains(@class, "ant-drawer-right")]//div[@class="ant-select-selector"])[3]//input'
PRESCRIBE_SECONDARYDIAGNOCODE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "item-option")]'
PRESCRIBE_NOTES = 'xpath://textarea[@placeholder="Notes..."]'
PRESCRIBE_ADD = 'xpath://div[contains(@class, "ant-drawer-right")]//button[contains(@class, "ant-btn-primary")]'
# Create new study
STUDY_P1_PATIENTID = 'xpath://input[@placeholder="Enter patient ID"]'
STUDY_P1_PACEMAKER = 'xpath://div[@class="create-new-patient-body-right"]//input[@class="ant-radio-input"]/../..'
STUDY_P1_SECONDARYPHONE = 'name:phoneNumber'
STUDY_P1_ADDCONTACT = 'xpath://div[@class="create-new-patient-body-right"]//button[contains(@class, "new-study-add-contact-btn")]'
STUDY_P1_CONTACT_NAME = 'xpath://div[@class="create-new-patient-body-right"]//input[@placeholder="Enter name"]'
STUDY_P1_CONTACT_RELATIONSHIP = 'xpath://div[@class="create-new-patient-body-right"]//input[@placeholder="Enter relationship"]'
STUDY_P1_CONTACT_PHONE = 'xpath://div[@class="create-new-patient-body-right"]//input[@name="secondPhoneNumber"]'
STUDY_P1_CONTACT_EMAIL = 'xpath://div[@class="create-new-patient-body-right"]//input[@placeholder="johnsmith@example.com"]'
STUDY_P1_NEXT = 'xpath://div[@class="create-new-patient-body-right"]//button[contains(@class, "ant-btn-primary")]'
STUDY_P2_DEVICETYPE = 'xpath://div[@class="create-new-patient-body-right"]//input[@class="ant-radio-input"]/..'
STUDY_P2_DEVICE_BIODIRECT = 'name:isUseBiodirect'
STUDY_P2_DIVICEBOX = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[1]'
STUDY_P2_INTERPRETPHYSICIAN = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[2]//input'
STUDY_P2_REFERPHYSICIAN = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[3]//input'
STUDY_P2_STUDYTYPE = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[4]//input'
STUDY_P2_STUDYTYPE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
STUDY_P2_DURATION = 'xpath://div[@class="create-new-patient-body-right"]//input[@placeholder="Enter study duration"]'
STUDY_P2_PATIENTREVISITDATE = 'xpath://div[@class="create-new-patient-body-right"]//div[@class="ant-picker-input"]'
STUDY_P2_PATIENTREVISITDATE_TODAY = 'xpath://div[contains(@class, "ant-picker-dropdown") and not(contains(@class, "dropdown-hidden"))]//a[contains(@class, "picker-today-btn")]'
STUDY_P2_CLINICINITIALS = 'xpath://div[@class="create-new-patient-body-right"]//input[@placeholder="Enter clinician initials"]'
STUDY_P2_NEXT = 'xpath://div[@class="create-new-patient-body-right"]//button[contains(@class, "ant-btn-primary")]'
STUDY_P3_PRIMARYDIAGNOSIS = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[1]//input'
STUDY_P3_PRIMARYDIAGNOSIS_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
STUDY_P3_SECONDARYDIAGNOSIS = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[2]//input'
STUDY_P3_SECONDARYDIAGNOSIS_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
STUDY_P3_MEDICATION = 'xpath://textarea[@placeholder="Enter patient medication"]'
STUDY_P3_NOTES = 'xpath://textarea[@placeholder="Enter physician amendments notes"]'
STUDY_P3_INSURANCETYPE = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[3]'
STUDY_P3_INSURANCEPROVIDER = 'xpath://input[@placeholder="Enter provider"]'
STUDY_P3_INSURANCEPREAUTHEN = 'xpath://input[@class="ant-radio-input"]/../..'
STUDY_P3_MEDIHISSYMPTOM = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[4]//input'
STUDY_P3_MEDIHISSYMPTOM_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
STUDY_P3_MEDICATIONHIS_ANSWER1 = 'xpath:(//div[@class="create-new-patient-body-right"]//div[@class="ant-select-selector"])[5]'
STUDY_P3_MEDICATIONHIS_ANSWER1_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
STUDY_P3_MEDICATIONHIS_ANSWER2 = 'xpath:(//div[@class="create-new-patient-body-right"]//div[contains(@class, "ant-radio-group")])[2]//label'
STUDY_P3_INITSTUDY = 'xpath://div[@class="create-new-patient-body-right"]//button[contains(@class, "ant-btn-primary")]'
# Study information tab
STUDYINFO_HEADER = 'xpath://div[@class="heart-mornitor-drawer"]//div[@class="main-wrapper"]//div[contains(@class, "size")]/span'
STUDYINFO_CONTENT = 'xpath://div[@class="heart-mornitor-drawer"]//div[@class="main-wrapper"]//div[contains(@class, "display-data") and contains(@class, "wrapper")]'
# Reports
REPORTS_MENU = 'xpath://div[@class="patient-details-report-wrapper"]//div[@role="tab"]'
REPORTS_MENU_ODR_TEXTSEARCH = 'xpath://input[@placeholder="Search by report ID"]'
REPORTS_MENU_ODR_HEADER = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "on-demand-table")]//thead//th[text()!=""]'
REPORTS_MENU_ODR_CONTENT = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "on-demand-table")]//tbody//td//span[not(@role)]'
REPORTS_MENU_NR_BYSTATUS = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "tabpane-active")]//input'
REPORTS_MENU_NR_BYSTATUS_OPTIONS = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "tabpane-active")]//div[@class="ant-select-item-option-content"]'
REPORTS_MENU_NR_HEADER = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "notification-table")]//thead//th'
REPORTS_MENU_NR_CONTENT = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "notification-table")]//tbody//td/div[contains(@class, "normal-cell-wrapper")]'
REPORTS_MENU_MR_BYSTATUS = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "tabpane-active")]//input'
REPORTS_MENU_MR_BYSTATUS_OPTIONS = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "tabpane-active")]//div[@class="ant-select-item-option-content"]'
REPORTS_MENU_MR_HEADER = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "monthly-table")]//thead//th'
REPORTS_MENU_MR_CONTENT = 'xpath://div[@class="patient-details-report-wrapper"]//div[contains(@class, "monthly-table")]//tbody//td/div[contains(@class, "normal-cell-wrapper")]'
# Change history
CHANGEHIST_DATA = 'xpath://div[@class="care-plan-change-history-wrapper"]//div[@class="event-log-row"]'
# Medical records
MEDRECORD_MENU = 'xpath://div[@class="medical-records-wrapper"]//div[@role="tab"]'
MEDRECORD_MENU_SAMPLEINFO = 'xpath://div[@class="medical-records-wrapper"]//div[contains(@class, "ant-tabs-tabpane-active")]//div[contains(@class, "-info-main")]'
# Daily entry
DAILYENTRY_TODAY = 'xpath://div[@class="daily-entry-wrapper"]//span[text()="Today"]'
DAILYENTRY_BACK = 'xpath://div[@class="daily-entry-wrapper"]//span[@aria-label="left"]'
DAILYENTRY_NEXT = 'xpath://div[@class="daily-entry-wrapper"]//span[@aria-label="right"]'
DAILYENTRY_MONTH = 'xpath://div[@class="daily-entry-wrapper"]//div[@class="date-name-month"]'
DAILYENTRY_YEAR = 'xpath://div[@class="daily-entry-wrapper"]//div[@class="date-name-year"]'
DAILYENTRY_DATEITEMS = 'xpath://div[@class="daily-entry-wrapper"]//div[@class="ant-picker-body"]//td[@title]'
DAILYENTRY_HEADER = 'xpath://div[@class="daily-entry-wrapper"]//div[@class="daily-entry-card-title"]'
DAILYENTRY_CONTENT = 'xpath://div[@class="daily-entry-wrapper"]//div[@class="daily-entry-card-info"]'
DAILYENTRY_CONTENTEMPTY = 'xpath://div[@class="daily-entry-wrapper"]//div[@class="daily-entry-wrapper-empty-data"]'
# Edit patient information
EDIT_EMAIL = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter patient\'s email"]'
EDIT_FIRSTNAME = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter patient\'s first name"]'
EDIT_LASTNAME = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter patient\'s last name"]'
EDIT_DOB = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Select patient\'s date of birth"]'
EDIT_DOB_TODAY = 'xpath://div[@class="edit-patient-info-page"]//div[contains(@class, "ant-picker-dropdown") and not(contains(@class, "hidden"))]//a[@class="ant-picker-today-btn"]'
EDIT_GENDER = 'xpath:(//div[@class="edit-patient-info-page"]//div[@class="ant-select-selector"])[1]'
EDIT_GENDER_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
EDIT_PHONENUMBER = 'xpath://div[@class="edit-patient-info-page"]//input[@name="phoneNumber"]'
EDIT_COUNTRY = 'xpath:(//div[@class="edit-patient-info-page"]//div[@class="ant-select-selector"])[2]'
EDIT_COUNTRY_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
EDIT_ADDRESS = 'xpath://input[@name="address"]/..//input[@type="text"]'
EDIT_ADDRESS_OPTIONS = 'xpath://div[contains(@class, "menu")]//div[contains(@class, "option") and contains(@id, "option")]'
EDIT_CITY = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter patient\'s city"]'
EDIT_STATEV1 = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter patient\'s state"]'
EDIT_STATEV2 = 'xpath:(//div[@class="edit-patient-info-page"]//div[@class="ant-select-selector"])[3]//input'
EDIT_STATEV2_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@option and @aria-selected]'
EDIT_ZIPCODE = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter zip code"]'
EDIT_HEIGHT_FT = 'xpath://span[text() = "ft"]/../../input'
EDIT_HEIGHT_IN = 'xpath://span[text() = "in"]/../../input'
EDIT_WEIGHT = 'xpath://span[text() = "lb"]/../../input'
EDIT_PAYMENTTYPE = 'xpath:(//div[@class="edit-patient-info-page"]//div[contains(@class, "ant-radio-group")])[1]//label[contains(@class, "ant-radio-wrapper")]'
EDIT_INSURANCENAMEV1 = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter patient\'s insurance name"]'
EDIT_INSURANCENAMEV2 = 'xpath:(//div[@class="edit-patient-info-page"]//div[contains(@class, "ant-select-selector")])[4]'
EDIT_INSURANCENAMEV2_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@class="ant-select-item-option-content"]'
EDIT_INSURANCEPROVINCIALBILLING = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Enter patient\'s provincial billing"]'
EDIT_INSURANCEEXPIREDATE = 'xpath://div[@class="edit-patient-info-page"]//input[@placeholder="Select patient\'s insurance expire date"]'
EDIT_INSURANCEEXPIREDATE_TODAY = 'xpath://div[@class="edit-patient-info-page"]//div[contains(@class, "ant-picker-dropdown") and not(contains(@class, "hidden"))]//a[@class="ant-picker-today-btn"]'
EDIT_SAVE = 'xpath://div[@class="edit-patient-info-page"]//button[contains(@class, "ant-btn-primary")]'
EDIT_LOADING = 'xpath://i[@class="ant-spin-dot-item"]/..'
# Time Tracking
TTK_STATUS = 'xpath://div[@class="time-tracking-wrapper"]//div[@class="ant-select-selector"]'
TTK_STATUS_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not( contains(@class, "-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
TTK_ADDNEWTIMELOG = 'xpath://div[@class="time-tracking-wrapper"]//button[contains(@class, "ant-btn-primary") and contains(@class, "btn-background-ghost")]'
TTK_HEADER = 'xpath://div[@class="time-tracking-wrapper"]//thead//th'
TTK_CONTENTS = 'xpath://div[@class="time-tracking-wrapper"]//tbody/tr[@data-row-key]/td'
TTK_CONTENT_ROW = 'xpath://div[@class="time-tracking-wrapper"]//tbody/tr[@data-row-key]/td'
OTIMETRACKING_STATUS = 'xpath://div[@class="time-tracking-wrapper"]//span[@class="ant-select-selection-search"]/..'
OTIMETRACKING_STATUS_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
# Time tracking details
TIMETRACK_FILTER = 'xpath://div[@class="time-tracking-wrapper"]//button[contains(@class, "ant-dropdown-trigger")]'
TIMETRACK_FILTER_OPTIONS = 'class:ant-checkbox-wrapper'
TIMETRACK_TOTALTIME = 'class:total-time'
TIMETRACK_DATA_HEADER = 'xpath://div[@class="time-tracking-wrapper"]//th'
TIMETRACK_DATA_CONTENT = 'xpath://div[@class="time-tracking-wrapper"]//tr[@data-row-key]//td[contains(@class, "ant-table-cell")]'
TIMETRACK_DATA_ROW = 'xpath://div[@class="time-tracking-wrapper"]//tr[@data-row-key]'
TIMETRACK_SUPERBILL = 'xpath://div[@class="time-tracking-wrapper"]/div[contains(@class, "superbill-info-card")]'
TIMETRACK_BACK = 'xpath://div[contains(@class, "left-go-back")]/button'
TIMETRACK_BILLINGWARNING = 'xpath://div[contains(@class, "modal-send-report")]//div[@class="ant-modal-content"]'
TIMETRACK_BILLINGWARNING_YES = 'xpath://div[contains(@class, "modal-send-report")]//div[@class="ant-modal-content"]//button[contains(@class, "ant-btn-primary")]'
TIMETRACK_CREATESUPERBILL = 'xpath://div[@class="time-tracking-wrapper"]//button[contains(@class, "ant-btn-primary") and not(contains(@class, "btn-background-ghost"))]'
# # Create super bill
SUPERBILL_DIAGNOSES = 'xpath:(//div[@class="create-superbill-right"]//div[contains(@class, "create-bill-select")])[1]'
SUPERBILL_DIAGNOSES_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[@option and @aria-selected]'
SUPERBILL_DIAGNOSES_ADD = 'xpath:(//div[@class="create-superbill-right"]//div[contains(@class, "create-bill-select")])[1]/..//button[contains(@class, "ant-btn-primary")]'
SUPERBILL_SERVICE = 'xpath:(//div[@class="create-superbill-right"]//div[contains(@class, "create-bill-select")])[2]'
SUPERBILL_SERVICE_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[@option and @aria-selected]/div'
SUPERBILL_SERVICE_ADD = 'xpath:(//div[@class="create-superbill-right"]//div[contains(@class, "create-bill-select")])[2]/..//button[contains(@class, "ant-btn-primary")]'
SUPERBILL_AMOUNTPAID = 'xpath://div[@class="create-superbill-right"]//div[@class="amount-paid"]//div[contains(@class, "create-bill-input")]//input'
SUPERBILL_STATUS = 'xpath://span[@aria-label="printer"]/../..//div[contains(@class, "footer-selection")]'
SUPERBILL_STATUS_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not(contains(@class, "hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
SUPERBILL_SAVE = 'xpath://div[@class="create-superbill-right"]//button[contains(@class, "save-btn")]'
# Time tracking info
TIMETRACK_EDIT = 'xpath://div[@class="time-log-drawer"]//button[contains(@class, "ant-btn-primary")]'
TIMETRACK_DELETE = 'xpath://span[text()="Delete"]/..'
TIMETRACK_DELETE_YES = 'xpath://div[@class="confirmation-layout-wrapper"]//button[contains(@class, "ant-btn-primary")]'
TIMETRACK_HEADERINF = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "open")]//div[@class="main-wrapper"]//div[contains(@class, "left-item")]'
TIMETRACK_CONTENTINF = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "open")]//div[@class="main-wrapper"]//div[contains(@class, "right-item")]'
TIMETRACK_CLOSE = 'xpath://span[@aria-label="close"]'
# # Add new time log
ATL_ACTIVITY = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//span[@class="ant-select-selection-search"])[1]//input'
ATL_ACTIVITY_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not( contains(@class, "-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
ATL_DATE = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//div[contains(@class, "datepicker")]//input[@placeholder="Select a date"]'
ATL_DATE_TODAY = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
ATL_DURATION_MM = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//input[@name="minDuration"]'
ATL_DURATION_SS = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//input[@name="secDuration"]'
ATL_NOTES = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//textarea[@placeholder="Notes..."]'
ATL_ADDMOREPARTI = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//button[contains(@class, "add-more-participant")]'
ATL_NURSEORPHISICIAN = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//span[@class="ant-select-selection-search"])[2]//input'
ATL_NURSEORPHISICIAN_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not( contains(@class, "-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
ATL_ADD = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//button[contains(@class, "ant-btn-primary")]'
# # EDIT time log
ETL_ACTIVITY = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//span[@class="ant-select-selection-search"])[1]//input'
ETL_ACTIVITY_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not( contains(@class, "-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
ETL_DATE = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//div[contains(@class, "datepicker")]//input[@placeholder="Select a date"]'
ETL_DATE_TODAY = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//div[contains(@class, "ant-picker-dropdown")]//a[contains(@class, "picker-today-btn")]'
ETL_DURATION_MM = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//input[@name="minDuration"]'
ETL_DURATION_SS = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//input[@name="secDuration"]'
ETL_NOTES = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//textarea[@placeholder="Notes..."]'
ETL_ADDMOREPARTI = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//button[contains(@class, "add-more-participant")]'
ETL_DELETEPARTI = 'xpath://span[@aria-label="delete"]/..'
ETL_NURSEORPHISICIAN = 'xpath:(//div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//span[@class="ant-select-selection-search"])[2]//input'
ETL_NURSEORPHISICIAN_OPTIONS = 'xpath://div[contains(@class, "ant-select-dropdown") and not( contains(@class, "-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
ETL_ADD = 'xpath://div[contains(@class, "ant-drawer-right") and contains(@class, "-open")]//button[contains(@class, "ant-btn-primary")]'
# Care plan condition information
CONDITIONINFO_SELECTCONDITION = 'xpath://div[@class="care-plan-diseases-info-wrapper"]//button[contains(@class, "ant-btn-primary")]'
CONDITIONINFO_DIAGNOSED = 'xpath:(//div[@class="care-plan-diseases-info-wrapper"]//div[@class="ant-select-selector"])[1]'
CONDITIONINFO_DIAGNOSED_OPTIONS = 'xpath://div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
CONDITIONINFO_AT_RISK = 'xpath:(//div[@class="care-plan-diseases-info-wrapper"]//div[@class="ant-select-selector"])[2]'
CONDITIONINFO_AT_RISK_OPTIONS = 'xpath://div[contains(@class, "select-dropdown") and not(contains(@class, "dropdown-hidden"))]//div[@aria-selected and contains(@class, "select-item-option")]'
CONDITIONINFO_ADD = 'xpath://div[@class="care-plan-diseases-info-wrapper"]//div[contains(@class, "footer-button")]//button[contains(@class, "ant-btn-primary")]'
# Care plan report consent
CONSENT_UPLOAD = 'xpath://div[@class="consent-forms-wrapper"]//input[@type="file"]'
CONSENT_PDFVIEW = 'class:pdf-viewer'
CONSENT_CONFIRMDIALOG = 'xpath://div[@class="confirmation-layout-wrapper"]'
CONSENT_VALIDATIONMSG = 'xpath://div[contains(@class, "ant-notification-notice-message")]'
# Care plan report settings
REPSETTINGS_EDITREPORT = 'xpath://div[@class="care-plan-report-settings-wrapper"]//span[@aria-label="edit"]/..'
REPSETTINGS = 'name:isReportAccessNurse'
REPSETTINGS_NOTIFREPORTTRIGGERS = 'xpath://div[@class="care-plan-report-settings-wrapper"]//div[contains(@class, "notification-report-triggers")]//button'
REPSETTINGS_NOTIFREPORTTRIGGERS_OPTIONS = 'xpath://div[contains(@class, "ant-dropdown") and not(contains(@class, "dropdown-hidden")]//ul[@role="menu"]//label[contains(@class, "ant-checkbox-wrapper")]'
