# Login page
FOOTER = 'class:login-container__footer'
# Menu
SIGNIN = 'xpath://button[contains(@class, "sign-in-btn")]'
SIGNIN_ATHENA = 'xpath://button[contains(@class, "auth-login-button")]'
OTP_CODE_INPUT = 'xpath://input[@id="athena-answer"]'
VERIFY_BUTTON_TEXT = 'xpath://span[contains(@class,"fe_c_button__text") and normalize-space()="Verify"]'

SIGNIN_CLINIC = 'xpath://button[@type="submit"]'
SIGNIN_ERROR_MSG = 'xpath://div[contains(@class, "__error-message")]'
AVATAR = 'id:avatar'
SIGNOUT = 'class:sign-out-btn'
MENU = 'class:sidebar-tab-content'
USERNAME_CLINIC = 'xpath://*[@id="username"]'
PASSWORD_CLINIC = 'xpath://*[@id="password"]'
USERNAME = 'name:username'
USERNAME_ATHENA = 'name:athena-username'
PASSWORD = 'name:password'
PASSWORD_ATHENA = 'name:athena-password'
SIGNIN_LOADING = 'selector:.ant-btn-loading-icon'
ICONSHORTCUT = 'xpath://a[@class="shortcuts-widget-item"][1]'
POPUP_VIDEO = 'xpath://div[@class="whats-new-modal"]'
POPUP_GOT_IT_VIDEO = 'xpath://button[@id="got-it-btn"]'
ERRORMESSAGE1ST = 'selector:div.error-message'
RELEASE_VERSION = 'xpath://div[@class="footer-container"]'
# AI Report
AI_REPORT_THUMBNAIL_SIZE = 'xpath://div[contains(@class,"active")]//div[@class="thumbnail-config"]//div[@class="size-config"]//button'
AI_REPORT_THUMBNAIL_OPTION = 'xpath://div[not(contains(@class,"hidden")) and contains(@class,"bottomLeft ")]//ul[contains(@class,"thumbnail-size-menu")]//li'
AI_REPORT_THUMBNAIL_CHANNEL = 'xpath://div[@class="channel-config"]//button[contains(@class,"toggle-button")]'
AI_REPORT_STRIP_BEATS_OPTION = 'xpath://button[contains(@class,"single-strip")]'
AI_REPORT_THUMBNAIL_GAIN = 'xpath://div[@class="thumbnail-config"]//div[@class="gain-config"]//button'
AI_REPORT_THUMBNAIL_HIGHPASS = 'xpath://div[@class="thumbnail-config"]//div[@class="highpass-config"]//button'
AI_REPORT_PANEL_TAB = 'xpath://div[contains(@class,"active")]//div[@id="scroll-container"]//div'
AI_REPORT_RESET_CHANGE = 'xpath://button[@id="btnResetBeatHr"]'
AI_REPORT_RESET_CHANGE_RHYTHM = 'xpath://button[@id="btnResetRhythmEvents"]'
AI_REPORT_ACTION = 'xpath://div[@class="pagination-container"]//button[contains(@class,"bulk-action-text")]'
AI_REPORT_ACTION_OPTION = 'xpath://div[@class="pagination-container"]//button[contains(@class,"bulk-action-text")]'
AI_REPORT_SAVE_BUTTON = 'xpath://div[@id="saveReportBtn"]//button'
AI_REPORT_MSG_BEAT = 'xpath://div[@class="no-cell-selected"]'
AI_REPORT_MARK_REVIEWED = 'xpath://div[contains(@class,"active")]//img[@alt="Review mark icon"]/../..'
AI_REPORT_FILTER_EVENT = 'xpath://button[@id="filterEventBtn"]'
AI_REPORT_HIDE_REVIEWED = 'xpath://div[@class="switch-review"]//button'
AI_REPORT_HIDE_REVIEWED_SUBMIT = 'xpath://div[@class="filter-popover-footer"]//button[2]'
AI_REPORT_HIDE_REVIEWED_RESET = 'xpath://div[@class="filter-popover-footer"]//button[1]'
AI_REPORT_EACH_EVENT = 'xpath://div[@id="stripEventsRhythmEvents"]//button[contains(@class,"single-strip")]'
AI_REPORT_PGN_NEXT = 'xpath://div[@class="pagination-container"]//img[@alt="Next icon"]/..'
AI_REPORT_ZOOM_TOOL = 'xpath://div[contains(@class,"active")]//div[@class="zoom-panel"]//div[@class="zoom-scale"]'
AI_REPORT_ZOOM_TOOL_MIN = 'xpath://div[contains(@class,"active")]//div[@class="zoom-panel"]//button[1]'
AI_REPORT_ZOOM_TOOL_MAX = 'xpath://div[contains(@class,"active")]//div[@class="zoom-panel"]//button[2]'
AI_REPORT_RESET_ZOOM = 'xpath://button[@id="resetZoomBtn"]'
AI_REPORT_START_DATETIME = 'xpath:(//div[contains(@class,"active")]//div[contains(@class,"select-date")]//div[contains(@class,"dropdown")]//button)[1]'
AI_REPORT_START_DATETIME_OPTION = 'xpath://div[contains(@class,"custom-dropdown-menu-body")]//button[@role="menuitem"]'
AI_REPORT_START_DATETIME_NEXT = 'xpath://div[contains(@class,"active")]//div[contains(@class,"select-date")]//button[contains(@class,"icon-btn")][2]'
AI_REPORT_START_DATETIME_PREVIOUS = 'xpath://div[contains(@class,"active")]//div[contains(@class,"select-date")]//button[contains(@class,"icon-btn")][1]'
AI_REPORT_CAPTURED_STRIPS = 'xpath://div[@class="event-attributes"]//input'

AI_REPORT_ECG_SPEED = 'xpath:(//div[contains(@class,"active")]//div[@id="ecgToolbarRow"]//button)[1]'
AI_REPORT_ECG_SPEED_OPTION = 'xpath://div[not(contains(@class,"hidden"))]/ul[@role="menu"]//span[@class="ant-dropdown-menu-title-content"]'
AI_REPORT_ECG_GAIN = 'xpath:(//div[contains(@class,"active")]//div[@id="ecgToolbarRow"]//button)[2]'
AI_REPORT_ECG_HIGH_PASS = 'xpath:(//div[contains(@class,"active")]//div[@id="ecgToolbarRow"]//button)[3]'
AI_REPORT_ECG_LOW_PASS = 'xpath:(//div[contains(@class,"active")]//div[@id="ecgToolbarRow"]//button)[4]'
AI_REPORT_ECG_SHOW_HIDE_CH1 = 'xpath:(//div[contains(@class,"active")]//div[@id="ecgToolbarRow"]//button)[5]'
AI_REPORT_ECG_SHOW_HIDE_CH2 = 'xpath:(//div[contains(@class,"active")]//div[@id="ecgToolbarRow"]//button)[6]'
AI_REPORT_ECG_SHOW_HIDE_CH3 = 'xpath:(//div[contains(@class,"active")]//div[@id="ecgToolbarRow"]//button)[7]'
AI_REPORT_ECG_BEAT_MARKER_TOOL = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerButton"]'
AI_REPORT_ECG_VIEW_ALL_STRIP = 'xpath://div[contains(@class,"active")]//button[@id="viewAllButton"]'
AI_REPORT_ECG_BEAT_MARKER_N = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerN"]'
AI_REPORT_ECG_BEAT_MARKER_S = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerS"]'
AI_REPORT_ECG_BEAT_MARKER_V = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerV"]'
AI_REPORT_ECG_BEAT_MARKER_Q = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerQ"]'
AI_REPORT_ECG_BEAT_MARKER_DELETE = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerDelete"]'
AI_REPORT_ECG_ZOOM = 'xpath://div[contains(@class,"active")]//button[@id="zoomButton"]'
AI_REPORT_ECG_HR_CHART = 'xpath://div[contains(@class,"active")]//div[@id="canvas-chart-container"]'
AI_REPORT_ECG_BEAT_CLOSE = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerClose"]'

AI_REPORT_TOTAL_PAGE = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//div[@class="relative"]//div'
AI_REPORT_PAGE = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//div[@class="relative"]//input'
AI_REPORT_CHART_SCROLLER = 'xpath://div[contains(@class,"active")]//div[@class="chart-scroller"]'
AI_REPORT_ADD_EVENT = 'xpath://div[@class="function-btn"]//button[contains(@class,"add-new-event-btn")]'
AI_REPORT_EVENT_DRAFT_STATUS = 'xpath://div[contains(@class,"active")]//*[@class="draft-btn"]//div[@class="draft-title"]'
AI_REPORT_EVENT_MARK_REVIEWED = 'xpath://div[contains(@class,"active")]//div[@class="top-right-corner"]//img'

AI_REPORT_NEW_EVENTS_OPTION = 'xpath://div[@class="ant-modal-body"]//button[contains(@class,"single-strip-event")]'
AI_REPORT_NEW_EVENTS_VIEW = 'xpath://div[@class="ant-modal-body"]//button[contains(@class,"single-strip-event")]//img[@alt="View icon"]'
AI_REPORT_NEW_EVENTS_DELETED = 'xpath://div[@class="ant-modal-body"]//button[contains(@class,"single-strip-event")]//img[@alt="Delete icon"]'
AI_REPORT_NEW_EVENTS_REMOVE = 'xpath://div[@class="modal-content"]//button[2]'
AI_REPORT_NEW_EVENTS_THUMBNAIL = 'xpath://div[@class="ant-modal-body"]//button[contains(@class,"single-strip-event")]//div[@class="bottom-left-corner"]'
AI_REPORT_THUMBNAIL_EVENTS_NO_HR = 'xpath://div[contains(@class,"active")]//div[@class="strips-img-container"]//button//div[@class="bottom-left-corner"]'
AI_REPORT_THUMBNAIL_EVENTS_SELECTED_NO_HR = 'xpath://div[contains(@class,"active")]//div[@class="strips-img-container"]//button[contains(@class,"active")]//div[@class="bottom-left-corner"]'

AI_REPORT_CAPTURE_DURATION = 'xpath:(//div[@class="capture-menu-container"]//div[contains(@class,"input ")])[1]//button'
AI_REPORT_CAPTURE_DURATION_OPTION = 'xpath://div[@class="ant-popover-inner"]//div[contains(@class,"custom-toggle-input")][1]//span[@class="content"]'
AI_REPORT_CAPTURE_CHANNEL = 'xpath:(//div[@class="capture-menu-container"]//div[contains(@class,"input ")])[2]//button'
AI_REPORT_CAPTURE_CHANNEL_OPTION = 'xpath://div[@class="ant-popover-inner"]//div[contains(@class,"custom-toggle-input")][2]//span[@class="content"]'
AI_REPORT_CAPTURE_TITLE = 'xpath://div[@id="text-input-wrapper-captureTitle-input-id"]//input[@id="captureTitle-input-id"]'
AI_REPORT_CAPTURE_COMMENT = 'xpath://textarea[@name="technicianComments"]'
AI_REPORT_CAPTURE_SUBMMIT = 'xpath://div[@class="capture-menu-container"]//button[contains(@class,"capture-btn")]'
AI_REPORT_CAPTURE = 'id:captureButton'
AI_REPORT_DELETED = 'xpath://div[contains(@class,"active")]//img[@alt="Delete icon"]/../..'
AI_REPORT_MARK_ARTIFACT = 'xpath://button[@id="btnChangeArtifactBeatHr"]'

AI_REPORT_NUMBER_EVENTS = 'xpath://div[@class="tooltip-inner"]'
# AI_REPORT_NUMBER_EVENTS_SUBTAB = 'xpath://button[contains(@class,"active")]//button[@class="options-btn"]'
AI_REPORT_NUMBER_EVENTS_SUBTAB = 'xpath://button[contains(@class,"active")]//div[@class="event-count"]'

BEAT_HR_AFIB_EVENTS = 'xpath://div[contains(@class,"active")]//button[contains(@class,"single-strip-event")]'
AI_REPORT_EVENT_STRIPS = 'xpath://div[contains(@class,"active")]//div[@class="strips-img-container"]//button'
AI_REPORT_EVENT_STRIPS_SELECTED = 'xpath://div[contains(@class,"active")]//button[contains(@class,"changed")]//div[contains(@class, "strip-right")]'
AI_REPORT_NEXT_MINUTE = 'xpath://button[@id="right-arrow-btn"]'
AI_REPORT_PREVIOUS_MINUTE = 'xpath://button[@id="left-arrow-btn"]'
AI_REPORT_NEXT_MIN_MAX_HR = 'xpath://div[@class="select-max-min-hr-date"]//button[2]'
AI_REPORT_PREVIOUS_MIN_MAX_HR = 'xpath://div[@class="select-max-min-hr-date"]//button[1]'
AI_REPORT_CAPTURE_VIEW = 'xpath:(//div[contains(@class,"active")]//div[@class="event-selected-info-content"]//button)[1]'
AI_REPORT_CAPTURE_DELETE = 'xpath://div[@class="left-part"]//button[contains(@class,"delete-button")]'
AI_REPORT_CAPTURE_CANCEL = 'xpath://div[@class="right-part"]//button[1]'
AI_REPORT_CAPTURE_DONE = 'xpath://div[@class="right-part"]//button[2]'
AI_REPORT_CAPTURE_DATETIME = 'xpath://div[@class="ai-strip-header"]'
AI_REPORT_CAPTURE_TECHNICIAN_COMMENT = 'xpath://textarea[@id="technicianInput"]'
AI_REPORT_CAPTURE_TITLE_INPUT = 'xpath://input[@id="titleInput"]'
AI_REPORT_MIN_MAX_AVG_HR = 'xpath: //div[@class="hr-info-container"]'

AI_REPORT_UNDO = 'xpath://div[@id="bt-undo-btn"]//button'
AI_REPORT_REDO = 'xpath://div[@id="bt-redo-btn"]//button'

AI_REPORT_VIEW_CAPTURED_STRIP = "xpath://div[contains(@class, 'event-selected-info-content')]//button[@class='event-selected-info-item__item-button' and text()='View']"

AI_REPORT_DISCARD_CHANGES= 'xpath://div[@class="modal-content"]//button[contains(@class, "text-btn")]'
AI_REPORT_KEEP_EDITING = 'xpath://div[@class="modal-content"]//button[contains(@class, "filled-btn")]'
AI_REPORT_BEAT_MARKER_TOOL = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerButton"]'
AI_REPORT_BEAT_MARKER_N = 'xpath://button[@id="beatMarkerN"]'
AI_REPORT_BEAT_MARKER_S = 'xpath://button[@id="beatMarkerS"]'
AI_REPORT_BEAT_MARKER_V = 'xpath://button[@id="beatMarkerV"]'
AI_REPORT_BEAT_MARKER_Q = 'xpath://button[@id="beatMarkerQ"]'
AI_REPORT_BEAT_MARKER_D = 'xpath://button[@id="beatMarkerDelete"]'
AI_REPORT_CANVAS = 'xpath://div[contains(@class,"active")]//div[@class="canvas-chart"]'

AI_REPORT_ADD_BEATS_CONTEXT_MENU = 'xpath://nav[contains(@class, "react-contextmenu-submenu")]'
AI_REPORT_ADD_BEATS_CONTEXT_MENU_N = 'xpath://div[@class="react-contextmenu-item" and text()="N"]'
AI_REPORT_ADD_BEATS_CONTEXT_MENU_S = 'xpath://div[@class="react-contextmenu-item" and text()="S"]'
AI_REPORT_ADD_BEATS_CONTEXT_MENU_V = 'xpath://div[@class="react-contextmenu-item" and text()="V"]'
AI_REPORT_ADD_BEATS_CONTEXT_MENU_Q = 'xpath://div[@class="react-contextmenu-item" and text()="Q"]'
AI_REPORT_DELETE_BEATS_CONTEXT_MENU = 'xpath://div[contains(@class, "react-contextmenu-item") and text()="Remove Beat"]'

AI_REPORT_STUDY_INFORMATION_BUTTON = 'xpath:(//button[@class="text-btn"]//div[@class="flex justify-center"])[1]'
AI_REPORT_STUDY_INFORMATION = 'xpath://div[@class="ant-drawer-wrapper-body"]//div[@class="drawer-title-container"]//span[@class="drawer-title" and text()="Study Information"]'
AI_REPORT_STATUS = 'xpath://div[@class="drawer-item"]//div[@class="study-status-container"]'
AI_REPORT_START_TIME = 'xpath:(//div[@class="drawer-item"]//div[@class="flex items-center"])[1]'
AI_REPORT_END_TIME = 'xpath: (//div[@class="drawer-item"]//div[@class="flex items-center"])[2]'
AI_REPORT_STUDY_TYPE= 'xpath: (//div[@class="drawer-item"]//div[@class="flex items-center"])[3]'
AI_REPORT_PATIENT_RETURN_VISIT = 'xpath:(//div[@class="drawer-item"]//div[@class="flex items-center"])[4]'
AI_REPORT_DEVICE_ID = 'xpath:(//div[@class="drawer-item"]//div[@class="flex items-center"])[5]'
AI_REPORT_DURATION = 'xpath:(//div[@class="drawer-item"]//div[@class="flex items-center"])[6]'
AI_REPORT_FACILITY = 'xpath:(//div[@class="drawer-item"]//div[@class="flex items-center"])[7]'
AI_REPORT_TOTAL_ARTIFACTS = 'xpath://div[@class="drawer-item"]//div[@class="total-artifact-percentage"]'
AI_REPORT_USE_ADD_ALL_AFIB_CHECKBOX = 'xpath://div[contains(@class, "custom-checkbox-container")]//label[@for="custom-checkbox-input-isUse100Afib"]'
AI_REPORT_ADD_START_DATE = 'xpath:(//div[@class="ant-picker-input"])[1]//input'
AI_REPORT_ADD_END_DATE = 'xpath:(//div[@class="ant-picker-input"])[3]//input'
AI_REPORT_ADD_START_TIME = 'xpath:(//div[@class="ant-picker-input"])[2]//input'
AI_REPORT_ADD_END_TIME = 'xpath:(//div[@class="ant-picker-input"])[4]//input'
AI_REPORT_CLOSE_TAB_INFORNATION= 'xpath:(//div[@class="ant-drawer-wrapper-body"]//button[contains(@class, "icon-btn")])[1]'
AI_REPORT_CHECKED_THE_CHECKBOX = 'xpath://input[contains(@id, "custom-checkbox-input-isUse100Afib") and contains(@class, "checked")]'

