CRAWL_DATA_GO = 'xpath://input[@id="loginbutton"]'
CRAWL_DATA_INPUT_SEARCH = 'id:searchinput'
CRAWL_DATA_SEARCH = 'id:searchdiv'
CRAWL_DATA_PATIENT_ID = 'xpath://div[@class="searchiconcontainer"]'
CRAWL_DATA_IFRAME_HEADER = 'xpath://iframe[@id="GlobalNav"]'
CRAWL_DATA_SHADOW_ROOT = 'xpath://div[@class="autostart aggressive-start-banner"]'
CRAWL_DATA_IFRAME_HOST = 'xpath://iframe[@id="GlobalWrapper"]'
CRAWL_DATA_IFRAME_CONTENT = 'xpath://frame[@id="frameContent"]'
CRAWL_DATA_IFRAME_PATIENT = 'xpath://iframe[@id="frMain"]'
CRAWL_DATA_PATIENT_FIRST_NAME = 'xpath:.//div[contains(@class,"first-name")]'
CRAWL_DATA_PATIENT_PHONE_NUMBER = 'xpath:.//div[contains(@class,"first-name")]'
CRAWL_DATA_QUICKVIEW_BUTTON = 'xpath://div[@title="Quickview"]'
CRAWL_DATA_DROP_DOWN = 'xpath://div[@data-view-classes="drop-down-popup"]//div[contains(@class, "popup-id-3")]'
CRAWL_DATA_DEMOGRAPHICS = 'xpath://div[contains(@class, "athenasubsectionheader") and contains(text(), "Demographic")]'
CRAWL_DATA_QUICKVIEW = 'xpath://div[@class="reskinpagetitle"]'
ADD_FILTER_BUTTON = 'xpath://span[contains(@class, "gs_c_filterable-list__add")]//button'
PATIENT_NAME = 'xpath://input[@id="NAME"]'
DOB = 'xpath://input[@id="DOB"]'
PHONE = 'xpath://input[@id="PHONE"]'
FIND_BUTTON = 'xpath://span[@class="fe_c_button__text fe_c_button__text--medium fe_c_button__text--primary"]'
FIND_A_PATIENT = 'xpath://h1[text()="Find a Patient"]'
PATIENT_CASE = 'xpath://a[text()="Patient Case"]'
PATIENT_ID = 'xpath://td[@data-column="ID"]'

CRAWL_DATA_PROMBLEM= 'xpath://div[contains(@class, "fe_c_accordion-item__content") and contains(@class, "fe_is-expanded")]//ul//li'
CRAWL_DATA_STATUS = 'xpath:.//div[contains(@class, "is-selected")]'
