REPORT_TABS = 'xpath://ul[contains(@class, "top-nav-tabs")]//li/a'
RELEASE_VERSION_AIREPORT = 'xpath:(//div[@class="info-row"]//div)[3]'
REPORT_SUBTABS = 'xpath://div[contains(@class, "active")]//div[contains(@class, "report-type")]//button'
FACILITY_INPUT = 'xpath://div[contains(@class, "select-facilities-select-input")]//input'
FACILITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select")]'
SEARCHBY = 'id:reports-search-by'
SEARCHBY_STUDIES = 'id:studies-search-by'
SEARCHBY_OPTIONS = 'xpath://div[@class="search-by-options-container"]//button'
SEARCHBY_STUDIES_OPTIONS = 'xpath://div[starts-with(@class, "search-by-options")]//button[contains(@class, "toggle-button")]'
TEXTSEARCH = 'xpath://div[@id="search-notification"]//input'
BYREPORT1ST = 'xpath://button[contains(text(), "Report type:")]'
BYREPORT2ST = 'xpath://div[contains(@class, "active")]//div[@class="custom-dropdown-input"]//button[contains(@class, "dropdown-toggle") and not(contains(text(), "Report type:")) and not(contains(text(), "Assignee:"))]'
BYREPORT_OPTIONS = 'xpath://div[contains(@class, "show")]//button[contains(@class, "dropdown-item")]'
BYASSIGNEE = 'xpath://button[contains(text(), "Assignee:")]'
BYASSIGNEE_OPTIONS = 'xpath://div[contains(@class, "show")]//button[contains(@class, "dropdown-item")]'
TEXTSEARCH_STUDYIDVALUES = 'xpath://div[contains(@class, "search-input-prefix__multi-value__label")]'
INTERIM_REPORTS_BYTYPE = 'xpath://div[@id="dropdow-input"]'
INTERIM_REPORTS_BYTYPE_OPTION = 'xpath://div[@id="dropdow-input"]//div[@role="menu"]//button'
INTERIM_REPORTS_TEXTSEARCH = 'xpath://input[@name="searchValue"]'
INTERIM_REPORTS_SORT_ICON = 'xpath://img[@alt="Sort icon"]'
# ==========================Pending reports============================
PENDINGRP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
PENDINGRP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
#   -> Eou
PENDINGEOU_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
PENDINGEOU_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
PENDINGEOU_CONTENT_PATIENTNAME = 'xpath://div[@class="flex items-center"]//span[@class="name"]'
PENDINGEOU_CONTENT_EDITRP = 'xpath://img[@alt="Edit report icon"]'
PENDINGEOU_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
PENDINGEOU_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
PENDINGEOU_CONTENT_PATIENT = 'xpath://button[@id="patient-name-formatter-btn"]'
PENDINGEOU_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
PENDINGEOU_PGN_NEXT = 'xpath://div[contains(@class,"active")]//div[@class="flex justify-center"]//span[text()=">"]'
#   -> Holter Eou
PENDINGHOLTEREOU_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
PENDINGHOLTEREOU_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
PENDINGHOLTEREOU_CONTENT_PATIENTNAME = 'xpath://button[@id="patient-name-formatter-btn"]'
PENDINGHOLTEREOU_CONTENT_EDITRP = 'xpath://img[@alt="Edit report icon"]'
PENDINGHOLTEREOU_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
PENDINGHOLTEREOU_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
PENDINGHOLTEREOU_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
# ==========================Ready reports============================
READYRP_ROOT = 'xpath://div[contains(@class, "active")]//div[contains(@class, "notification-list-item")]'
READYRP_HEADER1ST = 'xpath://div[contains(@class, "active")]//thead//th'
READYRP_CONTENT1ST = 'xpath://div[contains(@class, "active")]//tbody//td'
READYRP_HEADER2ST = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//span[@class="title"]'
#   -> 'notification reports'
READYNOTIFRP_ROOT = 'xpath://div[contains(@class, "active")]//div[contains(@class, "notification-list-item")]'
READYNOTIFRP_HEADER = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//span[@class="title"]'
READYNOTIFRP_CONTENT1ST = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//span[@class="name"]'  # blue content
READYNOTIFRP_CONTENT2ST = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//span[@class="normal-content"]'  # Normal content
READYNOTIFRP_CONTENT2ST_PRIORITY = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//div[contains(@class, "header-priority")]'
READYNOTIFRP_COLLAPSEICON = 'xpath:.//div[contains(@class,"last-child-border")]//div[@class="header-collapse-right"]'
READYNOTIFRP_CONTENT_REPORTTYPE = 'xpath://div[@class="notification-report-item-content"]'
READYNOTIFRP_EVENT_REPORT_HEADER = 'xpath:.//div[contains(@class,"event-list-item")]//div[@class="hidden"]/..//span[@class="title"]'
READYNOTIFRP_EVENT_REPORT_CONTENT = 'xpath:.//div[contains(@class,"event-list-item")]//div[@class="hidden"]/..//span[@class="normal-content" or @class="name"]'
READYNOTIFRP_EVENT_REPORT_ROW = 'xpath://div[text()="EVENT REPORTS"]//following::div[@class="collapse show"]'
READYNOTIFRP_EVENT_REPORT_EDIT = 'xpath://div[@class="header-collapse"]//div[text()="EVENT REPORTS"]//following::img[@alt="Edit report icon"]/..'
READYNOTIFRP_EVENT_REPORT_EVID = 'xpath://div[@class="collapse show"]//div[contains(@class,"item-header__group")][1]//span[@class="normal-content"]'
READYNOTIFRP_EVENT_ID_CHECKBOX = 'xpath://div[@class="collapse show"]//div[@class="custom-checkbox-container"]//input'
READYNOTIFRP_EVENT_DISMISS = 'xpath://button[@class="dissmis-button"]'
READYNOTIFRP_EVENT_DISMISS_CONFIRM = 'xpath:(//div[@class="modal-content"]//button)[2]'
READYNOTIFRP_CONTENT_MANAGERP = 'xpath://div[@class="header-collapse"]//div[text()="EVENT REPORTS"]//following::img[@alt="Manage study icon"]'
# READYNOTIFRP_EVENT_REPORT_EDIT = 'xpath://img[@alt="Edit report icon"]/..'
READYNOTIFRP_ASSIGN_TO_ME = 'xpath://div[contains(@class, "active")]//div[contains(@class, "notification-list-item")]//button[contains(@class,"self-assign-btn")]'

#   -> 'call required reports'
READYCALLRERP_ROOT = 'xpath://div[contains(@class, "active")]//div[contains(@class, "notification-list-item")]'
READYCALLRERP_HEADER = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//span[@class="title"]'
READYCALLRERP_CONTENT1ST = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//span[@class="name"]'  # blue content
READYCALLRERP_CONTENT2ST = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//span[@class="normal-content"]'  # Normal content
READYCALLRERP_CONTENT2ST_PRIORITY = 'xpath:(.//div[contains(@class, "item-header-left flex-row")])[1]//div[contains(@class, "header-priority")]'
READYCALLRERP_COLLAPSEICON = 'xpath:.//div[@class="header-collapse-right"]'
READYCALLRERP_CONTENT_REPORTTYPE = 'xpath://div[@class="notification-report-item-content"]'
READYCALLRERP_STUDY_ID = 'xpath:(//div[@class="notification-report-list"]//button//span)[2]'
READYCALLRERP_PATIENT_NAME = 'xpath:(//div[@class="notification-report-list"]//button//span)[1]'
READYCALLRERP_MARK_CALL_COMPLETED = 'xpath://div[contains(@class, "active")]//div[contains(@class, "item-header-right")]//button'
READYCALLRERP_MARK_SUBMIT = 'xpath://div[@class="modal-content"]//button[@id="right-id-btn"]'
READYCALLRERP_ROW = 'xpath://div[contains(@class, "item-header-left flex-row")]'
READYCALLRERP_CONTENT2 = 'xpath:(.//div[contains(@class, "item-header-left")])[1]//span[@class="normal-content"]'

#   -> interim reports
READYINTERIMRP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
READYINTERIMRP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
READYINTERIMRP_CONTENT_PATIENTNAME = 'xpath://div[@class="flex items-center"]//span[@class="name"]'
READYINTERIMRP_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
READYINTERIMRP_CONTENT_EDITICON = 'xpath://img[@alt="Edit report icon"]'
READYINTERIMRP_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
READYINTERIMRP_CONTENT_ASSIGN = 'xpath://img[@alt="Assign report icon"]'
READYINTERIMRP_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
#   -> end of use reports
READYEOURP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
READYEOURP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
READYEOURP_CONTENT_PATIENTNAME = 'xpath://button[@id="patient-name-formatter-btn"]'
READYEOURP_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
READYEOURP_CONTENT_EDITICON = 'xpath://img[@alt="Edit report icon"]'
READYEOURP_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
READYEOURP_CONTENT_ASSIGN = 'xpath://img[@alt="Assign report icon"]'
READYEOURP_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
# ==========================Sent reports============================
SENTRP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
SENTRP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
SENTRP_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
# -> Event reports
SENTEVENTRP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
SENTEVENTRP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
SENTEVENTRP_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
SENTEVENTRP_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
SENTEVENTRP_CONTENT_PATIENTNAME = 'xpath://div[@class="flex items-center"]//span[@class="name"]'
SENTEVENTRP_CONTENT_EDITICON = 'xpath://img[@alt="Edit report icon"]'
SENTEVENTRP_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
# -> Notification reports
SENTNOTIFRP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
SENTNOTIFRP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
SENTNOTIFRP_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
SENTNOTIFRP_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
SENTNOTIFRP_CONTENT_PATIENTNAME = 'xpath://div[@class="flex items-center"]//span[@class="name"]'
SENTNOTIFRP_CONTENT_EDITICON = 'xpath://img[@alt="Edit report icon"]'
SENTNOTIFRP_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
# -> interim reports
SENTINTERIMRP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
SENTINTERIMRP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
SENTINTERIMRP_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
SENTINTERIMRP_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
SENTINTERIMRP_CONTENT_PATIENTNAME = 'xpath://div[@class="flex items-center"]//span[@class="name"]'
SENTINTERIMRP_CONTENT_EDITICON = 'xpath://img[@alt="Edit report icon"]'
SENTINTERIMRP_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
SENTINTERIMRP_IMAGE_SCREENSHOT = 'xpath:(//*[@class="app-body"]//div[contains(@class,"active")])[2]'
SENTINTERIMRP_SUMMARY_TEST_SUMMARY = 'xpath://div[@class="summary-tabs-container"]//li[@class="nav-item"][1]//a'
SENTINTERIMRP_SUMMARY_TACHYCARDIA = 'xpath://div[@class="summary-tabs-container"]//li[@class="nav-item"][2]//a'
SENTINTERIMRP_SUMMARY_BRADYCARDIA = 'xpath://div[@class="summary-tabs-container"]//li[@class="nav-item"][3]//a'
SENTINTERIMRP_SUMMARY_ATRIAL_FIBRILLATION = 'xpath://div[@class="summary-tabs-container"]//li[@class="nav-item"][4]//a'
SENTINTERIMRP_SUMMARY_PAUSE = 'xpath://div[@class="summary-tabs-container"]//li[@class="nav-item"][5]//a'
SENTINTERIMRP_SUMMARY_MANUAL = 'xpath://div[@class="summary-tabs-container"]//li[@class="nav-item"][6]//a'
SENTINTERIMRP_NAV_HEADER = 'xpath://div[@class="title-block-container"]//div[@class="title-block__title"]'
SENTINTERIMRP_NAV_CONTENT = 'xpath:(//div[@class="title-block-container"]//div[contains(@class, "items-center")])'
SENTINTERIMRP_TOTAL_TIME = 'xpath://div[contains(@class,"active")]//div[@class="content-wrapper"]//following::span[@class="content"][2]'
SENTINTERIMRP_SUMMARY_MINHR = 'xpath://input[@id="hrMinMin"]'
SENTINTERIMRP_SUMMARY_MAXHR = 'xpath://input[@id="hrMinMax"]'
SENTINTERIMRP_SUMMARY_MINAVGHR = 'xpath://div[@id="text-input-wrapper-hrAVGMin"]//input'
SENTINTERIMRP_SUMMARY_MAXAVGHR = 'xpath://div[@id="text-input-wrapper-hrAVGMax"]//input'
SENTINTERIMRP_SUMMARY_MINMAXHR = 'xpath://div[@id="text-input-wrapper-hrMaxMin"]//input'
SENTINTERIMRP_SUMMARY_MAXMAXHR = 'xpath://div[@id="text-input-wrapper-hrMaxMax"]//input'
SENTINTERIMRP_SUMMARY_SAVE_REPORT = 'xpath://button[@id="saveReportBtn"]'
SENTINTERIMRP_SUMMARY_REFRESH = 'xpath://div[@class="summary-tabs-container"]//button[not(contains(@class,"hidden"))]'
SENTINTERIMRP_SUMMARY_CALCULATE = 'xpath:(//div[contains(@class,"active")]//div[@class="header-container"]//button)[1]'
SENTINTERIMRP_SUMMARY_CALCULATE_AVG_HR = 'xpath:(//div[contains(@class,"active")]//div[@class="header-container"]//button)[2]'
SENTINTERIMRP_SUMMARY_IMAGE_CALCULATE_AVG = 'xpath:(//div[contains(@class,"active")]//div[@class="header-container"]//button)[2]/../..'
SENTINTERIMRP_SUMMARY_FILTER = 'xpath://div[@class="custom-body"]//div[contains(@class,"active")]//div[@class="event-list-table-header"]//button'
SENTINTERIMRP_SUMMARY_ROW = 'xpath://div[@class="custom-body"]//div[contains(@class,"active")]//tbody//tr'
SENTINTERIMRP_SUMMARY_HEADER = 'xpath://div[@class="custom-body"]//div[contains(@class,"active")]//thead//th'
SENTINTERIMRP_SUMMARY_CONTENT = 'xpath://div[@class="custom-body"]//div[contains(@class,"active")]//tbody//td'
SENTINTERIMRP_SUMMARY_NEXT = 'xpath://div[@class="custom-body"]//div[contains(@class,"active")]//button[@id="next-page-btn"]'
SENTINTERIMRP_SUMMARY_EDIT = 'xpath://img[@alt="Event edit icon"]/..'
SENTINTERIMRP_SUMMARY_EVENT_ID = 'xpath://div[@class="custom-body"]//div[contains(@class,"active")]//tbody//td//button'
SENTINTERIMRP_SUMMARY_STRIPS_HEADER = 'xpath:.//div[@class="custom-body"]//div[@class="strip-selection-table-component"]//thead//th[position() < last() - 1]'
SENTINTERIMRP_SUMMARY_STRIPS_CONTENT = 'xpath:.//td[position() < last() - 2]'
SENTINTERIMRP_SUMMARY_STRIPS_ROW = 'xpath:.//div[@class="custom-body"]//div[@class="strip-selection-table-component"]//tbody//tr'
SENTINTERIMRP_SUMMARY_STRIPS_INCLUDE_REPORT = 'xpath://input[@name="includedReport"]'
SENTINTERIMRP_SUMMARY_STRIPS_CONTENT_WAIT = 'xpath://div[@class="custom-body"]//div[@class="strip-selection-table-component"]//tbody//td[position() < last()]'
SENTINTERIMRP_SUMMARY_STRIPS_NEXT = 'xpath://div[@class="custom-body"]//div[@class="strip-selection-table-component"]//button[@id="next-page-btn"]'
SENTINTERIMRP_SUMMARY_STRIPS_REFRESH = 'xpath://div[contains(@class,"active")]//img[@alt="Load data icon"]/..'
SENTINTERIMRP_SUMMARY_STRIPS_FILTER = 'xpath://div[contains(@class,"active")]//img[@alt="Filter icon"]/..'
SENTINTERIMRP_SUMMARY_STRIPS_EDIT = 'xpath://div[contains(@class,"active")]//div[contains(@id,"view-event-tab")]//img'
SENTINTERIMRP_SUMMARY_STRIPS_EVENT_ID = 'xpath://div[@class="custom-body"]//div[@class="strip-selection-table-component"]//tbody//td[position() < last()]//button'
SENTINTERIMRP_SUMMARY_STRIPS_ECG = 'xpath://div[contains(@class,"active")]//div[contains(@id,"view-ecg")]//img'
SENTINTERIMRP_SUMMARY_STRIPS_CONTAINER = 'xpath://div[@class="strips-container"]'
SENTINTERIMRP_SUMMARY_STRIPS_CLOSE = 'xpath://img[@class="close-img"]'
SENTINTERIMRP_SUMMARY_STRIPS_CLOSE_BUTTON = 'xpath://div[@class="close-btn-container"]//button'

# -> end of use reports
SENTEOURP_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
SENTEOURP_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
SENTEOURP_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
SENTEOURP_CONTENT_STUDIESID = 'xpath://div[contains(@class, "study-fid-item")]/button'
SENTEOURP_CONTENT_PATIENTNAME = 'xpath://button[@id="patient-name-formatter-btn"]'
SENTEOURP_CONTENT_EDITICON = 'xpath://img[@alt="Edit report icon"]'
SENTEOURP_CONTENT_MANAGERP = 'xpath://img[@alt="Manage study icon"]'
# alpha
MANAGE_STUDY = 'xpath://img[@alt="Manage study icon"]/..'
PENDINGEOU_EOU_NEW_REPORT_STATUS = 'xpath://div[contains(@class,"active")]//div[@class="ai-formater"]//span'
BEAT_TYPE_TRIP = 'xpath://div[@class="beat-type-strip-content"]'
TYPE_BEATS = 'xpath://div[@class="templates-btn-container"]//div[@class="react-contextmenu-wrapper"]'
CELL_ELEMENT = 'selector:tspan.highcharts-text-outline'
STRIP_BEAT_REPORT_OPTION = 'xpath://div[@id="stripBeatsReportSummary"]//button[contains(@class,"single-strip")]'
BEAT_CHANGE = 'xpath://div[@class="toolbar"]//button'
SAVE_BUTTON = 'xpath://div[@id="saveReportBtn"]//button'
ALPHA_PGN_NEXT = 'xpath://div[@class="pagination-container"]//img[@alt="Next icon"]/..'
TABS_MENU = 'xpath://div[@class="menu-icon-container"]//div[contains(@class,"sidebar-tab")]'
MSG_BEAT = 'xpath://div[@class="no-cell-selected"]'
TEXTSEARCH_INPUT = 'xpath://div[@id="search-notification"]//input'
MORE_ICON = 'xpath://div[@class="right-component"]//img[@alt="More icon"]/..'
STOP_AI_PROCESSING = 'xpath://div[@id="stopAiProcessingBtn"]//button'
BUTTON_OK = 'xpath:(//div[@class="modal-content"]//button[@class="filled-btn"])//span[text()="OK"]'
SIZE_CONFIG = 'xpath://div[@class="size-config"]//button'
SIZE_CONFIG_OPTION = 'xpath://ul[contains(@class,"ant-dropdown-menu")]//li'
ECG_EVENT_COUNT = 'xpath:(//div[contains(@class,"active")]//div[@id="rhythmEventTabId"]//div[@class="ant-collapse-content-box"])[1]//div[@class="react-contextmenu-wrapper"]'
ECG_BEAT_EVENT_OPTION = 'xpath://div[@id="stripEventsRhythmEvents"]//button[contains(@class,"single-strip")]'
ECG_MARK_AS_ARTIFACT = 'xpath://button[@id="beatArtifactt"]'
ECG_NO_DATA = 'xpath://div[@id="stripEventsRhythmEvents"]'
ECG_EVENT_TAB_ID = 'xpath://div[@id="rhythmEventTabId"]//div[@class="left-column-tab"]'

# PDF report
PDF_REPORT_GENERATE = 'xpath://div[@id="generatePdfReportBtn"]//button'
PDF_REPORT_VIEWER = 'xpath://div[contains(@class,"active")]//iframe[@id="pdf-viewer"]'
PDF_REPORT_UI = 'xpath://div[contains(@class,"active")]//div[@class="custom-body"]'
PDF_REPORT_EDIT_ELEMENT = 'xpath://div[@id="edit-facility-note"]//button'
PDF_REPORT_INPUT_FACILITY_NOTE = 'xpath://textarea[@name="facilityNote"]'
PDF_REPORT_INPUT_TECHNICIAN_COMMENT = 'xpath://textarea[@name="comments"]'
PDF_REPORT_SAVE_NOTE = 'xpath://div[@class="modal-content"]//button[contains(@class,"save-button")]'
PDF_REPORT_CURRENT_FACILITY_NOTES = 'xpath://div[@id="edit-facility-note"]//following::div[@class="content-container"][1]'

# loading page
LOADING_PAGE = 'xpath://div[@class="loading-page-container"]'

# MSG
MSG_STOP_AI_PROCESSSING = 'xpath:(//div[@class="modal-content"]//div[@class="custom-modal-content"])//div[contains(text(),"Stop")]'
POPUP_MODAL_CONTENT = 'xpath://div[@class="modal-content"]'
MSG_ARCHIVED_STUDY = 'xpath://div[@class="archived-study-message"]'
MSG_NO_MORE_STUDY = 'xpath://div[@id="toast-container"]//div[@class="toast-message"]'
MSG_BEAT_HR_INPUT_TITLE = 'xpath://div[@class="capture-menu-container"]//div[contains(@class,"error-message")]'

# AI report beats&hr
BEAT_HR_ARTIFACT_SUBTAB = 'xpath://div[@id="beatHrTabId"]//div[@class="left-column"]//button[contains(@class,"templates-btn") and not(contains(@class,"beat"))]'
BEAT_HR_ARTIFACT_AREA = 'xpath:(//div[@id="beatHrTabId"]//div[@class="left-column"]//button[contains(@class,"templates-btn") and not(contains(@class,"beat"))])[1]'
BEAT_HR_AFIB = 'xpath:(//div[@id="beatHrTabId"]//div[@class="left-column"]//button[contains(@class,"templates-btn") and not(contains(@class,"beat"))])[2]'
BEAT_HR_HEAT_MAP = 'xpath://div[@id="beatHrTabId"]//div[@class="left-column"]//div[@class="ant-collapse-header"]'
BEAT_HR_ADD_EVENT = 'xpath://div[@class="function-btn"]//button[contains(@class,"add-new-event-btn")]'
BEAT_HR_SELECT_THUMBNAIL = 'xpath://div[@class="thumbnail-content"]//button[contains(@class,"summary-thumbnail-item")]'
BEAT_HR_ARTIFACT_AREA_ACTIVE = 'xpath://div[@id="beatHrTabId"]//button[contains(@class,"active")]'
BEAT_HR_POPUP_GENERATE = 'xpath://div[@class="modal fade show"]//div[@class="modal-content"]'
BEAT_HR_POPUP_CLOSE = 'xpath://div[@class="modal fade show"]//div[@class="modal-content"]//button[1]'
BEAT_HR_THUMBNAIL_CHANNEL = 'xpath://div[@class="thumbnail-config"]//div[@class="channel-config"]'
BEAT_HR_THUMBNAIL_SELECT = 'xpath://div[contains(@class,"active")]//div[@class="thumbnail-config"]//div[position() > 1]'
BEAT_HR_THUMBNAIL_SIZE = 'xpath://div[contains(@class,"active")]//div[@class="thumbnail-config"]//div[@class="size-config"]//button'
BEAT_HR_THUMBNAIL_GAIN = 'xpath://div[contains(@class,"active")]//div[@class="thumbnail-config"]//div[@class="gain-config"]//button'
BEAT_HR_THUMBNAIL_HIGHPASS = 'xpath://div[contains(@class,"active")]//div[@class="thumbnail-config"]//div[@class="highpass-config"]//button'
BEAT_HR_THUMBNAIL_OPTION = 'xpath://div[not(contains(@class,"hidden")) and contains(@class,"bottomLeft ")]//ul[contains(@class,"thumbnail-size-menu")]//li'
BEAT_HR_THUMBNAIL_EVENTS = 'xpath://div[@class="strips-img-container"]//button//div[@class="bottom-left-corner"]'
BEAT_HR_NEXT = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//img[@alt="Next icon"]/..'
BEAT_HR_PREVIOUS = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//img[@alt="Previous icon"]/..'
BEAT_HR_TOTAL_PAGE = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//div[@class="relative"]//div'
BEAT_HR_ECG_SPEED = 'xpath:(//div[@id="ecgToolbarRow"]//button)[1]'
BEAT_HR_ECG_SPEED_OPTION = 'xpath://div[not(contains(@class,"hidden"))]/ul[@role="menu"]//span[@class="ant-dropdown-menu-title-content"]'
BEAT_HR_ECG_GAIN = 'xpath:(//div[@id="ecgToolbarRow"]//button)[2]'
BEAT_HR_ECG_HIGH_PASS = 'xpath:(//div[@id="ecgToolbarRow"]//button)[3]'
BEAT_HR_ECG_LOW_PASS = 'xpath:(//div[@id="ecgToolbarRow"]//button)[4]'
BEAT_HR_ECG_SHOW_HIDE_CH1 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[5]'
BEAT_HR_ECG_SHOW_HIDE_CH2 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[6]'
BEAT_HR_ECG_SHOW_HIDE_CH3 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[7]'
BEAT_HR_ECG_BEAT_MARKER_TOOL = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerButton"]'
BEAT_HR_ECG_VIEW_ALL_STRIP = 'xpath://div[contains(@class,"active")]//button[@id="viewAllButton"]'
BEAT_HR_ECG_BEAT_CLOSE = 'xpath://div[contains(@class,"active")]//button[@id="beatMarkerClose"]'
BEAT_HR_ECG_BEAT_MARKER_N = 'xpath://button[@id="beatMarkerN"]'
BEAT_HR_ECG_BEAT_MARKER_S = 'xpath://button[@id="beatMarkerS"]'
BEAT_HR_ECG_BEAT_MARKER_V = 'xpath://button[@id="beatMarkerV"]'
BEAT_HR_ECG_BEAT_MARKER_Q = 'xpath://button[@id="beatMarkerQ"]'
BEAT_HR_ECG_BEAT_MARKER_DELETE = 'xpath://button[@id="beatMarkerDelete"]'
BEAT_HR_ECG_CAPTURE = 'xpath://div[contains(@class,"active")]//button[@id="captureButton"]'
BEAT_HR_ECG_CAPTURE_SUBMMIT = 'xpath://div[@class="capture-menu-container"]//button[contains(@class,"capture-btn")]'
BEAT_HR_CANCEL = 'xpath://div[@class="footer-btn"]//button[1]'
BEAT_HR_CANCEL_ECG_EVENT = 'xpath://button[@id="rhythm-event-cancel-add-new-event"]'
BEAT_HR_SUBMIT = 'xpath://button[@id="add-event-beat-hr"]'
BEAT_HR_ADD_ECG = 'xpath://button[@id="rhythm-event-add-new-event"]'
BEAT_HR_DONE = 'xpath://button[contains(@id,"change-duration")][2]'
BEAT_HR_EVENTS_OPTION = 'xpath://div[contains(@class,"active")]//div[@class="strips-img-container"]//button'
BEAT_HR_DELETED = 'xpath://button[@id="btnDeleteBeatHr"]'
BEAT_HR_JUMP_START_TIME = 'xpath:(//div[@class="ant-modal-body"]//img[@alt="Jump to"]/..)[1]'
BEAT_HR_PICK_START_TIME = 'xpath:(//div[@class="ant-modal-body"]//img[@alt="Pick on ECG viewer"]/..)[1]'
BEAT_HR_JUMP_END_TIME = 'xpath:(//div[@class="ant-modal-body"]//img[@alt="Jump to"]/..)[2]'
BEAT_HR_PICK_END_TIME = 'xpath:(//div[@class="ant-modal-body"]//img[@alt="Pick on ECG viewer"]/..)[2]'
BEAT_HR_CHANGE_EVENT_DURATION = 'xpath://button[@id="btnChangeEventDurationBeatHr"]'
# R-R heatmap
BEAT_HR_HEATMAP_OPTION = 'xpath://div[@class="templates-btn-container"]//button[contains(@class,"active")]//button[@class="options-btn"]'
BEAT_HR_HEATMAP_REVIEWED = 'xpath://div[contains(@class,"active")]//div[@class="react-contextmenu-item"][1]'
BEAT_HR_HEATMAP_UNREVIEWED = 'xpath://div[contains(@class,"active")]//div[@class="react-contextmenu-item"][2]'
BEAT_HR_HEATMAP_COMPLETE_REVIEW = 'xpath://div[contains(@class,"active")]//button[contains(@class,"active")]//img[@alt="Complete review icon"]'
BEAT_HR_HEATMAP_ARROW = 'xpath://div[@class="column-content"]//img[@alt="arrow icon"]'
BEAT_HR_HEATMAP_NUMBER_CELL = 'xpath://div[contains(@class,"active")]//div[@class="header-chart"]//div[@class="selected"]'
BEAT_HR_HEATMAP_NUMBER_BEAT = 'xpath://div[contains(@class,"active")]//div[@class="header-chart"]//div[@class="beats"]'
BEAT_HR_HEATMAP_STRIP_BEATS_OPTION = 'xpath://button[contains(@class,"single-strip")]'
BEAT_HR_HEATMAP_STRIP_BEATS = 'xpath://div[@id="stripBeatsBeatHr"]//img'
BEAT_HR_HEATMAP_ECG_VIEWER = 'xpath://div[contains(@class,"active")]//div[@id="tooltipBeatHr"]'
BEAT_HR_HEATMAP_THUMBNAIL_ACTIVE = 'xpath://div[contains(@class,"active")]//div[@class="channel-config"]//button[contains(@class,"active")]'
BEAT_HR_HEATMAP_THUMBNAIL_OPTION = 'xpath://div[contains(@class,"active")]//div[@class="channel-config"]//button'
BEAT_HR_HEATMAP_THUMBNAIL_ACTIVE_TEXT = 'xpath://div[contains(@class,"active")]//div[@class="channel-config"]//button[contains(@class,"active")]//span'
BEAT_HR_HEATMAP_THUMBNAIL_NUMBER_CHANNEL = 'xpath://button[contains(@class, "single-strip") and contains(@class, "--active")]//*//*[local-name() = "path" and @stroke="#1D2F47"]'
BEAT_HR_HEATMAP_TOOLTIP_INFOR = 'xpath://div[@class="tooltip-wrapper"]//div[position() < last()]'
BEAT_HR_HEATMAP_PAGE_ACTIONS = 'xpath://button[contains(@class, "bulk-action-text") and not(contains(@class, "by-cell"))]'
BEAT_HR_HEATMAP_ALL_BEATS_ACTIONS = 'xpath://button[contains(@class, "by-cell")]'
BEAT_HR_HEATMAP_ACTION_OPTION = 'xpath://li[@role="menuitem"]//div[@class="item-label"]'
BEAT_HR_HEATMAP_ACTION_SELETED = 'xpath://label[contains(@class,"checked")]//div[@class="bulk-action-item"]//div'
BEAT_HR_HEATMAP_ECG_VIEWER_MESSAGE = 'xpath://div[@class="ecg-viewer-container"]'
# BEAT_HR_HEATMAP_ACTION_SELETED_HEADER = 'xpath://ul[contains(@class,"bulk-action-menu")]//li//label[contains(@class,"checked")]//div[@class="item-label"]'
# BEAT_HR_HEATMAP_ACTION_SELETED_CONTENT = 'xpath://ul[contains(@class,"bulk-action-menu")]//li//label[contains(@class,"checked")]//div[@class="item-hotkey"]'

BEAT_HR_HEADER_CH1 = 'xpath://div[contains(@class,"active")]//div[@class="channel-config"]//button[1]'
BEAT_HR_HEADER_CH2 = 'xpath://div[contains(@class,"active")]//div[@class="channel-config"]//button[2]'
BEAT_HR_HEADER_CH3 = 'xpath://div[contains(@class,"active")]//div[@class="channel-config"]//button[3]'
BEAT_HR_HEADER_AI = 'xpath://div[contains(@class,"active")]//div[@class="channel-config"]//button[4]'
BEAT_HR_HEATMAP_BEATS_CHANGE = 'xpath://div[contains(@class,"active")]//button//div[@class="top-left-corner"]'
BEAT_HR_HEATMAP_BEATS_OPTION = 'xpath://div[contains(@class,"active")]//div[@id="stripBeatsBeatHr"]//button//following-sibling::div[position() < last() - 1]'
BEAT_HR_HEATMAP_BEATS_SELECTED = 'xpath://button[contains(@class, "single-strip-beat") and contains(@class, "--active")]'
BEAT_HR_ARTIFACT_SELECTED = 'xpath://div[contains(@class,"active")]//button[contains(@class,"changed")]//div[@class="strip-right"]'
BEAT_HR_ARTIFACT_CANVAS = 'xpath://div[contains(@class,"active")]//div[@class="canvas-chart"]'
BEAT_HR_ARTIFACT_ENDTIME_MESSAGE_DATE = 'xpath:(//div[@class="time-input-row"]//div[contains(@class,"error-message")])[1]'
BEAT_HR_ARTIFACT_ENDTIME_MESSAGE_TIME = 'xpath:(//div[@class="time-input-row"]//div[contains(@class,"error-message")])[2]'
BEAT_HR_ARTIFACT_STARTTIME_MESSAGE_DATE = 'xpath:(//div[@class="time-input-row"]//div[contains(@class,"error-message")])[1]'
BEAT_HR_ARTIFACT_STARTTIME_MESSAGE_TIME = 'xpath:(//div[@class="time-input-row"]//div[contains(@class,"error-message")])[2]'
BEAT_HR_ARTIFACT_NEW_EVENT_OPTION = 'xpath://div[@class="ant-modal-body"]//button[contains(@class,"single-strip-event")]'
BEAT_HR_ARTIFACT_DELETED = 'xpath://div[@class="ant-modal-body"]//button[contains(@class,"single-strip-event")]//img[@alt="Delete icon"]'
BEAT_HR_ARTIFACT_VIEW = 'xpath://div[@class="ant-modal-body"]//button[contains(@class,"single-strip-event")]//img[@alt="View icon"]'
BEAT_HR_ARTIFACT_CLOSE = 'xpath://div[@class="footer-btn"]//button[contains(@class,"single-btn")]'
BEAT_HR_ARTIFACT_REMOVE = 'xpath://div[@class="modal-content"]//button[2]'
BEAT_HR_ARTIFACT_NUMBER_EVENT_NEW = 'xpath://div[@class="draft-btn"]//span[contains(@class,"badge")]'
BEAT_HR_ARTIFACT_ENDTIME_INPUT_DATE = 'xpath:(//div[@class="time-input-row"]//input)[3]'
BEAT_HR_ARTIFACT_ENDTIME_INPUT_TIME = 'xpath:(//div[@class="time-input-row"]//input)[4]'
BEAT_HR_ARTIFACT_STARTTIME_INPUT_DATE = 'xpath:(//div[@class="time-input-row"]//input)[1]'
BEAT_HR_ARTIFACT_STARTTIME_INPUT_TIME = 'xpath:(//div[@class="time-input-row"]//input)[2]'
BEAT_HR_ARTIFACT_EVENT_HEADER = 'xpath://div[contains(@class,"active")]//div[@class="event-selected-info-content"]//div[@class="event-selected-info-item"]//div[contains(@class,"title")]'
BEAT_HR_ARTIFACT_EVENT_CONTENT = 'xpath://div[contains(@class,"active")]//div[@class="event-selected-info-content"]//div[@class="event-selected-info-item"]//div[contains(@class,"value")]'
BEAT_HR_ARTIFACT_RESET_CHANGE = 'xpath://button[@id="btnResetBeatHr"]'
BEAT_HR_ARTIFACT_EVENT_ROOT = 'xpath://div[@class="event-selected-info-content"]//div[@class="event-selected-info-item"]'
BEAT_HR_ARTIFACT_PAGE_PANEL = 'xpath://div[@class="event-selected-info-content"]'
BEAT_HR_ARTIFACT_PANEL_TAB = 'xpath://div[@id="scroll-container"]//div'
BEAT_HR_ARTIFACT_TECHNICIAN_INPUT = 'xpath://textarea[@name="technicianComments"]'
BEAT_HR_ARTIFACT_TITLE_INPUT = 'xpath://input[@name="captureTitle"]'
BEAT_HR_ARTIFACT_HR_CHART = 'xpath://div[contains(@class,"active")]//div[@class="hr-chart-wrapper"]'
BEAT_HR_ARTIFACT_CHECKBOX_REVIEWED = 'xpath://div[contains(@class,"active")]//div[@class="reviewed"]//input[@name="reviewedColumn"]'
BEAT_HR_ARTIFACT_ZOOM = 'xpath://div[contains(@class,"active")]//button[@id="zoomButton"]'

# HR summary
BEAT_HR_HR_SUMMARY = 'xpath:(//div[@id="beatHrTabId"]//div[@class="left-column"]//button[contains(@class,"templates-btn") and not(contains(@class,"beat"))])[3]'
BEAT_HR_SUMMARY_THUMBNAIL = 'xpath://div[@class="mct-daily-summary-thumbnail"]//button[contains(@class,"summary-thumbnail-item")]'
BEAT_HR_SUMMARY_THUMBNAIL_ACTIVE = 'xpath://div[@class="mct-daily-summary-thumbnail"]//button[contains(@class,"summary-thumbnail-item") and contains(@class,"active")]'
BEAT_HR_SUMMARY_THUMBNAIL_OPTION = 'xpath://div[@class="mct-daily-summary-thumbnail"]//button[contains(@class,"summary-thumbnail-item")]//div[@class="hr-info"]'
BEAT_HR_SUMMARY_MINUTE_INFO = 'xpath://div[@class="event-info-content"]//div[contains(@class,"active")]//div[@class="event-info-item"]'
BEAT_HR_SUMMARY_HEADER = 'xpath://div[@class="hrs-item"]//div[@class="hrs-title"]'
BEAT_HR_SUMMARY_CONTENT = 'xpath://div[@class="hrs-content"]//div[contains(@class, "custom-text-input")]//input'
BEAT_HR_RELOAD_PAGE = 'xpath://div[@class="modal-content"]//button'
# BEAT_HR_SUMMARY_MIN_HR = 'xpath:(//div[@class="hr-info-container"]//div[@class="hr-info-item"])[1]//button[2]'
BEAT_HR_SUMMARY_MIN_INPUT = 'xpath://input[@id="edit-hr-input-MINHR"]'
BEAT_HR_SUMMARY_MAX_INPUT = 'xpath://input[@id="edit-hr-input-MAXHR"]'
# BEAT_HR_SUMMARY_MAX_HR = 'xpath:(//div[@class="hr-info-container"]//div[@class="hr-info-item"])[3]//button[2]'
# BEAT_HR_SUMMARY_AVG_HR = 'xpath:(//div[@class="hr-info-container"]//div[@class="hr-info-item"])[2]//button[1]'
BEAT_HR_SUMMARY_AVG_INPUT = 'xpath://input[@id="edit-hr-input-AVGHR"]'
BEAT_HR_SUMMARY_SAVE = 'xpath://div[@class="hrs-btn"]//button[contains(@class, "btn-approved")]'
BEAT_HR_SUMMARY_CANCEL = 'xpath://div[@class="hrs-btn"]//button[contains(@class, "btn-cancel")]'
BEAT_HR_SUMMARY_DATETIME_HR = 'xpath://div[@class="select-max-min-hr-date"]//div'
BEAT_MIN_HR_SUMMARY_ERROR_MESSAGE = 'xpath://div[@id="text-input-wrapper-edit-hr-input-MINHR"]//div[contains(@class,"error-message")]'
BEAT_MAX_HR_SUMMARY_ERROR_MESSAGE = 'xpath://div[@id="text-input-wrapper-edit-hr-input-MAXHR"]//div[contains(@class,"error-message")]'
BEAT_AVG_HR_SUMMARY_ERROR_MESSAGE = 'xpath://div[@id="text-input-wrapper-edit-hr-input-AVGHR"]//div[contains(@class,"error-message")]'
BEAT_HR_SUMMARY_SET_AS_MINMAX = 'xpath://div[@class="right-container"]//button'
BEAT_HR_SUMMARY_SET_INPUT = 'xpath://input[@id="set-min-max-hr-value"]'
BEAT_HR_SUMMARY_SET_MIN_HR = 'xpath://div[@class="hr-input-row"]//button[1]'
BEAT_HR_SUMMARY_SET_MAX_HR = 'xpath://div[@class="hr-input-row"]//button[2]'
BEAT_HR_SUMMARY_SET_VALUE = 'xpath://button[@id="beatrh-set-min-max"]'
BEAT_HR_SUMMARY_SET_CANCEL = 'xpath://button[@id="beatrh-cancel-set-min-max"]'
# Other

STRIPS_MANAGEMENT_ZOOM_TOOL = 'xpath://div[@id="tooltipEventStripDevice"]//button[@id="zoomButton"]'
STRIPS_MANAGEMENT_AUTO_ZOOM_TOOL = 'xpath://div[@id="tooltipEventStripManagement"]//button[@id="zoomButton"]'

# AFib event
BEAT_HR_AFIB_EVENTS_PAGE = 'xpath://div[@id="beatHrTabId"]//button[@id="AFIB"]'
BEAT_HR_AFIB_EVENTS_TOTAL_PAGE = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//div[@class="relative"]//div'

#callcenter
NOTIFICATION_REPORTS = 'xpath:(//div[@class="notification-report-item-content"]//img[@alt="Edit report icon"])[1]'
NOTIFICATION_REPORTS_ROW = 'xpath:(//div[@class="event-list-item"])[1]'
NOTIFICATION_REPORTS_CREATE = 'xpath://div[contains(@class,"item-header-right")]//button[contains(@id,"notification-tooltip")]'

#bookmark
BEAT_HR_ADD_BOOKMARK = 'xpath://div[@class="function-btn"]//button[@id="bookmarkBtn"]'
BEAT_HR_BOOKMARK_CANCEL = 'xpath://button[@id="cancel-add-bookmark"]'
BEAT_HR_BOOKMARK_ADD = 'xpath://button[@id="add-bookmark"]'

# undo&redo
BEAT_HR_UNDO = 'xpath://div[@id="bt-undo-btn"]//button'
BEAT_HR_REDO = 'xpath://div[@id="bt-redo-btn"]//button'

AI_REPORT_NEXT_MINUTE = 'xpath://button[@id="right-arrow-btn"]'
AI_REPORT_PREVIOUS_MINUTE = 'xpath://button[@id="left-arrow-btn"]'
AI_REPORT_CHART_SCROLLER = 'xpath://div[contains(@class,"active")]//div[@class="chart-scroller"]'