ELEMENT_TABS_MENU = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]'
ELEMENT_SEARCH_BY_EVENT_ID = 'xpath://input[@id="searchValueId"]'
ELEMENT_STRIPS_MANAGEMENT = 'xpath://button[contains(@class,"single-strip-management-event")]'
ELEMENT_INCLUDE_REPORT = 'xpath:.//div[contains(@class,"top-content")]//div[contains(@class,"include-report")]'
ELEMENT_INCLUDE_STRIP = 'xpath:.//div[contains(@class,"top-content")]//div[contains(@class,"include-strip")]'
ELEMENT_STRIPS_COMMENT = 'xpath:.//div[contains(@class,"bottom-content")]//div[@class="thumbnail-tooltip-content"]'
ELEMENT_STRIPS_TITLE = 'xpath:.//div[contains(@class,"top-content")]//div[@class="thumbnail-tooltip-content"]'
ELEMENT_EVENT_ID = 'xpath:.//div[@class="device-event-tag"]'
ELEMENT_EVENT_TIME = 'xpath:.//div[@class="event-time"]'
ELEMENT_EVENT_VALIDITY_STATUS = 'xpath:.//div[contains(@class,"valid-tag")]'
ELEMENT_STRIPS_BOX_HEADER = 'xpath://div[@class="edit-strip-box"]//div[contains(@class,"top-row-title")]'
ELEMENT_STRIPS_BOX_TECHNICIAN = 'xpath://div[@class="edit-strip-box"]//div[@class="btm-row-title"]'
ELEMENT_STRIPS_BOX_CONTENT = 'xpath://div[@class="edit-strip-box"]//div[@class="top-row-value"]'
ELEMENT_STRIPS_BOX_TECHNICIAN_TITLE = 'xpath://div[@class="edit-strip-box"]//input[@name="title"]'
ELEMENT_STRIPS_BOX_TECHNICIAN_COMMENT = 'xpath://div[@class="edit-strip-box"]//textarea[@name="technicianComment"]'
ELEMENT_STRIPS_VALIDITY_STATUS = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//div[@class="toolbar"]//div[contains(@class,"control")]'
ELEMENT_STRIPS_VALIDITY_STATUS_OPTION = 'xpath://div[@class="strip-management-tab"]//div[@class="toolbar"]//div[contains(@class,"menu")]//div[contains(@class,"option")]'
ELEMENT_STRIPS_SIZE = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//button[contains(@class,"thumbnail-size-text")]'
ELEMENT_STRIPS_SIZE_OPTION = 'xpath://ul[@role="menu"]//span[@class="ant-dropdown-menu-title-content"]//div'
ELEMENT_STRIPS_SORT = 'xpath://div[@class="pagination-container"]//img[@alt="Sort icon"]'
ELEMENT_STRIPS_OPEN = 'xpath://div[@class="edit-strip-box"]//button'
ELEMENT_STRIPS_FILTER = 'xpath://div[@class="pagination-container"]//img[@alt="Filter icon"]'
ELEMENT_STRIPS_FILTER_VALIDITY = 'xpath:(//div[@class="modal-content"]//div[@class="dropdown"])[2]'
ELEMENT_STRIPS_FILTER_VALIDITY_OPTION = 'xpath:(//div[@class="modal-content"]//div[@role="menu"])[2]//button[@role="menuitem"]'
ELEMENT_STRIPS_FILTER_EVENT_TYPE_OPTION = 'xpath:(//div[@class="modal-content"]//div[@role="menu"])[1]//button[@role="menuitem"]'
ELEMENT_STRIPS_FILTER_EVENT_TYPE = 'xpath:(//div[@class="modal-content"]//div[@class="dropdown"])[1]'
ELEMENT_STRIPS_FILTER_SUBMIT = 'xpath:(//div[@class="modal-content"]//button[contains(@class,"filter-btn")])[2]'
ELEMENT_STRIPS_FILTER_RESET = 'xpath:(//div[@class="modal-content"]//button[contains(@class,"filter-btn")])[1]'
ELEMENT_STRIPS_STATUS_EDIT = 'xpath://div[@class="bottom-content-right"]'
ELEMENT_STRIPS_CHECKBOX_REPORT = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//input[@name="isIncludedToReport"]'
ELEMENT_STRIPS_CHECKBOX_STRIP = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//input[@name="isIncludedStrip"]'
ELEMENT_STRIPS_NUMBER = 'xpath://button[contains(@class,"templates-btn") and contains(@class,"active")]//div[@class="event-count-column"]'
ELEMENT_STRIPS_EDIT_BUTTON = 'xpath://button[contains(@class,"edit-ecg-strip-button")]'

ELEMENT_STRIPS_PAGINATION = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//div[@class="pagination-container"]//div[@class="relative"]//input'
ELEMENT_STRIPS_NEXT = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//div[@class="pagination-container"]//img[@alt="Next icon"]/..'
ELEMENT_STRIPS_PREVIOUS = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//div[@class="pagination-container"]//img[@alt="Previous icon"]/..'

ELEMENT_STRIPS_ECG_SPEED = 'xpath:(//div[@id="tooltipEventStripDevice"]//div[@id="ecgToolbarRow"]//button)[1]'
ELEMENT_STRIPS_ECG_GAIN = 'xpath:(//div[@id="tooltipEventStripDevice"]//div[@id="ecgToolbarRow"]//button)[2]'
ELEMENT_STRIPS_HIGH_PASS = 'xpath:(//div[@id="tooltipEventStripDevice"]//div[@id="ecgToolbarRow"]//button)[3]'
ELEMENT_STRIPS_LOW_PASS = 'xpath:(//div[@id="tooltipEventStripDevice"]//div[@id="ecgToolbarRow"]//button)[4]'
ELEMENT_STRIPS_ECG_OPTION = 'xpath://div[not(contains(@class,"hidden")) and contains(@class,"Left")]//ul[@role="menu"]//li'
ELEMENT_STRIPS_EDIT_HEADER = 'xpath://div[@class="ai-strip-header"]'
ELEMENT_STRIPS_FILTER_HEADER = 'xpath://div[@class="modal-content"]//span[@class="custom-modal-header"]'
ELEMENT_STRIPS_NO_DATA = 'xpath://div[@class="no-data"]'
ELEMENT_STRIPS_DELETE = 'xpath://div[@id="btnDeleteStripEvents"]//button'
ELEMENT_STRIPS_REFRESH = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//button[contains(@class,"reset-btn")]'
ELEMENT_STRIPS_HIDE_EXCLUDED = 'xpath://div[@class="strip-management-tab"]//div[@class=""]//button[@role="switch"]'
ELEMENT_STRIPS_ROOT_TYPE = 'xpath:.//div[contains(@class,"top-content")]//div[@class="thumbnail-tooltip-wrapper"]'

ELEMENT_STRIPS_ZOOM_TOOL = 'xpath://div[@id="tooltipEventStripDevice"]//button[@id="zoomButton"]'
ELEMENT_STRIPS_ECG_CHART = 'xpath://div[@id="tooltipEventStripDevice"]//div[@id="canvas-chart-container"]'

ELEMENT_AUTO_EVENTS_ZOOM_TOOL = 'xpath://div[@id="tooltipEventStripManagement"]//button[@id="zoomButton"]'
ELEMENT_AUTO_EVENTS_ECG_CHART = 'xpath://div[@id="tooltipEventStripManagement"]//div[@id="canvas-chart-container"]'

ELEMENT_AUTO_ECG_SPEED = 'xpath:(//div[@id="tooltipEventStripManagement"]//div[@id="ecgToolbarRow"]//button)[1]'
ELEMENT_AUTO_ECG_GAIN = 'xpath:(//div[@id="tooltipEventStripManagement"]//div[@id="ecgToolbarRow"]//button)[2]'
ELEMENT_AUTO_HIGH_PASS = 'xpath:(//div[@id="tooltipEventStripManagement"]//div[@id="ecgToolbarRow"]//button)[3]'
ELEMENT_AUTO_LOW_PASS = 'xpath:(//div[@id="tooltipEventStripManagement"]//div[@id="ecgToolbarRow"]//button)[4]'

# element event selected
ELEMENT_STRIPS_MANAGEMENT_SELECTED = 'xpath://button[(contains(@class,"single-strip-management-event") and contains(@class,"active")) or (contains(@class,"single-strip-management-event") and contains(@class,"selected"))]'
ELEMENT_EVENT_ID_SELECTED = 'xpath:.//button[contains(@class,"single-strip-management-event") and contains(@class,"active") or contains(@class,"selected")]//div[@class="device-event-tag"]'
ELEMENT_EVENT_VALIDITY_STATUS_SELECTED = 'xpath:.//button[contains(@class,"single-strip-management-event") and contains(@class,"active") or contains(@class,"selected")]//div[contains(@class,"valid-tag")]'
ELEMENT_STRIPS_COMMENT_SELECTED = 'xpath:.//button[contains(@class,"single-strip-management-event") and contains(@class,"active") or contains(@class,"selected")]//div[contains(@class,"bottom-content")]//div[@class="thumbnail-tooltip-content"]'
ELEMENT_EVENT_TIME_SELECTED = 'xpath:.//button[contains(@class,"single-strip-management-event") and contains(@class,"active") or contains(@class,"selected")]//div[@class="event-time"]'
ELEMENT_STRIPS_ROOT_TYPE_SELECTED = 'xpath:.//button[contains(@class,"single-strip-management-event") and contains(@class,"active") or contains(@class,"selected")]//div[contains(@class,"top-content")]//div[@class="thumbnail-tooltip-wrapper"]'
ELEMENT_INCLUDE_REPORT_SELECTED = 'xpath:.//button[contains(@class,"single-strip-management-event") and contains(@class,"active") or contains(@class,"selected")]//div[contains(@class,"top-content")]//div[contains(@class,"include-report")]'
ELEMENT_INCLUDE_STRIP_SELECTED = 'xpath:.//button[contains(@class,"single-strip-management-event") and contains(@class,"active") or contains(@class,"selected")]//div[contains(@class,"top-content")]//div[contains(@class,"include-strip")]'

ELEMENT_AUTO_EVENTS_TACHY = 'xpath://div[@id="stripManagementTabId"]//div[@id="eventCountStripEventsTACHY"]'
ELEMENT_SAVE_BUTTON = 'xpath://div[@id="saveReportBtn"]//button'
ELEMENT_AUTO_EVENTS_WAITING = 'xpath://div[@id="stripManagementTabId"]//div[@id="eventCountStripEventsMIN_HR"]'

ELEMENT_START_TIME_EDIT = 'xpath://div[@class="start-time"]//b'
ELEMENT_STRIPS_MANAGEMENT_PAGE = 'xpath://div[contains(@class,"active")]//div[@class=""]//div[@class="pagination-container"]//div[@class="relative"]//input'
ELEMENT_STRIPS_MANAGEMENT_TOTAL_PAGE = 'xpath://div[contains(@class,"active")]//div[@class=""]//div[@class="pagination-container"]//div[@class="relative"]//div'
ELEMENT_STRIPS_MANAGEMENT_SPEED = 'xpath:(//div[@id="ecgToolbarRow"]//button)[1]'
ELEMENT_STRIPS_MANAGEMENT_GAIN = 'xpath:(//div[@id="ecgToolbarRow"]//button)[2]'
ELEMENT_STRIPS_MANAGEMENT_HIGH_PASS = 'xpath:(//div[@id="ecgToolbarRow"]//button)[3]'
ELEMENT_STRIPS_MANAGEMENT_LOW_PASS = 'xpath:(//div[@id="ecgToolbarRow"]//button)[4]'
ELEMENT_STRIPS_MANAGEMENT_SHOW_HIDE_CH1 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[5]'
ELEMENT_STRIPS_MANAGEMENT_SHOW_HIDE_CH2 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[6]'
ELEMENT_STRIPS_MANAGEMENT_SHOW_HIDE_CH3 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[7]'
ELEMENT_STRIPS_MANAGEMENT_CAPTURE = 'xpath://button[@id="captureButton"]'
ELEMENT_STRIPS_MANAGEMENT_VIEW_ALL_STRIP = 'xpath://button[@id="viewAllButton"]'
ELEMENT_STRIPS_MANAGEMENT_ZOOM_TOOL = 'xpath://div[@id="tooltipEventStripManagement"]//button[@id="zoomButton"]'
ELEMENT_STRIPS_MANAGEMENT_CAPTURE_EDIT = 'xpath://button[contains(@class, "capture-btn")]'
ELEMENT_STRIPS_MANAGEMENT_DONE = 'xpath://button[@class="filled-btn"]//div[contains(@class, "justify-center")]//span[@class="name" and text()="Done"]'
ELEMENT_STRIPS_MANAGEMENT_CONFIRM = 'xpath://button[@class="filled-btn"]//div[contains(@class, "justify-center")]//span[@class="name" and text()="Confirm"]'
ELEMENT_STRIPS_MANAGEMENT_CANCEL = 'xpath://div[contains(@class, "justify-center")]//span[@class="name" and text()="Cancel"]'

ELEMENT_SAVE_TECHNICIAN_COMMENT_BUTTON = 'xpath://div[@class="edit-strip-box"]//button[@class="icon-btn --filled"]'

ELEMENT_EVENT_INCLUDE_IN_REPORT = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsnotificationEvents"]'
ELEMENT_EVENT_PATIENT_TRIGGERED = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventspatientTriggeredEvents"]'
ELEMENT_EVENT_OTHER_DEVICE = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsotherEvents"]'
ELEMENT_EVENT_AUTO_EVENTS = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsAUTO_EVENTS"]'
ELEMENT_EVENT_OTHER_AUTO = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsOTHER"]'
ELEMENT_EVENT_VE = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsVE"]'
ELEMENT_EVENT_SVE = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsSVE"]'
ELEMENT_EVENT_AFIB = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsAFIB"]'
ELEMENT_EVENT_TACHY = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsTACHY"]'
ELEMENT_EVENT_BRADY = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsBRADY"]'
ELEMENT_EVENT_PAUSE = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsPAUSE"]'
ELEMENT_EVENT_VT = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsVT"]'
ELEMENT_EVENT_SVT = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsSVT"]'
ELEMENT_EVENT_MIN_HR = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsMIN_HR"]'
ELEMENT_EVENT_MAX_HR = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsMAX_HR"]'
ELEMENT_EVENT_HB = 'xpath://div[@id="stripManagementTabId"]//button[contains(@class,"templates-btn")]//div[@id="eventCountStripEventsHB"]'

ELEMENT_EVENT_DISCLOSURE = 'xpath://button[contains(@class, "set-ecg-disclosure-btn")]//div[contains(@class, "justify-center")]//span[@class="name" and text()="Set ECG disclosure"]'