BACKICON = 'xpath://div[@class="detail-title-container"]//button[contains(@class, "back-icon-btn")]'
TABS = 'xpath://ul[starts-with(@class, "top-nav-tabs")]/li'
MOREICON = 'xpath://img[@alt="icon more"]/..'
MORE_OPTIONS = 'xpath://button[starts-with(@class, "item-more")]'
# Overview
OVV_HEADER = 'xpath://div[@class="title-block__title"]'
OVV_CONTENT = 'xpath:(//div[@class="title-block"]//div[contains(@class, "items-center")])'
# Study details
STDET_CONTENT_ROOT = 'xpath://div[contains(@class,"active")]//div[contains(@class,"flex-column")]'
STDET_CONTENT_STUDYLOGS = 'xpath://div[contains(@class,  "--has-enter-study-log")]'
STDET_CONTENT_STUDYLOGS_SAVE = 'xpath://img[@alt="Add study log icon"]/..'
STDET_CONTENT_STUDYNOTES = 'xpath://div[contains(@class,  "study-notes")]//div[@class="content-container"]'
STDET_CONTENT_STUDYNOTES_ADD = 'xpath://div[@id="edit-study-info"]//button'
STDET_CONTENT_STUDYNOTES_INPUT = 'name:studyNotes'
STDET_CONTENT_STUDYNOTES_SAVE = 'xpath://button[contains(@class, "save-button")]'
STDET_CONTENT_STUDYHISTORY = 'xpath:(//div[contains(@class,  "study-history")]//div[@class="content-container"])[1]'
STDET_CONTENT_DEVICENOTIHISTORY = 'xpath:(//div[contains(@class,  "study-history")]//div[@class="content-container"])[2]'
STDET_CONTENT_ARTIFACTTEXT = 'xpath://div[contains(@class, "--need-attention")]//div[@class="label"]'
STDET_CONTENT_ZIPFILE = 'xpath://div[contains(@class, "active")]//img[@alt="Download zip file icon"]/..'
# Reports
REPORTS_CREATERP = 'xpath://button[@id="create-report-btn"]'
REPORTS_BYTYPE = 'xpath://button[starts-with(@class, "dropdown-toggle")]'
REPORTS_BYTYPE_OPTIONS = 'xpath://div[contains(@class, "show")]//button[contains(@class, "dropdown-item")]'
REPORTS_TEXTSEARCH = 'xpath://input[@placeholder="Search by Report ID"]'
REPORTS_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
REPORTS_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
REPORTS_DATA_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
REPORTS_DATA_CONTENT_EDITICON = 'xpath://img[@alt="Edit report icon"]/..'
REPORTS_STATUS = 'xpath://div[contains(@class, "active")]//tbody//tr//td[3]'
REPORTS_TYPE = 'xpath://div[contains(@class, "active")]//tbody//tr//td[4]'
REPORTS_EDIT_EOU = 'xpath://span[text()="EoU"]//following::img[@alt="Edit report icon"][1]/..'
REPORTS_STUDY_NEXT = 'xpath://div[contains(@class,"active")]//div[@class="flex justify-center"]//span[text()=">"]'
REPORTS_VIEW_ICON = 'xpath://div[contains(@class,"action-button-row")]//button'
REPORTS_TEXT_VIEW = 'xpath://div[@class="tooltip-inner"]'

# > New/edit interim report
INTERIM_TABS = 'class:nav-item'
INTERIM_STARTDATE = 'id:startDate'
INTERIM_ENDDATE = 'id:endDate'
INTERIM_LOADDATAICON = 'xpath://button[starts-with(@class, "reset-date-range-btn")]'
INTERIM_SAVEREPORT = 'id:saveReportBtn'
INTERIM_CURRENTPRIORITY = 'xpath://div[starts-with(@class, "custom-select-input")]'
INTERIM_PRIORITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select-")]'
INTERIM_READY = 'xpath://div[@id="aborted-update-send-report-btn"]//button'
INTERIM_DISMISS = 'xpath://div[@id="aborted-reenable-dismiss-report-btn"]//button'
INTERIM_DISMISS_YES = 'class:unassign-btn'
INTERIM_REENABLE = 'id:aborted-reenable-dismiss-report-btn'
INTERIM_MARKASARTIFACT = 'id:bt-artifact'
INTERIM_MARKASARTIFACT_YES = 'xpath://button[@id="right-id-btn"]'
INTERIM_ASSIGNTOME = 'id:assign-this-report-to-me'
INTERIM_DATE_START = 'xpath://td[@aria-disabled="false"]'
INTERIM_DATE_END = 'xpath://td[@aria-disabled="false"]'
INTERIM_MARKASARTIFACT_TEXT = 'xpath://div[@class="tooltip-inner"]'
INTERIM_DATE_TIME_START = 'xpath://input[@id="startDate"]'
INTERIM_DATE_TIME_END = 'xpath://input[@id="endDate"]'
# ******** Interim > PDF Report
INTERIM_PDF_GENERATE = 'id:bt-generate'
INTERIM_PDF_UPLOAD = 'id:bt-upload'
INTERIM_PDF_DOWNLOAD = 'id:bt-download'
INTERIM_PDF_REPORTLOGS = 'class:logs-icon-btn'
IMTERIM_PDF_FACILITYNOTES = 'xpath://div[@id="edit-facility-note"]'
IMTERIM_PDF_FACILITYNOTES_INPUT = 'name:facilityNote'
IMTERIM_PDF_FACILITYNOTES_INPUT_SAVE = 'class:save-button'
IMTERIM_PDF_TECHNICIANCOMMENT = 'name:comments'
# Edit Study Information
EDITSINFO_LOWCELLSIGNAL = 'xpath:(//button[starts-with(@class, "dropdown-toggle ")])[1]'
EDITSINFO_STUDYTYPE = 'xpath://div[starts-with(@class, "custom-select-input ")]//div[contains(@class, "control")]'
EDITSINFO_STUDYDURATION = 'name:duration'
EDITSINFO_PATIENTRETURNVISIT = 'name:reportDueDate'
EDITSINFO_PREEVENTTIME = 'xpath:(//button[starts-with(@class, "dropdown-toggle ")])[2]'
EDITSINFO_POSTEVENTTIME = 'xpath:(//button[starts-with(@class, "dropdown-toggle ")])[3]'
EDITSINFO_TACHYCARDIATHESHOLD = 'name:tachycardiaThreshold'
# Events
EVENTS_CURRENTSTATUS = 'xpath:(//button[starts-with(@class, "dropdown-toggle")])[1]'
EVENTS_STATUS_OPTIONS = 'xpath://div[contains(@class, "dropdown show")]//button[@role="menuitem"]'
EVENTS_CURRENTVALITITY = 'xpath:(//button[starts-with(@class, "dropdown-toggle")])[2]'
EVENTS_VALITITY_OPTIONS = 'xpath://div[contains(@class, "dropdown show")]//button[@role="menuitem"]'
EVENTS_CURRENTTYPE = 'xpath:(//button[starts-with(@class, "dropdown-toggle")])[3]'
EVENTS_TYPE_OPTIONS = 'xpath://div[contains(@class, "dropdown show")]//button[@role="menuitem"]'
EVENTS_ADVANCED_FILTER = 'xpath://img[@alt="Filter icon"]/..'
EVENTS_ADVANCED_FILTER_STARTDATE = 'name:startSearchDate'
EVENTS_ADVANCED_FILTER_STARTTIME = 'xpath:(//input[@placeholder="Select time"])[1]'
EVENTS_ADVANCED_FILTER_ENDDATE = 'name:stopSearchDate'
EVENTS_ADVANCED_FILTER_ENDTIME = 'xpath:(//input[@placeholder="Select time"])[2]'
EVENTS_ADVANCED_FILTER_AVAILABILITY = 'xpath://div[@role="dialog"]//button[starts-with(@class, "dropdown-toggle")]'
EVENTS_ADVANCED_FILTER_AVAILABILITY_OPTIONS = 'xpath://div[contains(@class, "dropdown show")]//button[@role="menuitem"]'
EVENTS_ADVANCED_FILTER_FILTER = 'xpath://button[contains(@class, "filled-btn")]'
EVENTS_ADVANCED_FILTER_RESET = 'xpath://button[contains(@class, "reset-filter-btn")]'
EVENTS_ADVANCED_FILTER_CLOSE = 'xpath://img[@alt="Close icon"]/..'
EVENTS_SORTICON = 'xpath://img[@alt="Sort icon"]'
EVENTS_RELOADICON = 'xpath://img[@alt="Reload icon"]/..'
EVENTS_TEXTSEARCH = 'xpath://input[@placeholder="Search by Event ID "]'
EVENT_CONTENT_ROOT = 'xpath://div[@class="event-list"]//div[@id and starts-with(@class, "event-list-item")]'
EVENT_HEADER1ST = 'xpath:.//div[contains(@class, "item-header-left")]//div[contains(@class, "item-header__group") and not(contains(@class, "blue-red-line"))]//span[@class="title"]'
EVENT_HEADER2ST = 'xpath:.//div[contains(@class, "list-item-ecg-slider")]//span[@class="b"]'
EVENT_CONTENT1ST = 'xpath:.//div[starts-with(@class, "item-header-left")]//span[@class="name"]'  # Study ID
EVENT_CONTENT2ST = 'xpath:.//div[contains(@class, "item-header-left")]//div[contains(@class, "item-header__group") and not(contains(@class, "blue-red-line"))]//span[@class="normal-content"]'
EVENT_CONTENT3ST = 'xpath:.//div[contains(@class, "info-ecg__group-comment")]//span[last()]'  # Symptoms and comment
EVENT_CONTENT4ST = 'xpath:.//div[contains(@class, "item-header-left")]//div[contains(@class, "item-header__group") and (contains(@class, "blue-red-line"))]//span[@class="title"]'  # Symptoms and comment
EVENT_EDIT = 'xpath://div[contains(@class, "item-header-right")]//button[starts-with(@class, "outline-btn")]'
EVENT_BOOKMARK = 'xpath://div[contains(@class, "item-header-right")]//button[contains(@class, "back-icon-btn")]/img'
EVENT_DATA_STRIPGALLERY = 'xpath://div[@class="image-gallery-content"]'
EVENT_LOADING_MORE = 'xpath://div[@class="loading-more"]'

HEADER_CONTENT = 'xpath://span[@class="custom-title"]'
