V_MORPHOLOGIES_TEMPLATE_THUMBNAIL = 'xpath://div[@class="column-content"]//button[contains(@class,"template-preview-wrapper")]'
V_MORPHOLOGIES_TEMPLATE_THUMBNAIL_ACTIVE = 'xpath://div[@class="column-content"]//button[contains(@class,"template-preview-wrapper") and contains(@class,"active")]'
V_MORPHOLOGIES_TEMPLATE_UNCLASSIFIED = 'xpath://div[@class="column-content"]//div[@class="template-left-top-conner" and text()="Unclassified"]'
V_MORPHOLOGIES_BEATS_THUMBNAIL = 'xpath://div[contains(@class,"active")]//div[@class="strips-img-container"]//button'
# (//div[@id="beatHrTabId"]//div[@class="left-column"]//button[contains(@class,"templates-btn") and not(contains(@class,"beat"))])[1]
V_MORPHOLOGIES_EVENTS = 'xpath://div[contains(@class,"active")]//button[contains(@class,"single-strip-beat")]'

V_MORPHOLOGIES_TOTAL_PAGE = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//div[@class="relative"]//div'
V_MORPHOLOGIES_PAGE = 'xpath://div[contains(@class,"active")]//div[@class="pagination-container"]//div[@class="relative"]//input'

V_MORPHOLOGIES_TYPE_SAVE = 'xpath://button[@class="filled-btn"]'
V_MORPHOLOGIES_SWAP_TEMPLATE = 'xpath://button[@id="swapTemplateBeats"]'
V_MORPHOLOGIES_SWAP_TEMPLATE_OPTION = 'xpath://div[@class="swap-template-wrapper"]//div[@class="template-left-top-conner"]'
V_MORPHOLOGIES_SWAP = 'xpath://div[@class="swap-template-button__container"]//button'
V_MORPHOLOGIES_NUMBER_BEATS_ON_TEMPLATE = 'xpath://div[@class="column-content"]//button[contains(@class,"active")]//div[@class="bottom-content"]'
V_MORPHOLOGIES_ALL_NUMBER_BEATS = 'xpath://div[@class="column-content"]//div[@class="bottom-content"]'

V_MORPHOLOGIES_INDENTIFIER = 'xpath://div[@class="column-content"]//div[@class="template-left-top-conner"]'
V_MORPHOLOGIES_WAVEFORM = 'xpath://div[@class="column-content"]//div[@class="template-preview-box"]'
V_MORPHOLOGIES_MARK_AS_REVIEWED = 'xpath://div[@class="template-action-button"]//button[@id="btnMarkReviewBeatTemplate"]'
V_MORPHOLOGIES_ICON_IN_TEMPLATE = 'xpath://button[contains(@class,"active")]//div[contains(@class, "template-right-top-conner")]//img'
V_MORPHOLOGIES_INCLUDE_IN_REPORT = 'xpath://div[@class="template-action-button"]//button[@id="btnMarkIncludeBeatTemplate"]'
V_MORPHOLOGIES_BEAT_N = 'xpath://div[contains(@class, "beat-type-strip-content-top-container")]//button[@id="beatN"]'
V_MORPHOLOGIES_BEAT_S = 'xpath://div[contains(@class, "beat-type-strip-content-top-container")]//button[@id="beatS"]'
V_MORPHOLOGIES_BEAT_V = 'xpath://div[contains(@class, "beat-type-strip-content-top-container")]//button[@id="beatV"]'
V_MORPHOLOGIES_BEAT_Q = 'xpath://div[contains(@class, "beat-type-strip-content-top-container")]//button[@id="beatQ"]'
V_MORPHOLOGIES_DELETE_BEAT = 'xpath://div[contains(@class, "beat-type-strip-content-top-container")]//button[@id="btnDeleteBeatHr"]'
V_MORPHOLOGIES_ALL_BEATS_ACTIONS = 'xpath://div[@class="pagination-container"]//button[contains(@class, "bulk-action-text-by-cell")]'
V_MORPHOLOGIES_PAGE_ACTIONS = 'xpath://button[contains(@class, "bulk-action-text") and not(contains(@class, "by-cell"))]'

V_MORPHOLOGIES_MODAL_CONTENT = 'xpath://div[@class="custom-modal-content"]'
V_MORPHOLOGIES_MODAL_HEADER = 'xpath://div[contains(@class,"custom-modal-header")]'
V_MORPHOLOGIES_MODAL_BODY = 'xpath://div[@class="custom-modal-content"]/div[2]'
V_MORPHOLOGIES_OKAY_BUTTON = 'xpath://div[@class="modal-content"]//button[@class="outline-btn"]'

V_MORPHOLOGIES_THUMBNAIL_EVENTS = 'xpath://div[contains(@class,"active")]//div[@class="strips-img-container"]//button//div[@class="bottom-left-corner"]'
V_MORPHOLOGIES_TIME_STRIP_INFO = 'xpath://div[@class="navigator-container"]//div[@class="strip-info"]'
V_MORPHOLOGIES_BACK_TO_ECG_VIEWER_BUTTON = 'xpath://div[@class="navigator-container"]//button//img[@alt="Back icon"]'
V_MORPHOLOGIES_NEXT_TO_ECG_VIEWER_BUTTON = 'xpath://div[@class="navigator-container"]//button//img[@alt="Next icon"]'