
SIGN_IN_BUTTON = 'xpath://a[@data-testid="loginButton"]'
SEARCH_INPUT = 'xpath://input[@data-testid="SearchBox_Search_Input"]'
FIRST_RESULT = 'xpath://div[@data-testid="typeaheadResult"][1]'
SEARCH_RESULTS = 'xpath://div[@data-testid="typeaheadResult"]'
FOLLOW_BUTTON = 'xpath://div[@data-testid="placementTracking"]//span[contains(text(), "Follow")]'
VIEW_ALL_BUTTON = 'xpath://div[@data-testid="cellInnerDiv"]//span[text()="View all"]'
VERIFIED_ICON = '//button[contains(@data-testid, "UserCell")]//*[local-name()= "svg" and @data-testid="icon-verified"]'
VERIFY_USERNAME = './/span[1]'
FOLLOWING_BUTTON = 'xpath://div[@data-testid="placementTracking"]//span[contains(text(), "Following")]'
PEOPLE_TAB = 'xpath://div[@role="presentation"]//span[text()="People"]'
LIST_USER = 'xpath://button[@data-testid="UserCell"]'
PROFILE_LINK = 'xpath://a[@data-testid="AppTabBar_Profile_Link"]'
FOLLOWING_BUTTON_PROFILE = 'xpath://a//span[text()="Following"]'
MESSAGE_BUTTON = 'xpath://button[@data-testid="sendDMFromProfile"]'
X_PREMIUM_POPUP = 'xpath://div[@data-testid="sheetDialog"]'
MESSAGE_TEXTAREA = 'xpath://div[@data-testid="dmComposerTextInput"]'
SEND_BUTTON = 'xpath://button[@data-testid="dmComposerSendButton"]'
BACK_BUTTON = 'xpath://button[@data-testid="app-bar-back"]'
ACTIONS_BUTTON = 'xpath://button[@data-testid="userActions"]'
COPPY_LINK_BUTTON = 'xpath://div[@role="menuitem"]//span[contains(text(), "Copy link to profile")]'
BIO_BUTTON = 'xpath://div[@data-testid="UserDescription"]'
FIRST_USER = 'xpath://div[@data-testid="cellInnerDiv"][1]'