FACILITY_CURRENT = 'xpath://*[@class="flex items-center"]//following::div[2]'
FACILITY_SELECTIONS = 'xpath://div[@class="custom-select-facilities"]//div[@role="option"]'
TABS = 'xpath://div[@role="tablist"]//div[contains(@class, "ant-tabs-tab-btn")]/..'
SUBTABS = 'xpath://div[@class="filter-device"]//label'
SUBTABS_USED = 'xpath://div[contains(@class,"ant-tabs-tabpane-active")]//div[@class="filter-device"]//label'
BYMODEL = 'xpath://div[@class="search-options"]//div[@class="ant-select-selector"]'
BYMODEL_OPTIONS = 'xpath://div[@class="search-options"]//div[@class="rc-virtual-list"]//div[@role="option"]'
SEARCHTEXTBOX = 'xpath://div[@class="search-options"]//input[@type="text"]'
CLEARTEXTSEARCH_ICON = 'xpath://button[contains(@class, "clear-btn")]'
DEVICEIDSORT = 'xpath://div[not(contains(@class, "hidden"))]/div[@class="custom-body"]//table//th[@class="sortable"]'
BYROW = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//div[@class="custom-body"]//div[@class="ant-select-selector"]'
BYROW_OPTIONS = 'xpath://*[@class="ant-pagination-options"]//div[@role="option"]'
DEVICE_ROW = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//tr[contains(@class,"ant-table-row")]'
# Pagination
PGN_NEXT = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//div[@class="custom-body"]//*[@title="Next Page"]'
PGN_NEXT_UNUSED = 'xpath://*[text()="Unused"]//following::button[@id="next-page-btn"][2]'
PGN_PREVIOUS_UNUSED = 'xpath://*[text()="Unused"]//following::button[@id="previous-page-btn"][2]'
PGN_PREVIOUS = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//div[@class="custom-body"]//*[@title="Previous Page"]'
PGN_PAGENUM = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//div[@class="custom-body"]//*[contains(@class,"ant-pagination-item")]'
# All devices tab
ALLDV_DATA_HEADER = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//th[position()>1]'
ALLDV_DATA_ROW = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//tbody//tr[position()>1]'
ALLDV_DATA_CONTENT = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//td[contains(@class,"ant-table-cell")]'
ALLDV_DATA_CONTENT_STATUS = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//tbody//td//div[starts-with(@class, "status-circle__ite")]'
ALLDV_DATA_CONTENT_DEVICEID = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//tbody//td[1]//button'
ALLDV_DATA_CONTENT_STUDYID = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//tbody//td[3]//button'
DEVICES_ID_DATA_CONTENT = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//td[contains(@class,"ant-table-cell")][1]'
SORT_DEVICES_ID = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//th[1]'
# Lost/Inactive devices tab
INACTDV_DATA_HEADER = 'xpath://div[contains(@class, "active")]//table//th'
INACTDV_DATA_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
INACTDV_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
INACTDV_DATA_CONTENT_DEVICEID = 'xpath://div[contains(@class, "active")]//table//tbody//td[1]//button'
INACTDV_DATA_CONTENT_STUDYID = 'xpath://div[contains(@class, "active")]//table//tbody//td[3]//button'
# Unused devices
UNUSED_DATA_HEADER = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//th[@class="ant-table-cell"]'
UNUSED_DATA_ROW = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//tbody//tr'
UNUSED_DATA_CONTENT = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//tbody//td'
UNUSED_DATA_CONTENT_DEVICEID = 'xpath://div[contains(@class, "active")]/div[not(contains(@class, "hidden"))]//table//tbody//td[1]//button'
# Lost/Inactive
LOST_PGN_NEXT = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//*[@title="Next Page"]'
LOST_BYROW = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//div[@class="ant-select-selector"]'
LOST_PGN_PREVIOUS = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//*[@title="Previous Page"]'
LOST_PGN_PAGENUM = 'xpath://div[@role="tabpanel" and contains(@class,"active")]//div[not(@class="hidden")]//*[contains(@class,"ant-pagination-item")]'
# msg
NO_MORE_DEVICES = 'xpath://img[@alt="Info message icon"]/..'
