FACILITY_CURRENT = 'xpath://div[@class="custom-select-facilities"]'
TABS = 'xpath://div[@class="rma-request-tab"]//div[@role="tab"]/..'
CLEARTEXTSEARCH_ICON = 'xpath://div[@class="rma-status-search"]//span[@class="ant-input-clear-icon"]'
SEARCHBOX = 'xpath://div[@class="rma-status-search"]//input[@type="text"]'
PAGE_HEADER_RMA_DETAIL = 'xpath://span[@class="title-header"]'
# Pagination
FLEET_PAGINATION_NEXT = 'xpath://div[@class="rma-request-body"]//*[@title="Next Page"]/img'
FLEET_PAGINATION_PREVIOUS = 'xpath://div[@class="rma-request-body"]//*[@title="Previous Page"]/img'
FLEET_PAGINATION_PAGENUM = 'xpath://div[contains(@class, "active")]//li[contains(@class,"ant-pagination-item")]'
# RMA Request
RMAREQ_SORT_RMAID = 'xpath://div[@class="rma-request-body"]//*[@class="ant-table-thead"]//th[contains(@class,"ant-table-cell")][1]'
RMAREQ_SORT_RQDATE = 'xpath://div[@class="rma-request-body"]//th[@class="ant-table-cell"]//following::div[@class="ant-table-column-sorters"][1]/..'
RMAREQ_NEWRMA = 'xpath://div[contains(@class,"rma-search-row")]//button[@id="go-new-rma-btn"]'
RMAREQ_STATUS = 'xpath://div[@class="rma-status-dropdown"]//div[@class="ant-select-selector"]'
RMAREQ_STATUS_OPTIONS = 'xpath://div[@class="rma-status-dropdown"]//div[@role="option"]'
RMAREQ_SEARCHBOX = 'xpath://div[@class="rma-status-search"]//span[@class="ant-select-selection-item"]'
RMAREQ_SEARCHBOX_OPTIONS = 'xpath://div[@class="option-search"]//span[@class="ant-select-selection-item"]//following::div[@role="option"]'
RMAREQ_SEARCH_INPUT = 'xpath://div[@class="rma-status-search"]//input[@type="text"]'
RMAREQ_DATA_HEADER = 'xpath://div[@class="rma-request-body"]//th[contains(@class,"ant-table-cell")][position()>1]'
RMAREQ_DATA_CONTENT = 'xpath://div[@class="rma-request-body"]//td[contains(@class,"ant-table-cell")][position() < last()]'
RMAREQ_DATA_ROW = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]'
RMAREQ_DATA_VIEW_OR_EDIT = 'xpath://div[@class="view-more-button"]//button'
RMAREQ_ID = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]//td[1]'
RMAREQ_STATUS_DATA = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]//td[2]'
RMAREQ_FACILITY = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]//td[3]'
RMAREQ_OUT_DEVICES = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]//td[4]'
RMAREQ_IN_DEVICES = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]//td[5]'
RMAREQ_RQDATE = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]//td[6]'
RMAREQ_RTDATE = 'xpath://div[@role="tabpanel"]//div[@class="rma-request-body"]//tr[contains(@class,"ant-table-row")]//td[7]'
RMAREQ_SEARCH_BY = 'xpath://div[@class="rma-status-search"]//div[@class="option-search"]//span[@class="ant-select-selection-item"]'
RMAREQ_SEARCH_BY_OPTION = 'xpath://div[@class="rma-status-search"]//div[@class="option-search"]//div[@role="option"]'
RMAREQ_CANCEL_REQUEST = 'xpath://div[@class="right-header"]//button[1]'
RMAREQ_CANCEL_MESSAGE = 'xpath://div[@class="right-header"]'
RMAREQ_CANCEL_REQUEST_CONFIRM = 'xpath://button[@id="right-id-btn"]'
RMAREQ_SIZEPERPAGE_CURRENT = 'xpath://div[@class="rma-request-body"]//div[@aria-label="Page Size"]//div[@class="ant-select-selector"]'
RMAREQ_SIZEPERPAGE_OPTIONS = 'xpath://div[@class="rma-request-body"]//div[@aria-label="Page Size"]//div[@role="option"]'
RMAREQ_PAGINATION_BUTTONS = 'xpath://div[@class="rma-request-body"]//li[contains(@class,"ant-pagination-item")]'
# Maintenance
MTN_MODEL = 'xpath://div[contains(@class, "device-maintenance-model-dropdown")]//button[starts-with(@class, "dropdown-toggle")]'
MTN_MODEL_OPTIONS = 'xpath://div[contains(@class, "device-maintenance-model-dropdown")]//button[starts-with(@class, "dropdown-item")]'
MTN_SEARCHBOX = 'xpath://input[@placeholder="Search by Device ID"]'
MTN_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th[(position()>1) and not(@data-row-selection)]'
MTN_DATA_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
MTN_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td[(position()>1 and position()<last()) and (contains(@class, "ant-table-cell"))]'
MTN_DATA_DEVICEID = 'xpath://div[contains(@class, "active")]//tbody//td[not(contains(@class, "selection-cell"))][1]'
MTN_DATA_CHECKBOXES = 'xpath://div[contains(@class, "active")]//tbody//td[contains(@class, "selection-cell")]'
MTN_DATA_INITIATE = 'xpath://img[@alt="Initiate protect plus"]/..'
# New RMA Request
NEWRMA_FACILITY = 'xpath://div[@class="select-facility-input"]//input'
NEWRMA_FACILITY_OPTIONS = 'xpath://div[@class="select-facility-input"]//following::div[@class="ant-select-item-option-content"]'
NEWRMA_SUBMIT = 'xpath://button[@id="submit-request-new-rma-btn"]'
NEWRMA_CONFIRM = 'xpath://button[@id="right-id-btn"]'
NEWRMA_BACK = 'xpath://div[@class="top-container"]//button[contains(@class, "back-icon-btn")]'
# New RMA Request > RMA DEVICE INFORMATION
NEWRMA_DEVINFO_DEVID = 'xpath:(//div[@class="input-list-input"])[1]//input'
NEWRMA_DEVINFO_DEVID_OPTIONS = 'xpath:(//div[@class="input-list-input"])[1]//div[@class="ant-select-item-option-content"]'
NEWRMA_DEVINFO_REPLACEMENTDEVID = 'xpath://td[@class="replacement-device-id"]/div[contains(@class, "device-id-select-input")]//input'
NEWRMA_DEVINFO_REPLACEMENTDEVID_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
NEWRMA_DEVINFO_RMAREASON = 'xpath://div[@id="reason-rma-select"]//div[@class="ant-select-selector"]'
NEWRMA_DEVINFO_RMAREASON_OPTIONS = 'xpath:(//div[@id="reason-rma-select"]//div[@class="ant-select-item-option-content"])[position()>1]'
NEWRMA_DEVINFO_PATIENTIMPACT = 'xpath://td[@class="patient-impact"]//div[contains(@class, "patient-impact-input__control")]'
NEWRMA_DEVINFO_PATIENTIMPACT_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
NEWRMA_DEVINFO_EVENTDATE = 'xpath://td[@class="date-of-event"]//input[@name="dateOfEvent"]'
NEWRMA_DEVINFO_EVENTDATE_TODAY = 'xpath://div[not(contains(@class, "hidden"))]//a[@class="ant-picker-today-btn"]'
NEWRMA_DEVINFO_ADD_DEVICE = 'xpath://div[@class="submit-btn"]//button'
NEWRMA_DEVINFO_ADDMORE_DEVICE = 'xpath://div[@class="btn-add-device"]//button'
# New RMA Request > Notif email
NOTIFEMAIL = 'xpath://div[contains(@class,"multi-emails-input")]//input'
# New RMA Request > Notes
NOTES = 'xpath://textarea[@name="notes"]'
# New RMA Request > Shipping information > shipping address
SHIPADDRESS_COUNTRY = 'id:shippingCountry'
SHIPADDRESS_COUNTRY_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
SHIPADDRESS_ADDRESS = 'id:shippingAddress'
SHIPADDRESS_ADDRESS_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
SHIPADDRESS_CITY = 'id:shippingCity'
SHIPADDRESS_CITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
SHIPADDRESS_STATE = 'id:shippingState'
SHIPADDRESS_STATE_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
SHIPADDRESS_ZIPCODE = 'id:shippingZip'
SHIPADDRESS_PHONE = 'xpath://input[@id="shippingContactPhone"]'
SHIPADDRESS_EMAIL = 'xpath://input[@id="shippingContactEmail"]'
# New RMA Request > Shipping information > returning address
RETURNADDRESS_SWITCH = 'xpath://div[starts-with(@class, "shipping-information")]//div[@class="right-column"]//button[@role="switch"]'
RETURNADDRESS_COUNTRY = 'id:returningCountry'
RETURNADDRESS_COUNTRY_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
RETURNADDRESS_ADDRESS = 'id:returningAddress'
RETURNADDRESS_ADDRESS_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
RETURNADDRESS_CITY = 'id:returningCity'
RETURNADDRESS_CITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
RETURNADDRESS_STATE = 'id:returningState'
RETURNADDRESS_STATE_OPTIONS = 'xpath://div[starts-with(@id, "react-select") and contains(@class, "option")]'
RETURNADDRESS_ZIP = 'id:returningZip'
RETURNADDRESS_PHONE = 'id:returningContactPhone'
RETURNADDRESS_EMAIL = 'id:returningContactEmail'
# RMA DETAILS
RMADET_OVERVIEW_HEADER = 'xpath://div[@class="title-block__title"]'
RMADET_OVERVIEW_CONTENT = 'xpath://div[@class="title-block__content"]'
RMADET_CURRENTRMASTATUS = 'xpath://div[@class="main-container"]//div[@class="right-header"]'
RMADET_TABS = 'xpath://div[@role="tablist"]//div[@role="tab"]/..'
RMADET_DEVICEINFO_HEADER = 'xpath://div[contains(@class, "active")]//table//th'
RMADET_DEVICEINFO_CONTENT = 'xpath://div[contains(@class, "active")]//table[@class="table-device-issues"]//td[not(contains(@class, "no-data"))]'
RMADET_OTHERINFO_HEADER = 'xpath://div[contains(@class, "active")]//div[@class="other-information-content"]//span[@class="title"]'
RMADET_OTHERINFO_CONTENT = 'xpath://div[contains(@class, "active")]//div[@class="other-information-content"]//span[@class="description"]'
RMADET_SHIPPINGINFO_HEADER = 'xpath://div[contains(@class, "active")]//div[@class="shipping-title" or @class="returning-title"]'
RMADET_SHIPPINGINFO_SHIPADDR_HEADER = 'xpath://div[contains(@class, "active")]//div[@class="shipping-row"]//div[@class="title"]'
RMADET_SHIPPINGINFO_SHIPADDR_CONTENT = 'xpath://div[contains(@class, "active")]//div[@class="shipping-row"]//div[@class="description"]'
RMADET_SHIPPINGINFO_RETURNADDR_HEADER = 'xpath://div[contains(@class, "active")]//div[@class="returning-row"]//div[@class="title"]'
RMADET_SHIPPINGINFO_RETURNADDR_CONTENT = 'xpath://div[contains(@class, "active")]//div[@class="returning-row"]//div[@class="description"]'
RMADET_SHIPPINGINFO_TRACKING_INFO = 'xpath://div[contains(@class, "active")]//div[starts-with(@class, "tracking-information")]/div[position() != 1]'
# #  Pending
RMADET_PENDING_DEVICEINFO_HEADER = 'xpath://div[@id="table-device-infor"]//table//th'
RMADET_PENDING_DEVICEINFO_CONTENT = 'xpath://div[@id="table-device-infor"]//table//td'
RMADET_PEND_NOTIFEMAIL = 'xpath://div[@class="multi-emails-input"]//div[@data-tag]'
RMADET_PEND_SHIPPINGADDRESS_HEADER = 'xpath://div[@class="left-column"]//div[@class="AWcpM2jDNdwTURVYIY6D"]'
RMADET_PEND_SHIPPINGADDRESS_COUNTRY = 'xpath://input[@id = "shippingCountry"]/../../..'
RMADET_PEND_SHIPPINGADDRESS_ADDRESS = 'xpath://input[@id = "shippingAddress"]'
RMADET_PEND_SHIPPINGADDRESS_CITY = 'xpath://input[@id = "shippingCity"]'
RMADET_PEND_SHIPPINGADDRESS_STATE = 'xpath://input[@id="shippingState"]//following::span[1]'
RMADET_PEND_SHIPPINGADDRESS_ZIP = 'id:shippingZip'
RMADET_PEND_SHIPPINGADDRESS_PHONE = 'id:shippingContactPhone'
RMADET_PEND_SHIPPINGADDRESS_EMAIL = 'id:shippingContactEmail'
RMADET_PEND_RETURNINGADDRESS_HEADER = 'xpath://div[@class="right-column"]//div[@class="AWcpM2jDNdwTURVYIY6D"]'
RMADET_PEND_RETURNINGADDRESS_COUNTRY = 'xpath://input[@id = "returningCountry"]/../../..'
RMADET_PEND_RETURNINGADDRESS_ADDRESS = 'xpath://input[@id = "returningAddress"]'
RMADET_PEND_RETURNINGADDRESS_CITY = 'xpath://input[@id = "returningCity"]'
RMADET_PEND_RETURNINGADDRESS_STATE = 'xpath://input[@id = "returningState"]//following::span[1]'
RMADET_PEND_RETURNINGADDRESS_ZIP = 'id:returningZip'
RMADET_PEND_RETURNINGADDRESS_PHONE = 'id:returningContactPhone'
RMADET_PEND_RETURNINGADDRESS_EMAIL = 'id:returningContactEmail'
RMADET_PEND_RETURNINGADDRESS_NOTI_EMAIL = 'xpath://div[contains(@class,"rma-detail-content__row")]//div[@data-tag="true"]'
RMADET_PEND_RETURNINGADDRESS_NOTES = 'xpath://div[@class="notes-input"]//textarea'
# msg
NO_MORE_FLEET = 'xpath://img[@alt="Info message icon"]/..'

# Waiting for return
WFRETURN_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th[(position()>1) and position() < last() -1]'
WFRETURN_DATA_HEADER_FACILITY = 'xpath://div[contains(@class, "active")]//thead//th[position() > last() -1]'
WFRETURN_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td[(position()>1 and position()<last()) and (contains(@class, "ant-table-cell"))]'
WFRETURN_SEARCH_INPUT = 'xpath://div[@class="waiting-to-return-tab"]//div[contains(@class,"search-input")]//input'
WFRETURN_SEARCH_BY = 'xpath://div[@class="waiting-to-return-tab"]//div[@class="option-search"]//div[@class="ant-select-selector"]'
WFRETURN_SEARCH_BY_OPTION = 'xpath://div[@class="waiting-to-return-tab"]//div[@class="option-search"]//div[@class="ant-select-item-option-content"]'
