DATA_ROOT = 'xpath://div[@class="body-profile"]//div[@class="drawer-body"]'
DATA_HEADER = 'xpath:.//div[@class="drawer-header"]'
DATA_CONTENT_HEADER = 'xpath:.//div[@class="drawer-content"]//div[@class="drawer-item"]/span[1]'
DATA_CONTENT_VALUE = 'xpath:.//div[@class="drawer-content"]//div[@class="drawer-item"]/span[2]'
DATA_CONTENT_FACILITY = 'xpath://div[@class="facility-list"]//div[@class="facility"]'
GENERALINFO_EDITICON = 'xpath:(//button[contains(@class, "icon-edit")])[1]'
CONTACTINFO_EDITICON = 'xpath:(//button[contains(@class, "icon-edit")])[2]'
CHANGEPWD_BUTTON = 'xpath://button[starts-with(@class, "outline-btn")]'
VERIFICATION_BUTTON = 'class:resend-verification-btn'
# General_information_popup
GENINFO_CURRENTROLE = 'xpath://div[@role="dialog" and contains(@class, "show")]//div[contains(@class, "singleValue")]'
GENINFO_FIRSTNAME = 'name:firstName'
GENINFO_LASTNAME = 'name:lastName'
GENINFO_EMAIL = 'name:email'
GENINFO_TITLE = 'name:title'
GENINFO_SAVE = 'xpath://div[@role="dialog" and contains(@class, "show")]//button[contains(@class, "save-button")]'
GENINFO_CLOSE = 'xpath://div[@role="dialog" and contains(@class, "show")]//img[@alt="Close icon"]/..'
# Contact information popup
CI_COUNTRY = 'xpath:(//div[contains(@class, "control")])[1]//input'
CI_COUNTRY_OPTIONS = 'xpath://div[starts-with(@id, "react-select-")]'
CI_ADDRESS = 'xpath:(//div[contains(@class, "control")])[2]//input'
CI_ADDRESS_OPTIONS = 'xpath://div[starts-with(@id, "react-select-")]'
CI_CITY = 'xpath:(//div[contains(@class, "control")])[3]//input'
CI_CITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select-")]'
CI_STATE1ST = 'xpath:(//div[contains(@class, "control")])[4]//input'
CI_STATE1ST_OPTIONS = 'xpath://div[starts-with(@id, "react-select-")]'
CI_STATE2ST = 'name:state'
CI_ZIPCODE = 'name:zip'
CI_DAYPHONE = 'name:phone1'
CI_NIGHTPHONE = 'name:nightPhone'
CI_FAX = 'name:fax'
CI_SAVE = 'xpath://div[@role="dialog" and contains(@class, "show")]//button[contains(@class, "save-button")]'
CI_CLOSE = 'xpath://div[@role="dialog" and contains(@class, "show")]//img[@alt="Close icon"]/..'
# Change password popup
CPW_CURRENTPASSWD = 'name:currPassword'
CPW_NEWPASSWD = 'name:newPassword'
CPW_NEWPASSWD_CONFIRM = 'name:confirmPassword'
CPW_CHANGEPWD = 'xpath://button[starts-with(@class, "filled-btn")]'
CPW_CLOSE = 'xpath://div[@role="dialog" and contains(@class, "show")]//img[@alt="Close icon"]/..'
