TABS = 'xpath://div[@role="tablist"]//div[@role="tab"]/..'
COMMON_HEADER = 'xpath://div[@class="title-block__title"]'
COMMON_CONTENT = 'xpath://div[@class="title-block__content"]'
COMMON_CONTENT_BIODIRECT = 'xpath://div[text()="Biodirect"]'
# Study details
STDET_ROOT_DATA = 'xpath://div[contains(@class, "study-details-tab")]//div[@class="multi-content"]//div[@class="row-item"]'
STDET_DATA_HEADER = 'xpath://div[contains(@class, "group-container")]//div[@class="title"]'
STDET_DATA_CONTENT_HEADER = 'xpath://div[@class="multi-content"]//div[@class="row-item"]//div[@class="label"]'
STDET_DATA_CONTENT_CONTENT = 'xpath://div[@class="multi-content"]//div[@class="row-item"]//div[@class="value"]'
STDET_DATA = 'xpath://div[contains(@class,"study-details-tab")]//div[contains(@class, "group-container")]'
STDET_DATA_HOLTER = 'xpath://div[contains(@class,"study-details-tab")]//div[@class="group-container"]'
STDET_DATA_HISTORIES = 'xpath://div[contains(@class, "info-item") and contains(@class, "study-history")]'
STDET_STUDYINFO_EDIT = 'xpath://div[contains(@class,"study-details-tab")]//div[@class="with-edit-icon"]//button'
STDET_REFPHYSICIAN_EDIT = 'xpath://button[@id="edit-study-details-btn"]'
STDET_INTPHYSICIAN_EDIT = 'xpath://div[@id="interpreting-physician"]//button'
STDET_DIAGNOSIS_EDIT = 'xpath://div[@id="diagnosis"]//button'
STDET_FLONSTTRACKING_STUDYID = 'xpath://div[contains(@class, "info-item")][2]'
# Edit STUDY INFORMATION dialog
STINFO_DIALOG_STUDYTYPE = 'xpath://div[@class="edit-study-details"]//div[@class="content"][1]//span[@class="ant-select-selection-item"]'
STINFO_DIALOG_STUDYTYPE_OPTIONS = 'xpath://div[@class="edit-study-details"]//div[@class="content"][1]//div[@class="ant-select-item-option-content"]'
STINFO_DIALOG_DURATION = 'name:duration'
STINFO_DIALOG_PRV = 'name:reportDueDate'
STINFO_DATE_ELEMENT = 'xpath://div[@class="ant-picker-body"]//td[contains(@class,"selected")]'
STINFO_DIALOG_CANCEL = 'xpath://div[@class="action"]//button[@id="cancel-btn"]'
STINFO_DIALOG_SAVE = 'xpath://div[@class="action"]//button[@id="save-btn"]'
STINFO_DIALOG_SAVE_CONFIRM = 'xpath://div[@class="footer"]//button[@id="right-id-btn"]'
STINFO_DIALOG_CANCEL_CONFIRM = 'xpath://div[@class="footer"]//button[@id="left-btn"]'
STINFO_DIALOG_STUDY_DURATION = 'xpath://input[@placeholder="Enter study duration"]'
STINFO_DIALOG_NOTI_VISIT = 'xpath:(//div[@class="content"])[1]//div[@class="right"]//img[@alt="inforOrangeIcon"]/..'
# Edit REFERRING PHYSICIAN dialog
REFPHY_DIALOG_REFERPHYSICIAN = 'xpath:(//div[@class="content"])[2]//div[@class="ant-select-selector"]'
REFPHY_DIALOG_REFERPHYSICIAN_OPTIONS = 'xpath:(//div[@class="content"])[2]//div[@class="ant-select-selector"]//following::div[@class="ant-select-item-option-content"]'
REFPHY_DIALOG_SAVE = 'xpath://div[@class="header-container"]//button[2]'
REFPHY_DIALOG_SAVE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
# Edit INTERPRETING PHYSICIAN dialog
INTERPHY_DIALOG_INTERPHYSICIAN = 'xpath:(//div[@class="content"])[3]//div[@class="ant-select-selector"]'
INTERPHY_DIALOG_INTERPHYSICIAN_OPTIONS = 'xpath:(//div[@class="content"])[3]//div[@class="ant-select-selector"]//following::div[@class="ant-select-item-option-content"]'
INTERPHY_DIALOG_SAVE = 'xpath://div[@class="header-container"]//button[2]'
INTERPHY_DIALOG_SAVE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
# Edit DIAGNOSIS dialog
DIAGNOSIS_DIALOG_PRIMARYDIAGNOSIS = 'xpath://*[text()="Primary diagnosis code"]//following::input[1]'
DIAGNOSIS_DIALOG_PRIMARYDIAGNOSIS_OPTIONS = 'xpath://*[text()="Primary diagnosis code"]//following::div[@class="ant-select-item-option-content"]'
DIAGNOSIS_DIALOG_SECONDARYDIAGNOSIS = 'xpath://*[contains(text(),"Secondary diagnosis code")]//following::input[1]'
DIAGNOSIS_DIALOG_SECONDARYDIAGNOSIS_OPTIONS = 'xpath://*[contains(text(),"Secondary diagnosis code")]//following::div[@class="ant-select-item-option-content"]'
DIAGNOSIS_DIALOG_PATIENTMEDICATION = 'xpath://*[contains(text(),"Patient medication")]//following::textarea[1]'
DIAGNOSIS_DIALOG_SAVE = 'xpath://button[contains(@class, "save-button")]'
DIAGNOSIS_DIALOG_SAVE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
DIAGNOSIS_PRIMARYDIAGNOSIS = 'xpath://div[@class="row-item"][div[@class="label"][text()="Primary diagnosis code:"]]/div[@class="value"]'
DIAGNOSIS_SECONDARYDIAGNOSIS = 'xpath://div[@class="row-item"][div[@class="label"][text()="Secondary diagnosis code:"]]/div[@class="value"]'

# Patient details
PTDET_ROOT_DATA = 'xpath://div[contains(@class, "patient-detail-tab")]//div[contains(@class,"group-container")]'
PTDET_DATA_HEADER = 'xpath://div[contains(@class, "patient-detail-tab")]//div[@class="title"]'
PTDET_DATA_CONTENT_HEADER = 'xpath://div[contains(@class, "patient-detail-tab")]//div[@class="row-item"]//div[@class="label"]'
PTDET_DATA_CONTENT_CONTENT = 'xpath://div[contains(@class, "patient-detail-tab")]//div[@class="row-item"]//div[@class="value"]'
PTDET_PATIENTINFO_EDIT = 'xpath://button[@id="edit-patient-info-btn"]'
PTDET_PATIENTCONTACT_EDIT = 'xpath://button[@id="edit-patient-contact-btn"]'
PTDET_SECONDARYCONTACT_EDIT = 'xpath://button[@id="edit-secondary-contact-btn"]'
PTDET_INSURANCE_EDIT = 'xpath://button[@id="edit-insurance-btn"]'
PTDET_MEDICALHIS_EDIT = 'xpath://button[@id="edit-medical-history-btn"]'
# Patient details > Edit PATIENT INFORMATION dialog
PINFO_PATIENTID = 'xpath:(//div[@class="list-input"]//div[contains(@class,"custom-input-wrapper")])[4]//input'
PINFO_FIRSTNAME = 'xpath:(//div[@class="list-input"]//div[contains(@class,"custom-input-wrapper")])[1]//input'
PINFO_MIDDLENAME = 'xpath:(//div[@class="list-input"]//div[contains(@class,"custom-input-wrapper")])[2]//input'
PINFO_LASTNAME = 'xpath:(//div[@class="list-input"]//div[contains(@class,"custom-input-wrapper")])[3]//input'
PINFO_DOB = 'xpath:(//div[@class="list-input"]//div[contains(@class,"custom-text-input")])[1]//input'
PINFO_GENDER = 'xpath://input[@class="ant-radio-input"]/..'
PINFO_HEIGHTFT = 'xpath:(//div[@class="list-input"]//div[contains(@class,"relative")])[1]//input'
PINFO_HEIGHTIN = 'xpath:(//div[@class="list-input"]//div[contains(@class,"relative")])[2]//input'
PINFO_WEIGHT = 'xpath:(//div[@class="list-input"]//div[contains(@class,"relative")])[3]//input'
PINFO_ETHNICITY = 'xpath:(//div[@class="list-input"]//div[contains(@class,"ant-select-selector")])'
PINFO_ETHNICITY_OPTION = 'xpath:(//div[@class="list-input"]//div[contains(@class,"ant-select-item-option-content")])'
PINFO_PACEMAKER = 'xpath:(//div[@class="list-input"]//input[@class="ant-checkbox-input"])[1]/..'
PINFO_ICD = 'xpath:(//div[@class="list-input"]//input[@class="ant-checkbox-input"])[2]/..'
PINFO_SAVE = 'xpath://button[@id="save-btn"]'
PINFO_SAVE_CONFIRM = 'xpath://button[@id="right-id-btn"]'
# Patient details > patient contact dialog
PCONTACT_COUNTRY = 'xpath:(//div[starts-with(@class, "ant-select-selector")])[1]'
PCONTACT_COUNTRY_INPUT = 'xpath:(//div[starts-with(@class, "ant-select-selector")])[1]//input'
PCONTACT_COUNTRY_OPTIONS = 'xpath:(//div[starts-with(@class, "ant-select-selector")])[1]//following::div[@class="ant-select-item-option-content"]'
PCONTACT_ADDRESS = 'xpath:(//div[starts-with(@class, "ant-select-selector")])[2]'
PCONTACT_ADDRESS_OPTIONS = 'xpath:(//div[starts-with(@class, "ant-select-selector")])[1]//following::div[@class="ant-select-item-option-content"][position() > last() - 1]'
PCONTACT_CITY = 'xpath:(//div[starts-with(@class, "ant-select-selector")])[3]'
PCONTACT_CITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select")and contains(@id, "option")]'
PCONTACT_STATEST1 = 'xpath:(//div[starts-with(@class, "ant-select-selector")])[4]'
PCONTACT_STATEST1_OPTIONS = 'xpath://div[starts-with(@id, "react-select")and contains(@id, "option")]'
PCONTACT_STATEST2 = 'name:state'
PCONTACT_ZIPCODE = 'xpath://div[@class="list-input"]//div[@class="custom-text-input"][1]//input'
PCONTACT_PRIMARYPHONE = 'xpath:(//span[@class="ant-input-group-addon"])[1]/../input'
PCONTACT_SECONDARYPHONE = 'xpath:(//span[@class="ant-input-group-addon"])[2]/../input'
PCONTACT_EMAIL = 'xpath://div[@class="list-input"]//div[@class="custom-text-input"][2]//input'
PCONTACT_SAVE = 'xpath://div[@class="bottom-button-row"]//button[2]'
PCONTACT_SAVE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
PCONTACT_HEADER = 'xpath://div[@class="drawer-title-container"]'
# Patient details > Edit secondary contact dialog
PCONTACTST2_NAME = 'xpath:(//div[@class="custom-text-input"])[1]//input'
PCONTACTST2_PHONENUMBER = 'xpath://div[contains(@class,"phone-input-wrapper")]//input'
PCONTACTST2_RELATIONSHIP = 'xpath:(//div[@class="custom-text-input"])[2]//input'
PCONTACTST2_EMAIL = 'xpath:(//div[@class="custom-text-input"])[3]//input'
PCONTACTST2_SAVE = 'xpath://div[@class="bottom-button-row"]//button[2]'
PCONTACTST2_SAVE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
# Patient details > Edit Insurance dialog
PINS_INSURANCETYPE = 'xpath://div[@class="list-input"]//div[@class="ant-select-selector"]'
PINS_INSURANCETYPE_OPTIONS = 'xpath://div[@class="list-input"]//following::div[contains(@class,"ant-select-item-option-content")]'
PINS_PROVIDER = 'xpath://input[@placeholder="Enter provider"]'
PINS_PREAUTHORIZATION = 'xpath://div[contains(@class,"radio-group-wrapper")]//label'
PINS_SAVE = 'xpath://div[@class="bottom-button-row"]//button[2]'
PINS_SAVE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
# Patient details > Edit medication history dialog
PMEDIHIS_SYMPTOMS = 'xpath:(//div[@class="list-input"]//div[@class="ant-select-selector"])[1]'
PMEDIHIS_SYMPTOMS_CURRENT = 'xpath:(//div[@class="list-input"]//div[@class="ant-select-selector"])[1]//span[@class="ant-select-selection-item"]'
PMEDIHIS_SYMPTOMS_OPTIONS = 'xpath:(//div[@class="list-input"]//div[@class="ant-select-selector"])[1]//following::div[@class="ant-select-item-option-content"]'
PMEDIHIS_SYMPTOMS_TIMEHAPPEN = 'xpath:(//div[@class="list-input"]//div[@class="ant-select-selector"])[2]'
PMEDIHIS_SYMPTOMS_TIMEHAPPEN_OPTIONS = 'xpath:(//div[@class="list-input"]//div[@class="ant-select-selector"])[2]//following::div[@class="ant-select-item-option-content"]'
PMEDIHIS_SYMPTOMS_HEARTMONITORBEFORE = 'xpath://div[contains(@class,"radio-group-wrapper")]//label'
PMEDIHIS_SELECTEDSYMPTOMS = 'xpath://div[contains(@class, "multiValue")]'
PMEDIHIS_SAVE = 'xpath://div[@class="bottom-button-row"]//button[2]'
PMEDIHIS_SAVE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
# Reports
REPORT_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th[contains(@class,"ant-table-cell")]'
REPORT_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//table[contains(@class,"reports-table")]//tr//td'
REPORT_BYREPORT = 'xpath://div[contains(@class, "active")]//button[contains(@class, "dropdown-toggle")]'
REPORT_BYREPORT_OPTIONS = 'xpath://div[contains(@class, "dropdown-menu") and contains(@class, "show")]//button[contains(@class, "dropdown-item")]'
REPORT_SEARCHTEXTBOX = 'xpath://div[contains(@class, "active")]//input[@placeholder="Search by Report ID"]'
# Events
EVENT_ROOT = 'xpath://div[@id and contains(@class, "event-list-item")]'
EVENT_DATA_HEADER1ST = 'xpath:.//span[@class="title"]'
EVENT_DATA_HEADER2ST = 'xpath:.//div[contains(@class, "info-ecg__group-comment")]//span[1]'
EVENT_DATA_CONTENT1ST = 'xpath:.//span[@class="normal-content"]'
EVENT_DATA_CONTENT2ST = 'xpath:.//div[contains(@class, "info-ecg__group-comment")]//span[last()]'
EVENT_DATA_CONTENT_VIEWECG = 'xpath://div[@class="event-list-item-container"]//div[contains(@class,"item-header-right")]//button'
EVENT_STARTDATE = 'xpath://input[@placeholder="Start date"]'
EVENT_ENDDATE = 'xpath://input[@placeholder="End date"]'
EVENT_BYTYPE = 'xpath://div[@class="ant-select-selector"]'
EVENT_BYTYPE_OPTIONS = 'xpath://div[contains(@class,"active")]//div[@class="ant-select-item-option-content"]'
EVENT_SEARCHTEXTBOX = 'xpath://div[@class="right-header"]//input'
EVENT_SORT = 'xpath://button[@id="sort-btn"]'
EVENT_REFRESH = 'xpath:(//img[@alt="Sort icon"])[2]/..'
EVENT_NONE = 'xpath://div[@class="archived-study-container"]'
EVENT_LOADING = 'xpath://div[@class="loading-more"]'
EVENT_SORT_REPORT = 'xpath://div[@class="ant-tooltip-inner"]'

# ECG Viewer
ECG_DATA = 'xpath://div[@class="event-ecg-viewer"]//div[@class="warning-message"]'
ECG_BYDATE = 'name:selectedDate'
ECG_BYDATE_TODAY = 'class:ant-picker-today-btn'
ECG_RELOAD = 'xpath://div[contains(@class, "active")]//img[@alt="Reload icon"]/..'
ECG_INDICATORS = 'id:custom-checkbox-input-event-indicators'
ECG_BYEVENTTYPE = 'xpath://div[@class="top-table-header"]//div[@class="dropdown"]//img[@class="dropdown-icon"]/..'
ECG_BYEVENTTYPE_OPTIONS = 'xpath://div[contains(@class, "show")]//button[starts-with(@class, "dropdown-item")]'
ECG_DATA_HEADER = 'xpath://div[contains(@class, "active")]//table//th'
ECG_DATA_ROW = 'xpath://div[contains(@class, "active")]//table//tbody//tr[position() > 1]'
ECG_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//table//tbody//tr[position() > 1]//td'
ECG_REFRESH = 'xpath://button[@id="reload-data-id-btn"]'
ECG_INDICATORS_CHECKBOX = 'xpath://input[@id="event-indicators"]'
ECG_SPEED = 'xpath:(//div[@id="ecgToolbarRow"]//button)[1]'
ECG_SPEED_OPTION = 'xpath://div[not(contains(@class,"hidden"))]/ul[@role="menu"]//span[@class="ant-dropdown-menu-title-content"]'
ECG_GAIN = 'xpath:(//div[@id="ecgToolbarRow"]//button)[2]'
ECG_HIGH_PASS = 'xpath:(//div[@id="ecgToolbarRow"]//button)[3]'
ECG_LOW_PASS = 'xpath:(//div[@id="ecgToolbarRow"]//button)[4]'
ECG_SHOW_HIDE_CH1 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[5]'
ECG_SHOW_HIDE_CH2 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[6]'
ECG_SHOW_HIDE_CH3 = 'xpath:(//div[@id="ecgToolbarRow"]//button)[7]'
ECG_BEAT_MARKER_TOOL = 'xpath://button[@id="addRemoveBeatMarkerButton"]'
ECG_VIEW_ALL_STRIP = 'xpath://button[@id="viewAllButton"]'
ECG_BEAT_MARKER_N = 'xpath://button[@id="beatMarkerN"]'
ECG_BEAT_MARKER_S = 'xpath://button[@id="beatMarkerS"]'
ECG_BEAT_MARKER_V = 'xpath://button[@id="beatMarkerV"]'
ECG_BEAT_MARKER_Q = 'xpath://button[@id="beatMarkerQ"]'
ECG_BEAT_MARKER_DELETE = 'xpath://button[@id="beatMarkerDelete"]'
ECG_EVENT_TYPE_OPTION = 'xpath://div[@class="option"]//div[@class="ant-select-item-option-content"]'
ECG_EVENT_TYPE = 'xpath://div[@class="option"]//div[@class="ant-select-selector"]'
ECG_FILTER_EVENT = 'xpath://div[@class="ecg-viewer-container"]//div[contains(@class,"event-info")]'
ECG_DATE_OPTION = 'xpath://div[contains(@class,"date-panel")]//tr//td[not(contains(@class,"disabled")) and following::td[contains(@class,"cell-start")]]'
ECG_CHART = 'xpath://div[@class="highcharts-series-group"]'

# Instant reports study
INS_CREATE_INSREPORT = 'xpath://button[@id="create-instant-report-btn" or @id="create-report-btn"]'
INS_CREATE_INSREPORT_SUBMIT = 'xpath://div[@class="create-instant-report-modal"]//button[@id="create-instant-report-btn"]'
INS_SELECTED_DATE = 'xpath://td[not(contains(@class,"disabled"))]//div[@class="ant-picker-cell-inner"]'
INS_CHECKED_CREATED = 'xpath://div[@class="checked-icon"]'
INS_STATUS_GENERATION = 'xpath://div[@class="generating-icon"]'

INS_DATA_HEADER = 'xpath://div[contains(@class, "active")]//table//th'
INS_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//tr[not(@aria-hidden="true")]//td[position() < last()]'
INS_DATA_ROW = 'xpath://div[contains(@class, "active")]//table//tbody//tr[not(@aria-hidden="true")]'
INS_SEARCHBY_INPUT = 'xpath://div[@role="tabpanel"]//div[contains(@class,"custom-input-wrapper")]//input'
INS_OPENREPORT = 'xpath://div[contains(@class, "active")]//div[@class="action-table"]//img[2]'
INS_DELETEREPORT = 'xpath://div[contains(@class, "active")]//div[@class="action-table"]//img[1]'
INS_DELETEREPORT_CONFIRM = 'xpath://div[@class="ant-modal-content"]//button[@id="right-id-btn"]'

# Instant report details
INSDET_OVERVIEW_HEADER = 'selector:div.inbox-detail div.title-block__title'
INSDET_OVERVIEW_CONTENT = 'selector:div.inbox-detail div.title-block__content'
INSDET_DELETEICON = 'xpath://div[contains(@class, "inbox-detail")]//button[starts-with(@id, "delete")]'
INSDET_DELETE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[starts-with(@class, "outline-btn")]'
INSDET_REGENERATE = 'xpath://button[@id="re-generate-button"]'
INSDET_REGENERATE_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[starts-with(@class, "outline-btn")]'
INSDET_DOWNLOADBUTTON = 'id:download-btn'
INSDET_ADDCOMMENTBUTTON = 'id:add-interpretation-btn'
INSDET_ADDCOMMENTBUTTON_INPUT = 'xpath://div[@class="ant-modal-content"]//textarea'
INSDET_ADDSIGNATUREBUTTON = 'id:add-signature-btn'
INSDET_SAVEBUTTON = 'id:save-btn'
INSDET_PDFVIEWER = 'id:pdf-viewer'
INSDET_BACKICON = 'xpath://div[contains(@class, "inbox-detail")]//img[@alt="Back icon"]/..'
INSDET_CREATE = 'xpath://img[@alt="No data icon"]/..//button[@type="button"]'
INSDET_MESSAGE = 'xpath://div[contains(@class,"instant-reports-tab")]//div[@class="archived-study-container-instant"]'
INSDET_BACK = 'xpath://span[@class="ant-btn-icon"]'

# Study detail -> FO Tracking
STDET_DATA_CONTENT_TRACKING = 'xpath://div[@class="f0-study"]//div[@class="label"]'
STDET_DATA_VALUE_TRACKING = 'xpath://div[@class="f0-study"]//div[@class="value"]'
PAGE_HEADER_DETAIL = 'xpath://div[@class="top-container"]//following-sibling::span'
PAGE_HEADER_QUICK_ACCESS = 'xpath://span[@class="drawer-title"]'
STDET_DATA_STATUS_TRACKING = 'xpath://div[@class="badge"]'
STDET_FACILITY = 'xpath://div[@class="title-block"]/div[@class="item-content"]/div[@class="title-block__content"][contains(text(), "Facility")]'
# Physician amendments notes
PYAN_DIALOG_INPUT = 'xpath:(//div[@class="content"])[5]//textarea'
# Edit study detail
STEDIT_DATA = 'xpath://div[contains(@class,"edit-study-details")]//div[@class="content-container"]//div[contains(@class, "content")]'
STEDIT_DATA_TITLE = 'xpath://div[@class="content-container"]//div[@class="left"]//div[@class="title"]'
# Study History
STHISTORY_DATE = 'xpath://div[@class="history"]//div[@class="date"]'

# Report details
STUDY_REPORT_HEADER = 'xpath://div[contains(@class, "active")]//thead//th[contains(@class,"ant-table-cell")]'
STUDY_REPORT_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td[contains(@class,"ant-table-cell")][position() < last()]'
STUDY_REPORT_RAW = 'xpath://div[contains(@class, "active")]//tbody//tr[position() > 1]'
STUDY_REPORT_DOS = 'xpath://div[contains(@class, "active")]//thead//th[@class="ant-table-cell"]'
STUDY_REPORT_LAST_MODIFIED = 'xpath:(//div[contains(@class, "active")]//thead//th[contains(@class,"ant-table-cell")])[3]'
STUDY_REPORT_REPORT_TYPE = 'xpath://div[contains(@class, "active")]//thead//th[@aria-label="Report Type"]'
STUDY_REPORT_STATUS = 'xpath://div[contains(@class, "active")]//thead//th[@aria-label="Status"]'
STUDY_REPORT_ID = 'xpath:(//div[contains(@class, "active")]//thead//th[contains(@class,"ant-table-cell")])[1]'
STUDY_REPORT_NEXT = 'xpath://div[contains(@class, "active")]//li[@title="Next Page"]'
STUDY_REPORT_SUBTABS = 'xpath://div[@class="list-option"]//div'
STUDY_REPORT_SHOWING = 'xpath://div[contains(@class, "active")]//span[@class="show-count-page"]'
STUDY_REPORT_VIEW = 'xpath://div[@class="table-action"]//img'
STUDY_REPORT_BACK = 'xpath://div[@class="inbox-detail"]//button[@id="back-btn"]'
STUDY_REPORT_PDF = 'xpath://iframe[@id="pdf-viewer"]'
STUDY_REPORT_ABORTED_MESSAGE = 'xpath://div[@class="ant-alert-description"]'

# Return status
RS_DEVICE_RETURNED = 'xpath://div[@class="return-status-checkbox"]//button'
RS_SAVE = 'xpath://button[@id="save-btn"]'
RS_DEVICE = 'xpath:(//div[@class="return-status-checkbox"]//div[@class="list"]//input/..)[1]'
RS_ACCESSORIES = 'xpath:(//div[@class="return-status-checkbox"]//div[@class="list"]//input/..)[2]'
RS_BOX = 'xpath:(//div[@class="return-status-checkbox"]//div[@class="list"]//input/..)[3]'
RS_CABLE = 'xpath:(//div[@class="return-status-checkbox"]//div[@class="list"]//input/..)[4]'
RS_CHARGER = 'xpath:(//div[@class="return-status-checkbox"]//div[@class="list"]//input/..)[5]'
RS_QUICK_GUIDE = 'xpath:(//div[@class="return-status-checkbox"]//div[@class="list"]//input/..)[6]'
RS_NOTES_INPUT = 'xpath://div[@class="return-status-notes"]//textarea'
