FACILITY_CURRENT = 'xpath://*[@class="flex items-center"]//following::div[2]'
FACILITY_SELECTIONS = 'xpath://div[contains(@class,"ant-select-item ant-select-item-option")]'
CLOSE_POPUP = 'xpath://button[@id="right-id-btn"]'
STUDY_TABS = 'xpath://div[@class="ant-tabs-nav-list"]//div[contains(@class,"ant-tabs-tab-btn")]'
STUDY_TABS_VALUE = 'xpath://div[@class="ant-tabs-nav-list"]//div[contains(@class,"ant-tabs-tab-btn")]//span[1]'
SEARCHBY_ICON = 'xpath://div[@class="option-search"]//div[@class="ant-select-selector"]'
CLEARTEXTSEARCH_ICON = 'xpath://span[@class="ant-input-clear-icon"]'
CLEAR_BUTTON = 'xpath://button[@id="clear-btn"]'
SEARCHBY_OPTIONS = 'xpath://div[@class="option-search"]//div[contains(@class,"ant-select-item ant-select-item-option")]'
SEARCH_INPUT = 'xpath://div[@class="search-bar"]//input[@type="text"]'
NEWSTUDY_BUTTON = 'xpath://div[@class="search-bar"]//button'
STUDYSORT = 'class:sortable'
SIZEPERPAGE_CURRENT = 'xpath://div[@aria-label="Page Size"]//div[@class="ant-select-selector"]'
SIZEPERPAGE_OPTIONS = 'xpath://div[@aria-label="Page Size"]//div[@role="option"]'
PAGINATION_BUTTONS = 'xpath://li[contains(@class,"ant-pagination-item")]'
# Pagination
PAGINATION_NEXT = 'xpath://div[contains(@class,"active")]//*[@title="Next Page"]/img'
PAGINATION_PREVIOUS = 'xpath://div[contains(@class,"active")]//*[@title="Previous Page"]/img'
PAGINATION_PAGENUM = 'xpath://div[contains(@class, "active")]//button[contains(@class, "pagination-btn")]//span[not(text()=">") and not(text()="<")]/../..'
# Active
ACTIVE_LOADING_MORE = 'xpath://div[@class="loading-more"]'
ACTIVE_STUDY_DATA_ROOT = 'class:study-card'
ACTIVE_STUDY_1ST_HEADER = 'xpath:.//span[@class="title"]'
ACTIVE_STUDY_1ST_CONTENT = 'xpath:.//span[@class="title"]/../*[2]'
ACTIVE_STUDY_2ND_HEADER = 'xpath:.//*[@class="info-col"][1]/div'
ACTIVE_STUDY_2ND_CONTENT = 'xpath:.//*[@class="info-col"][2]/div'
ACTIVE_STUDY_BIODIRECT = 'xpath:.//div[contains(@class,"biodirect-tag-list")]'
ACTIVE_STUDY_PROGRESS = 'xpath:.//div[contains(@class, "study-duration")]'
ACTIVE_STUDY_STOP = 'xpath:.//div[contains(@class, "study-duration")]//button[@id="stop-study-btn"]'
ACTIVE_STUDY_STOP_CONFIRM = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[@id="stop-stop-stuy-btn"]'
ACTIVE_STUDY_STOP_CANCEL = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "--black-text")]'
ACTIVE_STUDY_COPY = 'xpath://button[@id="copy-click-btn"]'
ACTIVE_STUDY_STRIPIMAGE = 'xpath://div[@class="image-gallery-slides"]'
ACTIVE_STUDY_GETECG = 'xpath://button[@id="get-ecg-btn"]'
ACTIVE_STUDY_VIEWSTUDY = 'xpath://div[@class="header-container__right"]//span[text()="Open study"]'
ACTIVE_STATUS = 'xpath://div[@class="device-status --empty"]'
ACTIVE_ABORT_BUTTON = 'xpath://button[@id="abort-study-btn"]'
ACTIVE_ABORT_CONFIRM_BUTTON = 'xpath://button[@id="right-id-btn"]//span[text()="Abort"]'
# Completed
COMPLETED_STUDY_HEADER = 'xpath://*[contains(@class,"ant-table-thead")]//th[@class="ant-table-cell"]'
COMPLETED_STUDY_CONTENT = 'xpath://*[contains(@class,"ant-table-row")]//td[contains(@class,"ant-table-cell")][position()>1 and position()<last()]'
COMPLETED_STUDY_ROW = 'xpath://*[contains(@class,"ant-table-row")]'
COMPLETED_STUDY_ISBIODIRECT = 'xpath:.//span[@class="biodirect-label"]'
COMPLETED_STUDY_STUDYID = 'xpath://div[@class="study-id-formatter"]//span'
COMPLETED_STUDY_PATIENTNAME = 'xpath://button[@id="patient-name-formatter-btn"]'
COMPLETED_STUDY_DEVICEID = 'xpath://button[@id="device-id-btn"]'
COMPLETED_STUDY_DELETEICONS = 'xpath://*[@class="ant-table-tbody"]//input[@type="checkbox"]'
COMPLETED_STUDY_BUTTON = 'xpath://*[@class="list-selected-study"]//button'
COMPLETED_STUDY_COPYICONS = 'xpath://div[starts-with(@id, "copy-study")]/button'
COMPLETED_STUDY_MANAGEICONS = 'xpath://img[@alt="studyTableIcon"]'
COMPLETED_STUDY_CHECKBOX_ALL = 'xpath://div[@class="custom-checkbox-container"]//input[@id="custom-checkbox-input-select-header"]'
COMPLETED_STUDY_CHECKBOXES = 'xpath://div[@class="custom-checkbox-container"]//input[starts-with(@id, "custom-checkbox-input-select-row")]'
COMPLETED_STUDY_DELETE = 'xpath://div[@class="top-nav-tabs-container"]//button[contains(@class, "outline-btn")]'
COMPLETED_STUDY_DELETE_CONFIRM = 'xpath://button[@id="right-id-btn"]'
COMPLETED_STUDY_ID = 'xpath://div[@class="ant-table-column-sorters"]'
COMPLETED_STUDY_ID_VALUE = 'xpath://button[@id="study-id-btn"]'
COMPLETED_DATA_SAMPLE = 'xpath://*[contains(@class,"ant-table-row")]'
COMPLETED_STUDYID = 'xpath://button[@id="study-id-btn"]'
COMPLETED_DATE = 'xpath://button[@id="study-id-btn"]//following::td[1]'
COMPLETED_STOP_TIME = 'xpath://button[@id="study-id-btn"]//following::td[2]'
COMPLETED_PATIENT_VISIT = 'xpath://button[@id="study-id-btn"]//following::td[3]'
COMPLETED_DURATION = 'xpath://button[@id="study-id-btn"]//following::td[4]'
COMPLETED_PATIENT_NAME = 'xpath://button[@id="study-id-btn"]//following::td[5]'
COMPLETED_PATIENT_ID = 'xpath://button[@id="study-id-btn"]//following::td[6]'
COMPLETED_DEVICE_ID = 'xpath://button[@id="study-id-btn"]//following::td[7]'
COMPLETED_STUDY_TYPE = 'xpath://button[@id="study-id-btn"]//following::td[8]'
COMPLETED_FACILITY = 'xpath://button[@id="study-id-btn"]//following::td[9]'
COMPLETED_RAW = 'xpath://tr[contains(@class,"ant-table-row")]'
COMPLETED_RAW_STUDYID = 'xpath://div[@class="study-id-formatter"]'
COMPLETED_ABORT_STUDY = 'xpath://div[@class="switch-group"]//button'
COMPLETED_COPY_STUDY = 'xpath://img[@alt="copyTableIcon"]/..'
COMPLETED_DELETE_STUDY = 'xpath://img[@alt="trashTableIcon"]/..'
COMPLETED_MANAGE_MORE_ICON = 'xpath://img[@alt="moreIcon"]/..'
# Flagged
FLAGGED_STUDY_DATA_ROOT = 'class:study-card'
FLAGGED_STUDY_HEADER = 'xpath:.//*[@class="title"]'
FLAGGED_STUDY_1ST_CONTENT = 'xpath:.//div[contains(@class, "title-block")]//*[self::strong or @class="name"]'
FLAGGED_STUDY_2ND_CONTENT = 'xpath:.//div[@class="info-row"]//*[self::strong or contains(@class, "flex-") or (self::span and not(@class))]'
FLAGGED_STUDY_RESOLVED = 'xpath:.//div[contains(@class, "resolved")]'
FLAGGED_STUDY_PROGRESS = 'xpath:.//div[contains(@class, "study-duration")]'
FLAGGED_STUDY_STOP = 'xpath://div[@class="study-duration"]//button'
FLAGGED_STUDY_GETECG = 'xpath://div[@class="header-container__right"]//button[contains(@class, "outline-btn")]'
# Deleted
DELETED_DATA_SAMPLE = 'xpath://*[contains(@class,"ant-table-row")]'
DELETED_STUDYID = 'xpath://div[contains(@class,"study-fid-item")]'
DELETED_STOP_TIME = 'xpath://div[contains(@class,"study-fid-item")]//following::td[1]'
DELETED_PATIENT_VISIT = 'xpath://div[contains(@class,"study-fid-item")]//following::td[2]'
DELETED_DURATION = 'xpath://div[contains(@class,"study-fid-item")]//following::td[3]'
DELETED_PATIENT_NAME = 'xpath://div[contains(@class,"study-fid-item")]//following::td[4]'
DELETED_PATIENT_ID = 'xpath://div[contains(@class,"study-fid-item")]//following::td[5]'
DELETED_DEVICE_ID = 'xpath://div[contains(@class,"study-fid-item")]//following::td[6]'
DELETED_STUDY_TYPE = 'xpath://div[contains(@class,"study-fid-item")]//following::td[7]'
DELETED_FACILITY = 'xpath://div[contains(@class,"study-fid-item")]//following::td[8]'

DELETED_STUDY_HEADER = 'xpath://*[@class="ant-table-thead"]//th[@class="ant-table-cell"]'
DELETED_STUDY_CONTENT = 'xpath://*[@class="ant-table-tbody"]//td[contains(@class,"ant-table-cell")][position()<last()]'
DELETED_STUDY_CONTENT_ROW = 'xpath://*[contains(@class,"ant-table-row")]'
DELETED_STUDY_CONTENT_PATIENTNAME = 'xpath://td[not(@class)]//button[@class="text-btn"]'
DELETED_STUDY_CONTENT_DEVICEIID = 'xpath://td[not(@class)]//button[contains(@class, "nowrap")]'
DELETED_STUDY_RESTOREICONS = 'xpath://img[@alt="restoreIcon"]'
DELETED_STUDY_NAME = 'xpath://th[@aria-label="Study ID"]'
DELETED_STUDY_VALUE = 'xpath://*[@class="ant-table-tbody"]//tr//*[@class="ant-table-cell"]'
DELETED_STUDY_ID_VALUE = 'xpath://*[@class="ant-table-tbody"]//div[@class="flex items-center study-fid-item"]'
# New study
NEW_STUDY_ENTER_NOW = 'xpath://div[@class="footer"]//button[2]'
NEW_STUDY_CANCEL = 'xpath://div[@class="footer"]//button[1]'
NEW_STUDY_NOTI = 'xpath://div[@class="footer"]/..//div[@class="content"]'
NEW_STUDY_MSG_BIODIRECT = 'xpath://div[@class="biodirect-warning-msg"]'
NEW_STUDY_BACK_ICON = 'xpath://button[contains(@class, "back-icon-btn")]'
NEW_STUDY_BACK_YES = 'xpath://div[contains(@class, "custom-confirm-modal")]//button[contains(@class, "outline-btn")]'
NEW_STUDY_PAGE_NAME = 'xpath://div[contains(@class,"active")]//div[@class="ant-steps-item-content"]'
NEW_STUDY_LEFTCONTAINER = 'class:custom-body__right-container'
NEW_STUDY_STEP = 'xpath://div[contains(@class,"new-study-step")]//div[contains(@class,"ant-steps-item-active")]'
NEW_STUDY_NOTI_EMAIL = 'xpath://img[@class="icon-error"]/..'
# New Study Page 1
NEW_STUDY_PAGE_1_PATIENTID = 'id:patientId'
NEW_STUDY_PAGE_1_FIRSTNAME = 'id:firstName'
NEW_STUDY_PAGE_1_MIDDLENAME = 'id:middleName'
NEW_STUDY_PAGE_1_LASTNAME = 'id:lastName'
NEW_STUDY_PAGE_1_DOB = 'id:dob'
NEW_STUDY_PAGE_1_HEIGHT_FT = 'id:heightFt'
NEW_STUDY_PAGE_1_HEIGHT_IN = 'id:heightIn'
NEW_STUDY_PAGE_1_WEIGHT = 'id:weight'
NEW_STUDY_PAGE_1_GENDERS = 'xpath://span[text()="Gender"]/..//label'  # handle i18n for Gender
NEW_STUDY_PAGE_1_ETHNICITY = 'xpath://button[@class="ethnicity-btn"]//following::div[@class="ant-select-selector"]'
NEW_STUDY_PAGE_1_ETHNICITY_OPTION = 'xpath://div[@class="rc-virtual-list"]//div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_1_IMPLANDEVICE = 'xpath://div[@class="implantable_device"]/div'
NEW_STUDY_PAGE_1_IMPLANDEVICE_PACEMAKER = 'xpath://input[@id="implantable_device__pacemaker"]'
NEW_STUDY_PAGE_1_IMPLANDEVICE_ICD = 'xpath://input[@id="implantable_device__icd"]'
NEW_STUDY_PAGE_1_PACEMAKERS = 'xpath://span[text()="Pacemaker"]/..//button'  # handle i18n for Pacemaker
NEW_STUDY_PAGE_1_NEXT = 'xpath://div[@class="bottom-button-row"]//button'
# New study page 2
NEW_STUDY_PAGE_2_CURRENTCOUNTRY = 'xpath://*[text()="Country"]//following::div[@class="ant-select-selector"][1]'
NEW_STUDY_PAGE_2_COUNTRY_INPUT = 'xpath://div[@class="step-content step-2"]//span[@title="United States"]/..'
NEW_STUDY_PAGE_2_COUNTRY_OPTIONS = 'xpath://div[@class="rc-virtual-list"]//div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_2_ADDRESS_INPUT = 'xpath://div[@class="custom-auto-complete-wrapper"]//input'
NEW_STUDY_PAGE_2_ADDRESS_OPTIONS = 'xpath://div[@id="address_list"]//following::div[2]//div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_2_CITY = 'xpath://div[contains(@class, "city-input")]//input'
NEW_STUDY_PAGE_2_CITY_OPTIONS = 'xpath://div[@id="fc_push_frame"]//following::div[@class="rc-virtual-list-scrollbar"][2]//..//div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_2_CURRENTSTATE = 'xpath://*[text()="Country"]//following::div[@class="ant-select-selector"][4]'
NEW_STUDY_PAGE_2_STATE = 'xpath://div[contains(@class, "state-input")]//input'
NEW_STUDY_PAGE_2_STATE_OPTIONS = 'xpath://div[contains(@class, "state-input")]//div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_2_ZIPCODE = 'xpath://input[@id="zip"]'
NEW_STUDY_PAGE_2_PRIMARYPHONE = 'xpath://div[@id="text-input-wrapper-zip"]//following::span[contains(@class,"ant-input-group-wrapper")][1]//input'
NEW_STUDY_PAGE_2_EMAIL = 'xpath://input[@id="email"]'
NEW_STUDY_PAGE_2_SECONDARYPHONE = 'xpath://div[@id="text-input-wrapper-zip"]//following::span[contains(@class,"ant-input-group-wrapper")][2]//input'
NEW_STUDY_PAGE_2_ADD2ND = 'xpath://button[contains(@class, "add-secondary-contact-button")]'
NEW_STUDY_PAGE_2_2ND_NAME = 'xpath://input[@id="secondaryName"]'
NEW_STUDY_PAGE_2_2ND_RELATIONSHIP = 'xpath://input[@id="secondaryRelationship"]'
NEW_STUDY_PAGE_2_2ND_PHONE = 'xpath://div[@id="text-input-wrapper-zip"]//following::span[contains(@class,"ant-input-group-wrapper")][3]//input'
NEW_STUDY_PAGE_2_2ND_EMAIL = 'xpath://input[@id="secondaryEmail"]'
NEW_STUDY_PAGE_2_PREVIOUS = 'xpath://div[@class="bottom-button-row"]//button[1]'
NEW_STUDY_PAGE_2_NEXT = 'xpath://button[@id="nextStep2Button"]'
# New study page 3
NEW_STUDY_PAGE_3_FACILITY_INPUT = 'xpath://div[@class="facility-select"]//div[@class="ant-select-selector"]'
NEW_STUDY_PAGE_3_CURRENTFACILITY = 'xpath://div[contains(@class, "elect-facilities-select-input")]//div[contains(@class, "singleValue")]'
NEW_STUDY_PAGE_3_FACILITY_OPTIONS = 'xpath://div[@class="facility-select"]//div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_3_FUNCTIONALTEST = 'xpath://input[@id="custom-checkbox-input-isTest"]'
NEW_STUDY_PAGE_3_USEBIODIRECT = 'xpath://div[@class="biodirect-switch-input-container"]//button[@role="switch"]'
NEW_STUDY_PAGE_3_DEVICE_TYPES = 'xpath://div[@class="biodirect-switch-input-container"]//following::input[@type="radio"]'
NEW_STUDY_PAGE_3_DEVICEINPUT = 'xpath://div[contains(@class,"device-id-select")]//input'
NEW_STUDY_PAGE_3_CURRENTDEVICE = 'xpath://div[@class="device-id-select"]//div[@class="ant-select-selector"]//input'
NEW_STUDY_PAGE_3_DEVICE_OPTIONS = 'xpath://div[contains(@class,"device-id-select")]//div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_3_REFPHYSICIAN_INPUT = 'xpath://div[@class="referring-physician-select"]//input'
NEW_STUDY_PAGE_3_REFPHYSICIAN_OPTIONS = 'xpath://div[@class="referring-physician-select"]//div[contains(@class,"ant-select-item ant-select-item-option ant-select-item-option-grouped")]'
NEW_STUDY_PAGE_3_REFPHYSICIAN_ADDPHYSICIAN = 'xpath://div[@class="add-new-physician"]'
NEW_STUDY_PAGE_3_INTPHYSICIAN_INPUT = 'xpath://*[text()="Interpreting physician"]//following::input[1]'
NEW_STUDY_PAGE_3_INTPHYSICIAN_OPTIONS = 'xpath://*[text()="Interpreting physician"]//following::div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_3_STUDYTYPE_INPUT = 'xpath://input[@id="studyType"]/../..'
NEW_STUDY_PAGE_3_STUDYTYPE_OPTIONS = 'xpath://div[@class="rc-virtual-list-holder"]/..//div[contains(@class,"ant-select-item ant-select-item-option")]/..//div[contains(@class,"ant-select-item-option-content")]'
NEW_STUDY_PAGE_3_DURATION = 'xpath://div[@id="text-input-wrapper-"]//input[contains(@placeholder, "duration")]'
NEW_STUDY_PAGE_3_PRV = 'name:reportDueDate'
NEW_STUDY_PAGE_3_INITIALS = 'xpath://div[@id="text-input-wrapper-"]//input[contains(@placeholder, "clinician ")]'
NEW_STUDY_PAGE_3_PREVIOUS = 'xpath://div[@class="bottom-button-row"]//button[1]'
NEW_STUDY_PAGE_3_NEXT = 'xpath://div[@class="step-3"]//div[@class="bottom-button-row"]//button[@id="next-btn"]'
NEW_STUDY_PAGE_3_CONTINUE = 'xpath://div[@class="footer"]//button[@id="right-id-btn"]'
NEW_STUDY_PAGE_3_POPUP = 'xpath://div[@class="ant-modal-content"]'
NEW_STUDY_PAGE_3_LOADING = 'xpath://div[@class="device-id-select"]//span[@class="ant-select-selection-item"]'
# New study page 4
NEW_STUDY_PAGE_4_PRIMARYDIAGNO = 'xpath:(//input[starts-with(@class, "ant-select")])[1]/../..'
NEW_STUDY_PAGE_4_PRIMARYDIAGNO_OPTIONS = 'xpath://*[text()="Primary diagnosis code"]//following::div[contains(@class,"ant-select-item ant-select-item-option")]/..//div[contains(@class,"ant-select-item-option-content")]'
NEW_STUDY_PAGE_4_PRIMARYDIAGNO_OTHERINPUT = 'xpath:(//input[@placeholder="Enter diagnosis code"])[1]'
NEW_STUDY_PAGE_4_SECONDARYDIAGNO = 'xpath:(//input[starts-with(@class, "ant-select")])[2]/../..'
NEW_STUDY_PAGE_4_CURRENTSECONDARYDIAGNO = 'xpath:(//input[starts-with(@class, "ant-select")])[2]'
NEW_STUDY_PAGE_4_SECONDARYDIAGNO_OPTIONS = 'xpath:(//input[starts-with(@class, "ant-select")])[2]//following::div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_4_SECONDARYDIAGNO_OTHERINPUT = 'xpath:(//input[@placeholder="Enter diagnosis code"])[2]'
NEW_STUDY_PAGE_4_PATIENTMEDICATION = 'xpath:(//textarea[(@type="textarea")])[1]'
NEW_STUDY_PAGE_4_PHYSICIANNOTES = 'xpath:(//textarea[(@type="textarea")])[2]'
NEW_STUDY_PAGE_4_ISRTYPE = 'xpath:(//input[starts-with(@class, "ant-select")])[3]/../..'
NEW_STUDY_PAGE_4_CURRENTISRTYPE = 'xpath:(//input[starts-with(@class, "ant-select")])[3]'
NEW_STUDY_PAGE_4_ISRTYPE_OPTIONS = 'xpath:(//input[starts-with(@class, "ant-select")])[3]//following::div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_4_ISRPROVIDER = 'xpath://input[@placeholder="Enter provider"]'
NEW_STUDY_PAGE_4_PREAUTHEN = 'xpath:(//div[contains(@class,"radio-input")])[1]//label'
NEW_STUDY_PAGE_4_SYMPTOMS = 'xpath://div[@class="ant-select-selection-overflow"]'
NEW_STUDY_PAGE_4_SYMPTOMS_INPUT = 'xpath://div[@class="ant-select-selection-overflow"]//input'
NEW_STUDY_PAGE_4_CURRENTSYMPTOMS = 'xpath://div[@class="ant-select-selection-overflow"]//div[@class="ant-select-selection-overflow-item"]'
NEW_STUDY_PAGE_4_SYMPTOMS_OPTIONS = 'xpath://div[@class="ant-select-selection-overflow"]//following::div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_4_SYMPTOMSHAPPEN = 'xpath:(//input[starts-with(@class, "ant-select")])[5]/../..'
NEW_STUDY_PAGE_4_CURRENTSYMPTOMSHAPPEN = 'xpath:(//input[starts-with(@class, "ant-select")])[5]'
NEW_STUDY_PAGE_4_SYMPTOMSHAPPEN_OPTIONS = 'xpath:(//input[starts-with(@class, "ant-select")])[5]//following::div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_STUDY_PAGE_4_BEFOREHEARTMONITOR = 'xpath:(//div[contains(@class,"radio-input")])[2]//label'
NEW_STUDY_PAGE_4_PREVIOUS = 'xpath://button[@id="previous-new-study-step-4-btn"]'
NEW_STUDY_PAGE_4_NEXT = 'xpath://button[@id="initiate-new-study-step-4-btn"]'
NEW_STUDY_PAGE_4_HIDDEN_PRIMARY = 'xpath:(//input[starts-with(@class, "ant-select")])[1]//following::div[@title="Other"]'
NEW_STUDY_PAGE_4_HIDDEN_SECONDARY = 'xpath:(//input[starts-with(@class, "ant-select")])[2]//following::div[@title="Other"]'
# New study page 5
NEW_STUDY_PAGE_5_DONE = 'xpath://div[@class="bottom-button-row"]//button'
# New physician
NEW_PHY_FIRSTNAME = 'id:firstName'
NEW_PHY_LASTNAME = 'id:lastName'
NEW_PHY_TITLE = 'id:title'
NEW_PHY_COUNTRY = 'xpath://*[text()="Country"]//following::input[1]'
NEW_PHY_COUNTRY_OPTIONS = 'xpath://*[text()="Country"]//following::div[contains(@class,"ant-select-item ant-select-item-option")]'
NEW_PHY_ADDRESS = 'xpath://div[@class="custom-auto-complete-wrapper"]//input'
NEW_PHY_ADDRESS_OPTIONS = 'xpath://div[starts-with(@id, "react-select-") and contains(@class, "option")]'
NEW_PHY_CITY = 'id:city'
NEW_PHY_CITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select-") and contains(@class, "option")]'
NEW_PHY_STATE = 'id:state'
NEW_PHY_STATE_OPTIONS = 'xpath://div[starts-with(@id, "react-select-") and contains(@class, "option")]'
NEW_PHY_ZIPCODE = 'id:zip'
NEW_PHY_PHONE = 'id:phone1'
NEW_PHY_NIGHTPHONE = 'id:nightPhone'
NEW_PHY_EMAIL = 'id:email'
NEW_PHY_FAX = 'id:fax'
NEW_PHY_CREATE = 'class:filled-btn'
# Sort
SORT_STUDIES_ID = 'xpath://img[@alt="Sort Up Icon"]/../..'
STUDY_ID_DATA_CONTENT = 'xpath://div[@class="flex items-center study-fid-item"]//span'
# web page callcenter
CALLCENTER_STUDY_TABS = 'xpath://ul[contains(@class, "top-nav-tabs ")]/li'
CALLCENTER_FACILITY_INPUT = 'xpath://div[contains(@class, "custom-select-input")]//input'
CALLCENTER_FACILITY_OPTIONS = 'xpath://div[starts-with(@id, "react-select")]'
CALLCENTER_SEARCHBY = 'xpath://button[@id="studies-search-by"]'
CALLCENTER_TEXTSEARCH_INPUT = 'xpath://div[@id="search-notification"]//input'
CALLCENTER_SEARCHBY_OPTIONS = 'xpath://div[starts-with(@class, "search-by-options")]//button[contains(@class, "toggle-button")]'
CALLCENTER_DATA_HEADER = 'xpath://div[contains(@class, "active")]//thead//th'
CALLCENTER_DATA_CONTENT = 'xpath://div[contains(@class, "active")]//tbody//td'
CALLCENTER_COMPLETED_DATA_CONTENT_ROW = 'xpath://div[contains(@class, "active")]//tbody//tr'
CALLCENTER_COMPLETED_DATA_CONTENT_MANAGESTUDY = 'xpath://div[starts-with(@id, "manage-study")]'
CALLCENTER_ICON_MORE = 'xpath://button[@id="ic-more"]'
CALLCENTER_ABORT_STUDY = 'xpath://button[@class="item-more"]'
CALLCENTER_ABORT_STUDY_CONFIRM = 'xpath://button[@id="right-id-btn"]'
CALLCENTER_ABORT_MESSAGE = 'xpath://div[@class="aborted-study-message"]'
# web page direct
DIRECT_SIDEBAR = 'xpath://a[contains(@class,"sidebar-tab")]'
DIRECT_SEARCHBY = 'xpath://div[@class="icon-search-by"]/..'
DIRECT_TEXTSEARCH_INPUT = 'xpath://input[@class="input-number"]'
DIRECT_SEARCHBY_OPTIONS = 'xpath://div[@class="search-by-value"]//div[@class="option"]//button'
DIRECT_DATA_HEADER = 'xpath://div[@class="body-container"]//thead//th[position() < last()]'
DIRECT_DATA_CONTENT = 'xpath://div[@class="body-container"]//tbody//td[position() < last()]'
# Error message
# step1
MESSAGE_FIRST_NAME = 'xpath://div[contains(@id, "firstName")]//img/..'
MESSAGE_LAST_NAME = 'xpath://div[contains(@id, "lastName")]//img/..'
MESSAGE_PATIENT_ID = 'xpath://div[contains(@id, "patientId")]//img/..'
MESSAGE_DOB = 'xpath://div[contains(@id, "dob")]//img/..'
MESSAGE_HEIGHT = 'xpath://div[@class="error-message"]'
MESSAGE_WEIGHT = 'xpath://div[contains(@id, "weight")]//img/..'
# step2
MESSAGE_ADDRESS = 'xpath://div[@class="custom-auto-complete-wrapper"]//img/../..'
MESSAGE_CITY = 'xpath://div[contains(@class,"city-input")]//img/../..'
MESSAGE_STATE = 'xpath:(//div[contains(@class,"state-input")]//img)[2]/../..'
MESSAGE_ZIP_CODE = 'xpath://div[contains(@id, "zip")]//img/..'
MESSAGE_PRIMARY_PHONE_NUMBER = 'xpath:(//div[contains(@class, "phone-input")]//img)[2]/../..'
# step3
MESSAGE_DEVICE_ID = 'xpath:(//div[@class="device-id-select"]//img)[2]/../..'
MESSAGE_REFERRING_PHYSICIAN = 'xpath:(//div[@class="referring-physician-select"]//img)[2]/../..'
MESSAGE_INTERPRETING_PHYSICIAN = 'xpath:(//*[text()="Interpreting physician"]//following::img)[2]/../..'
MESSAGE_STUDY_TYPE = 'xpath://input[@id="studyType"]//following::img[2]/../..'
MESSAGE_CLINICIAN = 'xpath://input[@placeholder="Enter clinician initials"]//following::img[@class="icon-error"][1]/..'
MESSAGE_STUDY_DURATION = 'xpath://input[contains(@placeholder, "duration")]//following::img[@class="icon-error"][1]/..'
# step4
MESSAGE_PRIMARY_DIAGNOSIS_CODE = 'xpath:(//input[starts-with(@class, "ant-select")])[1]//following::img[2]/../..'
MESSAGE_INSURANCE_TYPE = 'xpath:(//input[starts-with(@class, "ant-select")])[3]//following::img[2]/../..'
MESSAGE_OTHER_PRIMARY_DIAGNOSIS_CODE = 'xpath:(//input[@placeholder="Enter diagnosis code"])[1]//following::img[1]/..'
MESSAGE_OTHER_SECONDARY_DIAGNOSIS_CODE = 'xpath:(//input[@placeholder="Enter diagnosis code"])[2]//following::img[1]/..'
# msg
NO_MORE_STUDY = 'xpath://img[@alt="Info message icon"]/..'
MESSAGE_NOTICE_CONTENT = 'xpath://div[@class="ant-message-notice-content"]'
# app
APP_BODY_ELEMENT = 'xpath://div[@class="app"]'

ALL_STUDIES_DROPDOWN = 'xpath://div[@class="custom-select-see-all-patient"]'
ALL_STUDIES_DROPDOWN_OPTIONS = 'xpath://div[@class="ant-select-item-option-content"]'

