MENU = 'xpath://div[contains(@class,"ant-tabs-tab-btn")]//span[@class="tab-text"]'
CONTACT_EMAIL = 'xpath://*[contains(@class,"link-contact")]'
CONTACT_PHONE = 'xpath://*[@class="text-right"]'
SEND_FEEDBACK = 'xpath://button[@id="send-feedback-btn"]'
CURRENT_FACILITY = 'xpath://div[@class="custom-select-facilities"]//div[@class="ant-select-selector"]'
FACILITY_SELECTIONS = 'xpath://div[@class="custom-select-facilities"]//div[@role="option"]'
REPORTPDF_FIELD = 'class:pdf-viewer'
REPORTPDF_FRAME = 'id:pdf-viewer'
# Support Request
SUPPORTRQ_DATA_ROW = 'xpath://tbody[@class="ant-table-tbody"]//tr[position() > 1]'
SUPPORTRQ_ID = 'xpath://tbody[@class="ant-table-tbody"]//tr[position() > 1]//td[contains(@class,"ant-table-cell")][1]'
SUPPORTRQ_STATUS = 'xpath://tbody[@class="ant-table-tbody"]//tr[position() > 1]//td[contains(@class,"ant-table-cell")][2]'
SUPPORTRQ_NEWREQUEST = 'xpath://button[@id="new-request-btn"]'
SUPPORTRQ_BYSTATUS = 'xpath://div[@class="status-input"]//div[@class="ant-select-selector"]'
SUPPORTRQ_BYSTATUS_OPTIONS = 'xpath://div[@class="status-input"]//div[@role="option"]'
SUPPORTRQ_BYCATEGORY = 'xpath://div[@class="request-input"]//div[@class="ant-select-selector"]'
SUPPORTRQ_BYCATEGORY_OPTIONS = 'xpath://div[@class="request-input"]//div[@role="option"]'
SUPPORTRQ_TEXTSEARCH = 'xpath://div[@class="request-input"]//following::input[@type="text"]'
SUPPORTRQ_DATA_HEADER = 'xpath://*[@class="ant-table-thead"]//th[(position() > 1)]'
SUPPORTRQ_DATA_CONTENT = 'xpath://tbody[@class="ant-table-tbody"]//tr[position() > 1]//td[position() < last()]'
SUPPORTRQ_DATA_CONTENT_ROW = 'xpath://table[contains(@class, "support-request-table")]//tbody//tr'
SUPPORTRQ_DATA_CONTENT_VIEWREQUEST = 'xpath://img[@alt="View request icon"]/..'
# Support Materials
SUPMATERIAL_SUBTABS = 'xpath://div[@id="support-materials"]//div[contains(@class,"ant-tabs-tab-btn")]'
SUPMATERIAL_CATEGORY = 'xpath://div[@class="category-list"]//button'
# new support request
SUBMR_FACILITY = 'xpath://div[@class="select-facilities-select-input"]//input'
SUBMR_FACILITY_OPTIONS = 'xpath://div[@class="select-facilities-select-input"]//div[contains(@class,"ant-select-item ant-select-item-option")]'
SUBMR_CATEGORY = 'xpath://div[@class="category-list"]//input/../..'
SUBMR_STUDYIDBOX = 'xpath://div[contains(@class, "multi-id-search__control")]//input'
SUBMR_EMAIL = 'xpath://div[@class="email-box"]//input'
SUBMR_MESSAGE = 'xpath://div[@class="message-box"]//textarea'
SUBMR_SUBMIT = 'xpath://div[@class="bottom-button-row"]//button'
SUBMR_BACKICON = 'xpath://img[@alt="Back icon"]/..'
# # change_study_type
SUBMR_CRQST_SEARCHBY = 'xpath://div[@class="option-search-for-study"]//div[@class="ant-select-selector"]'
SUBMR_CRQST_SEARCHBY_OPTIONS = 'xpath://div[@class="option-search-for-study"]//div[@class="ant-select-item-option-content"]/..'
SUBMR_CRQST_TEXTSEARCH = 'xpath://div[@id="search-for-study-id"]//div[contains(@class,"custom-search-select")]//input'
SUBMR_CRQST_TEXTSEARCH_OPTIONS = 'xpath://div[@id="search-for-study-id"]//div[contains(@class,"custom-menu-options")]//div[@role="option"]'
SUBMR_CRQST_NEWSTUDYTYPE = 'xpath://div[contains(@class, "new-study-type-select-input")]//div[@class="ant-select-selector"]'
SUBMR_CRQST_NEWSTUDYTYPE_OPTIONS = 'xpath://div[contains(@class, "new-study-type-select-input")]//div[contains(@class,"ant-select-item ant-select-item-option")]'
SUBMR_CRQST_SEARCHBYSTUDY_ROOT = 'xpath://div[@id="search-for-study-id"]//div[contains(@class,"custom-menu-options")]//div[@role="option"]'
SUBMR_CRQST_SEARCHBYSTUDY_NOOPTIONS = 'xpath://div[@id="search-for-study-id"]//div[contains(@class,"ant-select-dropdown-empty")]'
SUBMR_CRQST_SEARCHBYSTUDY_PATIENTNAME = 'xpath:.//div[@class="patientName"]'
SUBMR_CRQST_SEARCHBYSTUDY_STUDYTYPE = 'xpath:.//div[@class="studyType"]'
SUBMR_CRQST_SEARCHBYSTUDY_BOTTOMTITLE = 'xpath:.//div[@class="container-bottom"]//div[@class="name"]'
SUBMR_CRQST_SEARCHBYSTUDY_BOTTOMCONTENT = 'xpath:.//div[@class="container-bottom"]//div[@class="value"]'
SUBMR_CRQST_SELECTEDSTUDY_ROOT = 'xpath://div[@class="selected-study-type"]'
SUBMR_CRQST_SELECTEDSTUDY_PATIENTNAME = 'xpath:.//div[@class="infor-header"]//div[@class="patientName"]'
SUBMR_CRQST_SELECTEDSTUDY_STUDYID = 'xpath:.//div[@class="info-container"]//div[@class="studyId"]//div[@class="value"]'
SUBMR_CRQST_SELECTEDSTUDY_STARTDATE = 'xpath:.//div[@class="info-container"]//div[@class="startDate"]//div[@class="value"]'
SUBMR_CRQST_SELECTEDSTUDY_ENDDATE = 'xpath:.//div[@class="info-container"]//div[@class="endDate"]//div[@class="value"]'
SUBMR_CRQST_SELECTEDSTUDY_CURRSTUDYTYPE = 'xpath://div[@class="current-study-type-select-input"]//div[@class="ant-select-selector"]'
SUBMR_CRQST_SELECTEDSTUDY_NEWSTUDYTYPE = 'xpath:.//div[@class="new-study-type-select-input"]//div[@class="ant-select-selector"]'
# # abort study
SUBMR_ABORT_SEARCHINPUT = 'xpath://div[starts-with(@class, "custom-multi-id-input")]//input'
# # Billing
SUBMR_BILLINGISSUE_SELECTIONS = 'xpath://div[@class="billing-questions"]//input[@class="ant-radio-input"]/../..'

# Send feedback
FEEDBACK_YOURFACILITY = 'xpath://div[@class="your-facility"]//div[@class="ant-select-selector"]'
FEEDBACK_CATEGORY = 'xpath://div[@class="category-box"]//label[contains(@class, "ant-radio-wrapper")]'
FEEDBACK_FACILITY = 'xpath://div[contains(@class, "your-facility")]//div[contains(@class, "custom-your-facilities")]//div[@class="ant-select-selector"]'
FEEDBACK_FACILITY_OPTIONS = 'xpath://div[contains(@class, "ant-select-item-option-content")]'
FEEDBACK_EMAIL = 'xpath://div[@class="your-email-box"]//input'
FEEDBACK_MESSAGE = 'xpath://div[@class="message-box"]//textarea'
FEEDBACK_BUTTON = 'id:send-feedback-btn'
FEEDBACK_SUBMIT = 'xpath://button[@id="submit-btn"]'
FEEDBACK_EMAIL_ERROR = 'xpath://div[@class="your-email-box"]//p'
FEEDBACK_MESSAGE_ERROR = 'xpath://div[@class="message-box"]//p'
FEEDBACK_CLOSE_MODAL = 'xpath://button[@id="close-btn"]'
