# Notification
NOTIFICATION = 'xpath://div[contains(@class, "sidebar")]//button[1]'
NOTIFICATION_CLOSE = 'xpath://div[contains(@class, "style_notificationDrawerHeader")]/button'
NOTIFICATION_CLEAR_ALL = 'xpath://div[contains(@class, "style_notificationDrawerContentHeaderRight")]'
NOTIFICATION_DATA_ROOT = 'xpath://div[contains(@class, "style_notificationCard__")]'
NOTIFICATION_DATA_TITLE = 'xpath:.//div[contains(@class, "notificationCardHeaderTitle")]'
NOTIFICATION_DATA_DESC = 'xpath:.//div[contains(@class, "notificationCardContent")]'
NOTIFICATION_DATA_TIME = 'xpath:.//div[contains(@class, "notificationCardFooter")]'
NOTIFICATION_DELETE = 'xpath://div[contains(@class, "style_actionsDrawer")]/button'
NOTIFICATION_CONFIRM_DELETE = 'xpath:(//div[contains(@class, "confirmationModalFooter")]/button)[2]'
NOTIFICATION_CANCEL_DELETE = 'xpath:(//div[contains(@class, "confirmationModalFooter")]/button)[1]'
NOTIFICATION_TITLE = 'xpath://div[contains(@class, "style_notificationDrawerHeader")]/h2'
NOTIFICATION_CARD = 'xpath://div[contains(@class, "style_notificationDrawerContentBody")]/div'
NOTIFICATION_WHAT_NEW = 'xpath://img[@alt="whatsnew"]'
