# Edit Profile
PROF_SIDEBAR_AVATAR = 'xpath://div[contains(@class, "customAvt")]'
PROF_EDIT = 'xpath://div[contains(@class,"profileDrawerContent")]//button[1]'
PROF_HEADER = 'xpath://div[contains(@class, "infoItem")]/p[contains(@class,"infoTitle")]'
PROF_CONTENT = 'xpath://div[contains(@class, "infoItem")]/p[contains(@class,"infoValue")]'
PROF_SAVE = 'xpath://div[contains(@class, "editProfile")]//div[contains(@class, "headerBtn")]'
PROF_NAME = 'xpath://div[contains(@class, "profileName")]'
PROF_EMAIL = 'xpath://p[contains(@class, "profileRole")]'
PROF_BIOSPHERE = 'xpath://span[contains(@class, "biophereText")]'
PROF_BIOSPHERE_STATUS = 'xpath://span[contains(@class, "monthlyText")]'
PROF_BACK = 'xpath://div[contains(@class,"editProfile")]/button'
PROF_AVATAR = 'xpath:(//div[contains(@class, "style_customAvt")]/img)[2]'
PROF_CLOSE = 'xpath://div[contains(@class, "profileDrawerHeader")]/button'
PROF_CHANGE_IMG = 'xpath://div[contains(@class, "containerAvt")]/button'
PROF_IMG = 'id:contained-button-file'
PROF_SAVE_IMG = 'xpath://div[contains(@class, "actionRight")]/button[1]'
PROF_CLOSE_IMG = 'xpath://div[contains(@class, "actionRight")]/button[2]'
PROF_REMOVE_IMG = 'xpath://div[contains(@class, "actions")]/button'
PROF_LOADING = 'xpath://div[contains(@class,"loadingIndicator")]'
PROF_AVATAR_RM = 'xpath://div[contains(@class,"profileDrawerContent")]//span/div'
PROF_AVATAR_UPLOADED = 'xpath://div[contains(@class, "avtUploaded")]/img'
PROF_PICTURE_MODAL = 'xpath://div[contains(@class,"containerModal")]'
PROF_BASIC_INFOR_TAB = 'xpath://div[@aria-label="wrapped label tabs example"]/button[1]'
PROF_CONTACT_INFOR_TAB = 'xpath://div[@aria-label="wrapped label tabs example"]/button[2]'
PROF_COUNTRY_INPUT = 'xpath://div[contains(@class,"ant-select-selector")]'
PROF_COUNTRY_OPTION = 'xpath://div[contains(@class,"ant-select-item-option-content")]'
PROF_PHONE_NUMBER = 'name:phoneNumber'
PROF_ADDRESS_INPUT = 'xpath:(//div[contains(@class,"control")]//div/input)[1]'
PROF_ADD_CITY_OPTION = 'xpath://div[contains(@class,"custom-select-input")]//div[contains(@class, "-menu")]//div[@id]'
PROF_CITY_INPUT = 'xpath:(//div[contains(@class,"control")]//div/input)[2]'
PROF_STATE = 'name:state'
PROF_ZIPCODE = 'name:zip'
# Complete Profile
CP_SAVE = 'xpath://div[contains(@class, "completeProfileContentInfo")]//button[2]'
CP_BACK = 'xpath://div[contains(@class, "completeProfileContentInfo")]//button[1]'
CP_CONTINUE = 'xpath://div[contains(@class,"bodyIndex")]//button'
CP_FIRSTNAME = 'name:firstName'
CP_LASTNAME = 'name:lastName'
CP_DATE = 'xpath://div[contains(@class, "ant-picker-input")]/input'
CP_GENDER = 'name:gender'
CP_SYS_MEASUREMENT = 'xpath://div[contains(@class, "style_measurement")]/div/div'
CP_HEIGHT_FT = 'name:fts'
CP_HEIGHT_IN = 'name:ins'
CP_HEIGHT_CM = 'name:height'
CP_WEIGHT_LBS = 'name:lbs'
CP_WEIGHT_KG = 'name:weight'
