# Upgrade Biosphere+ Common
UPG_BIOSPEREPLUS = 'xpath:(//div[contains(@class, "account_container")]//button[contains(@class, "MuiButton-root")])[2]'
# Upgrade Biosphere+ Step 1
UPG_PACKAGES_OPTION = 'xpath://div[contains(@class, "step1_cardHeader")]'
UPG_NEXT = 'xpath:(//div[contains(@class, "purchaseModal")]//button)[2]'
# Upgrade Biosphere+ Step 2
UPG_BILLING_PLAN = 'xpath://div[contains(@class, "step2_planPrice")]'
UPG_EMAIL = 'xpath://input[@name="email"]'
UPG_COUNTRY = 'xpath://div[contains(@class, "step2_country")]'
UPG_OPTION = 'xpath://div[contains(@class, "MuiPaper-root")]/ul/li'
UPG_ADDRESS_INPUT = 'xpath:(//div[contains(@class, "step2_contentBill")]/div[3]//input)[1]'
UPG_ADDRESS_CITY_OPTION = 'xpath://div[contains(@class, "step2_contentBill")]//div[contains(@class, "-menu")]//div[@id]'
UPG_CITY_INPUT = 'xpath:(//div[contains(@class, "step2_contentBill")]/div[4]//input)[1]'
UPG_STATE = 'xpath://input[@name="state"]'
UPG_ZIP_CODE = 'xpath://input[@name="zip"]'
UPG_PHONE_CODE = 'xpath://div[contains(@class, "step2_phoneCode")]'
UPG_PHONE_NUMBER = 'xpath://input[@name="phoneNumber"]'
UPG_TAX_CODE = 'xpath://div[contains(@class, "step2_taxCode")]'
UPG_TAX_ID = 'xpath://input[@name="taxId"]'
UPG_PAY_BTN = 'xpath://div[contains(@class, "purchaseModal_bottom")]//button[contains(@class, "MuiButton-textPrimary")]'
# Upgrade Biosphere+ Step 3
UPG_CC_NUMBER = 'id:cardNumber'
UPG_CARD_EXPIRY = 'id:cardExpiry'
UPG_CARD_CCV = 'id:cardCvc'
UPG_BILLING_NAME = 'id:billingName'
UPG_REGION = 'id:billingCountry'
UPG_REGION_OPTION = 'xpath://select[@name="billingCountry"]/option'
UPG_ENABLE_STRIPE = 'id:enableStripePass'
UPG_PHONE_NUMBER_STRIPE_PASS = 'id:phoneNumber'
UPG_SUBSCRIBE = 'xpath://button[contains(@data-testid, "hosted-payment-submit-button")]'
