# Change Password
SET = 'xpath://div[contains(@class, "sidebar")]//button[2]'
SET_CHANGE_PASS = 'xpath://button[contains(@class, "changePasswordButton")]'
SET_CURRENT_PASS = 'name:currentPassword'
SET_NEW_PASS = 'name:newPassword'
SET_CONFIRM_NEW_PASS = 'name:confirmNewPassword'
SET_UPDATE = 'xpath:(//div[contains(@class, "changePasswordContent")]//button)[4]'
SET_CHANGE_PASS_BACK = 'xpath://div[contains(@class, "backArrow")]//button'
SET_VISIBILITY_PASS = 'xpath://button[contains(@aria-label, "toggle password visibility")]'
# Settings
SET_COMPONENTS_TITLE = 'xpath://p[contains(@class, "settingSectionTitle")]'
SET_HIGH_HR_INPUT = 'xpath:(//div[contains(@class,"ant-collapse-header")])[1]'
SET_BPM_HR_OPTION = 'xpath://div[contains(@class,"heart-rate-item")]'
SET_LOW_HR_INPUT = 'xpath:(//div[contains(@class,"ant-collapse-header")])[2]'
SET_CLOSE = 'xpath://div[contains(@class, "style_settingDrawerHeader")]/button'
SET_HIGH_HR_COLLAPSE = 'xpath:(//div[contains(@class,"ant-collapse-header")])[1]'
SET_LOW_HR_COLLAPSE = 'xpath:(//div[contains(@class,"ant-collapse-header")])[2]'
SET_HIGH_HR_VALUE = 'xpath:(//div[contains(@class,"ant-collapse-content")])[1]//div[contains(@class,"heart-rate-item")]'
SET_LOW_HR_VALUE = 'xpath:(//div[contains(@class,"ant-collapse-content")])[3]//div[contains(@class,"heart-rate-item")]'
SET_HR_SELECTED = 'xpath://div[contains(@class,"ant-collapse-extra")]/p'
